import Foundation
import Testing

@testable import Kikimi

// MARK: - FakeCompletingLLM

/// Deterministic, network-free stand-in for `LLMCompleting` (mirrors `RefinementQueueTests
/// .FakeLLM`'s role), scripted with a fixed response/usage/error at `init` time rather than a
/// mutable queue -- `UsageRecordingLLMTests` only ever needs one canned outcome per test.
private actor FakeCompletingLLM: LLMCompleting {
    private(set) var callCount = 0
    private let responseJSON: String
    private let usage: LLMUsage
    /// Simulates `LLMBackendResponse.respondedModel` (`OpenAIChatBackend`'s Azure-legacy-deployment
    /// case, `docs/design/16-llm-usage-stats.md` section 2). `nil` mirrors `ClaudeCLIBackend`, which
    /// never reports one.
    private let respondedModel: String?
    private let errorToThrow: LLMClientError?

    init(responseJSON: String = "{\"value\":\"ok\"}", usage: LLMUsage = .zero, respondedModel: String? = nil, errorToThrow: LLMClientError? = nil) {
        self.responseJSON = responseJSON
        self.usage = usage
        self.respondedModel = respondedModel
        self.errorToThrow = errorToThrow
    }

    func complete<T: Decodable & Sendable>(_ request: LLMRequest) async throws -> LLMResult<T> {
        callCount += 1
        if let errorToThrow {
            throw errorToThrow
        }
        let value = try JSONDecoder().decode(T.self, from: Data(responseJSON.utf8))
        return LLMResult(value: value, usage: usage, respondedModel: respondedModel)
    }

    /// `docs/design/05-watcher-runner.md` §5.1's raw path, used by `completeRaw(_:)`'s own coverage
    /// below (`UsageRecordingLLM` must record usage identically for both entry points).
    func completeRaw(_ request: LLMRequest) async throws -> LLMResult<Data> {
        callCount += 1
        if let errorToThrow {
            throw errorToThrow
        }
        return LLMResult(value: Data(responseJSON.utf8), usage: usage, respondedModel: respondedModel)
    }
}

// MARK: - DummyValue

private struct DummyValue: Decodable, Sendable {
    let value: String
}

/// Layer 1 coverage for `UsageRecordingLLM` (`docs/design/16-llm-usage-stats.md` section 3): a
/// successful call records exactly one `llm_usage.jsonl` line with `purpose == stubKey` and posts
/// `.kikimiLLMUsageRecorded`; a failing call records nothing and rethrows unchanged.
@Suite("UsageRecordingLLM")
struct UsageRecordingLLMTests {
    private func makeTempSessionDirectory() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("UsageRecordingLLMTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func baseMeta(id: String = "2026-07-01T14-30-00_a1b2c3d4") -> SessionMeta {
        SessionMeta(
            id: id,
            title: "Test Session",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_010),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func makeRequest(model: String = "claude-haiku-4-5-20251001", stubKey: String? = "refinement", provider: String? = nil) -> LLMRequest {
        LLMRequest(system: "system", user: "user", schema: "{}", model: model, stubKey: stubKey, provider: provider)
    }

    // MARK: - Success path

    @Test("complete(_:) appends exactly one llm_usage.jsonl record with purpose == stubKey on success")
    func completeRecordsUsageOnSuccess() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let base = FakeCompletingLLM(
            usage: LLMUsage(inputTokens: 100, outputTokens: 50, cacheReadInputTokens: 10, cacheCreationInputTokens: 0, totalCostUSD: 0.01)
        )
        let recorder = UsageRecordingLLM(base: base, sessionHandle: handle, now: { Date(timeIntervalSince1970: 1_751_000_500) })

        let result: LLMResult<DummyValue> = try await recorder.complete(makeRequest())
        #expect(result.value.value == "ok")

        let records = try await handle.readLLMUsageRecords()
        #expect(records.count == 1)
        let record = try #require(records.first)
        #expect(record.purpose == "refinement")
        #expect(record.model == "claude-haiku-4-5-20251001")
        #expect(record.inputTokens == 100)
        #expect(record.outputTokens == 50)
        #expect(record.cacheReadInputTokens == 10)
        #expect(record.cacheCreationInputTokens == 0)
        #expect(record.reportedCostUSD == 0.01)
        #expect(record.timestamp == Date(timeIntervalSince1970: 1_751_000_500))
    }

    @Test("complete(_:) records the backend's respondedModel instead of request.model when the backend reports one")
    func completeRecordsRespondedModelOverRequestModel() async throws {
        // Mirrors the Azure legacy deployment bug this covers: `refinement.model` defaults to
        // `claude-haiku-4-5-20251001` in the request, but the endpoint actually answered with
        // `gpt-5.4-nano` -- `llm_usage.jsonl` must record the model that actually answered, not the
        // configured default (`docs/design/16-llm-usage-stats.md` section 2).
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let base = FakeCompletingLLM(respondedModel: "gpt-5.4-nano")
        let recorder = UsageRecordingLLM(base: base, sessionHandle: handle)

        let _: LLMResult<DummyValue> = try await recorder.complete(makeRequest(model: "claude-haiku-4-5-20251001"))

        let records = try await handle.readLLMUsageRecords()
        #expect(records.first?.model == "gpt-5.4-nano")
    }

    @Test("complete(_:) falls back to request.model when the backend reports no respondedModel")
    func completeFallsBackToRequestModelWhenRespondedModelNil() async throws {
        // `ClaudeCLIBackend`'s envelope never carries a `respondedModel`, so this must keep recording
        // `request.model` exactly as before this fallback was introduced.
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let recorder = UsageRecordingLLM(base: FakeCompletingLLM(respondedModel: nil), sessionHandle: handle)

        let _: LLMResult<DummyValue> = try await recorder.complete(makeRequest(model: "claude-haiku-4-5-20251001"))

        let records = try await handle.readLLMUsageRecords()
        #expect(records.first?.model == "claude-haiku-4-5-20251001")
    }

    @Test("completeRaw(_:) records the backend's respondedModel instead of request.model when the backend reports one")
    func completeRawRecordsRespondedModelOverRequestModel() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let base = FakeCompletingLLM(responseJSON: "{\"source_seg_id\":\"seg_00001\"}", respondedModel: "gpt-5.4-nano")
        let recorder = UsageRecordingLLM(base: base, sessionHandle: handle)

        _ = try await recorder.completeRaw(makeRequest(model: "claude-haiku-4-5-20251001", stubKey: "watcher_pre-check"))

        let records = try await handle.readLLMUsageRecords()
        #expect(records.first?.model == "gpt-5.4-nano")
    }

    @Test("complete(_:) records request.provider on the llm_usage.jsonl line (docs/design/44-llm-model-config.md §7)")
    func completeRecordsRequestProvider() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let recorder = UsageRecordingLLM(base: FakeCompletingLLM(), sessionHandle: handle)

        let _: LLMResult<DummyValue> = try await recorder.complete(makeRequest(provider: "azure"))

        let records = try await handle.readLLMUsageRecords()
        #expect(records.first?.provider == "azure")
    }

    @Test("complete(_:) records a nil provider unchanged when the request never set one")
    func completeRecordsNilProviderWhenRequestHasNone() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let recorder = UsageRecordingLLM(base: FakeCompletingLLM(), sessionHandle: handle)

        let _: LLMResult<DummyValue> = try await recorder.complete(makeRequest())

        let records = try await handle.readLLMUsageRecords()
        #expect(records.first?.provider == nil)
    }

    @Test("complete(_:) records purpose \"unknown\" when the request carries no stubKey")
    func completeRecordsUnknownPurposeWhenStubKeyMissing() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let recorder = UsageRecordingLLM(base: FakeCompletingLLM(), sessionHandle: handle)

        let _: LLMResult<DummyValue> = try await recorder.complete(makeRequest(stubKey: nil))

        let records = try await handle.readLLMUsageRecords()
        #expect(records.first?.purpose == "unknown")
    }

    @Test("complete(_:) stores reportedCostUSD as nil when the backend's totalCostUSD is zero")
    func completeStoresNilCostWhenTotalCostIsZero() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let base = FakeCompletingLLM(
            usage: LLMUsage(inputTokens: 10, outputTokens: 5, cacheReadInputTokens: 0, cacheCreationInputTokens: 0, totalCostUSD: 0)
        )
        let recorder = UsageRecordingLLM(base: base, sessionHandle: handle)

        let _: LLMResult<DummyValue> = try await recorder.complete(makeRequest())

        let records = try await handle.readLLMUsageRecords()
        #expect(records.first?.reportedCostUSD == nil)
    }

    @Test("complete(_:) posts .kikimiLLMUsageRecorded with this session's id after a successful record")
    func completePostsNotificationWithSessionId() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(id: "2026-07-01T14-30-00_a1b2c3d4"))
        let recorder = UsageRecordingLLM(base: FakeCompletingLLM(), sessionHandle: handle)

        var receivedSessionId: String?
        let observer = NotificationCenter.default.addObserver(forName: .kikimiLLMUsageRecorded, object: nil, queue: nil) { notification in
            receivedSessionId = notification.userInfo?["sessionId"] as? String
        }
        defer { NotificationCenter.default.removeObserver(observer) }

        let _: LLMResult<DummyValue> = try await recorder.complete(makeRequest())

        #expect(receivedSessionId == "2026-07-01T14-30-00_a1b2c3d4")
    }

    // MARK: - completeRaw (`docs/design/05-watcher-runner.md` §5.1)

    @Test("completeRaw(_:) appends exactly one llm_usage.jsonl record with purpose == stubKey on success")
    func completeRawRecordsUsageOnSuccess() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let base = FakeCompletingLLM(
            responseJSON: "{\"source_seg_id\":\"seg_00001\"}",
            usage: LLMUsage(inputTokens: 20, outputTokens: 10, cacheReadInputTokens: 0, cacheCreationInputTokens: 0, totalCostUSD: 0.002)
        )
        let recorder = UsageRecordingLLM(base: base, sessionHandle: handle, now: { Date(timeIntervalSince1970: 1_751_000_600) })

        let result = try await recorder.completeRaw(makeRequest(stubKey: "watcher_pre-check"))
        #expect(String(data: result.value, encoding: .utf8) == "{\"source_seg_id\":\"seg_00001\"}")

        let records = try await handle.readLLMUsageRecords()
        #expect(records.count == 1)
        let record = try #require(records.first)
        #expect(record.purpose == "watcher_pre-check")
        #expect(record.inputTokens == 20)
        #expect(record.outputTokens == 10)
        #expect(record.timestamp == Date(timeIntervalSince1970: 1_751_000_600))
    }

    @Test("completeRaw(_:) does not record anything and rethrows unchanged when base throws")
    func completeRawDoesNotRecordAndRethrowsOnFailure() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let recorder = UsageRecordingLLM(base: FakeCompletingLLM(errorToThrow: .timedOut(.seconds(1))), sessionHandle: handle)

        await #expect(throws: LLMClientError.timedOut(.seconds(1))) {
            _ = try await recorder.completeRaw(makeRequest())
        }

        let records = try await handle.readLLMUsageRecords()
        #expect(records.isEmpty)
    }

    // MARK: - Failure path

    @Test("complete(_:) does not record anything and rethrows unchanged when base throws")
    func completeDoesNotRecordAndRethrowsOnFailure() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let recorder = UsageRecordingLLM(base: FakeCompletingLLM(errorToThrow: .timedOut(.seconds(1))), sessionHandle: handle)

        await #expect(throws: LLMClientError.timedOut(.seconds(1))) {
            let _: LLMResult<DummyValue> = try await recorder.complete(makeRequest())
        }

        let records = try await handle.readLLMUsageRecords()
        #expect(records.isEmpty)
    }
}
