import Foundation
import Testing

@testable import Kikimi

// MARK: - FakeLLM

/// Deterministic, network-free stand-in for `LLMCompleting` (`docs/design/04-summary-updater.md`
/// §4.1's SWE review C8: inject the narrow seam, not the concrete `LLMClient`). An `actor` so
/// call-count/received-request assertions are race-free, mirroring `LLMClientTests.swift`'s
/// `FakeProcessRunner`.
///
/// Responses are registered per `stubKey` as raw JSON strings and decoded into whatever `T` the
/// caller asks for -- this mirrors `LLMStubProvider`'s own dispatch-by-`stubKey` shape closely
/// enough that the fixtures read the same way.
private actor FakeLLM: LLMCompleting {
    private(set) var callCount = 0
    private(set) var receivedRequests: [LLMRequest] = []

    /// `stubKey -> raw JSON`. A missing key throws `.missingStructuredOutput`, matching
    /// `LLMStubProvider`'s own safe-default behavior.
    var responses: [String: String] = [:]
    /// `stubKey -> error` overrides `responses` when both are set for the same key.
    var errors: [String: LLMClientError] = [:]

    func complete<T: Decodable & Sendable>(_ request: LLMRequest) async throws -> LLMResult<T> {
        let data = try resolveData(for: request)
        // Mirror `LLMClient.decodeResult`'s `.convertFromSnakeCase` decoding of `structured_output`
        // so snake_case fixture keys (`decisions_add`/`source_seg_ids`/...) map onto the camelCase
        // `SummaryPatch`/`SummaryState` properties exactly as they would in production.
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let value = try decoder.decode(T.self, from: data)
        return LLMResult(value: value, usage: .zero)
    }

    /// `docs/design/05-watcher-runner.md` §5.1: not exercised by any `SummaryUpdater` test in this
    /// file, but required to satisfy `LLMCompleting`.
    func completeRaw(_ request: LLMRequest) async throws -> LLMResult<Data> {
        LLMResult(value: try resolveData(for: request), usage: .zero)
    }

    private func resolveData(for request: LLMRequest) throws -> Data {
        callCount += 1
        receivedRequests.append(request)
        let key = request.stubKey ?? ""
        if let error = errors[key] {
            throw error
        }
        guard let rawJSON = responses[key], let data = rawJSON.data(using: .utf8) else {
            throw LLMClientError.missingStructuredOutput(raw: "no fake response for stubKey=\(key)")
        }
        return data
    }
}

// MARK: - Test helpers

@Suite("SummaryUpdater")
struct SummaryUpdaterTests {
    private func makeTempSessionDirectory() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("SummaryUpdaterTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func baseMeta(
        id: String = "2026-07-01T14-30-00_a1b2c3d4",
        title: String = "",
        titleAutoGenerated: Bool = true,
        titleAutoNamedOnce: Bool = false,
        titleProposal: String? = nil
    ) -> SessionMeta {
        SessionMeta(
            id: id,
            title: title,
            titleAutoGenerated: titleAutoGenerated,
            titleAutoNamedOnce: titleAutoNamedOnce,
            titleProposal: titleProposal,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_010),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func makeHandle(directory: URL, meta: SessionMeta) -> SessionHandle {
        SessionHandle(directoryURL: directory, meta: meta)
    }

    /// Appends `count` transcript segments (500ms apart, starting at `startingAt`), alternating
    /// mic/system, to `handle`'s `transcript.jsonl`.
    @discardableResult
    private func appendSegments(
        _ count: Int,
        to handle: SessionHandle,
        startingAt: Int = 0,
        stepMs: Int = 500,
        textPrefix: String = "segment"
    ) async throws -> [TranscriptSegment] {
        var results: [TranscriptSegment] = []
        for index in 0..<count {
            let startMs = startingAt + index * stepMs
            let segment = try await handle.appendTranscriptSegment(
                source: index.isMultiple(of: 2) ? .mic : .system,
                startMs: startMs,
                endMs: startMs + stepMs,
                text: "\(textPrefix) \(index)",
                confidence: 0.9
            )
            results.append(segment)
        }
        return results
    }

    /// Mirrors `SessionHandleTranscriptTests.swift`'s helper of the same name: builds a
    /// `RefinedSegment` for direct `appendRefinedSegment` calls, so tests can put more than one
    /// refined row under the same `id` (something `SessionHandle` itself never does — see
    /// `loadDuplicateRefinedIdDoesNotCrashAndLastRowWins` below).
    private func makeRefinedSegment(
        id: String,
        startMs: Int = 0,
        endMs: Int = 1_000,
        refinedText: String?
    ) -> RefinedSegment {
        RefinedSegment(
            id: id,
            startMs: startMs,
            endMs: endMs,
            speaker: .mic,
            rawText: "raw text",
            refinedText: refinedText,
            error: nil,
            refinedAt: Date(timeIntervalSince1970: 1_751_000_020),
            model: "claude-haiku-4-5-20251001",
            batchId: "batch_00001"
        )
    }

    private let patchJSONWithTitle = """
    {"title":"新タイトル","participants_add":null,"overview":"概要です","decisions_add":null,"action_items":null}
    """
    private let emptyPatchJSON = """
    {"title":null,"participants_add":null,"overview":null,"decisions_add":null,"action_items":null}
    """

    // MARK: - Triggers (§4.2)

    @Test("noteSegmentAppended triggers an automatic update once the segment threshold is reached")
    func segmentThresholdTriggersUpdate() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(20, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")

        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM, config: SummaryConfig())
        for _ in 0..<20 {
            await updater.noteSegmentAppended()
        }

        try await waitUntil { await fakeLLM.callCount >= 1 }

        let state = try await handle.readJSON(.summaryState, as: SummaryState.self)
        #expect(state?.overview == "概要です")
        let markdown = try await handle.readText(.summaryMarkdown)
        #expect(markdown != nil)
    }

    @Test("noteSegmentAppended triggers an automatic update after the time threshold elapses, even below the segment threshold")
    func timeThresholdTriggersUpdate() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(3, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(emptyPatchJSON, for: "summary_patch")

        // A near-zero time threshold so the timer fires almost immediately without a real sleep.
        let config = SummaryConfig(updateTriggerSegments: 20, updateTriggerSeconds: 0)
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM, config: config)
        for _ in 0..<3 {
            await updater.noteSegmentAppended()
        }

        try await waitUntil { await fakeLLM.callCount >= 1 }
    }

    @Test("an update with no unsummarized segments does not call the LLM")
    func emptyPendingInputSkipsLLMCall() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        // No segments appended at all.

        let fakeLLM = FakeLLM()
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        await updater.updateNow(reason: .manual)

        #expect(await fakeLLM.callCount == 0)
        let state = try await handle.readJSON(.summaryState, as: SummaryState.self)
        #expect(state == nil)
    }

    // MARK: - Update flow persists state/markdown/events (§4.3)

    @Test("updateNow(.manual) persists summary.state.json and summary.md and yields an event")
    func manualUpdatePersistsStateAndMarkdownAndYieldsEvent() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(5, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")

        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)
        var eventsIterator = updater.events.makeAsyncIterator()

        await updater.updateNow(reason: .manual)

        let event = try #require(await eventsIterator.next())
        #expect(event.summaryMarkdown != nil)
        #expect(event.summaryMarkdown?.contains("概要です") == true)

        let state = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        #expect(state.overview == "概要です")
        #expect(state.lastSummarizedStartMs == 4 * 500) // last of 5 segments, stepMs 500, 0-indexed
    }

    @Test("an incremental update's LLM request.system reflects promptBodyProvider(.summary) plus the fixed patch contract (docs/design/42-prompt-overrides.md §4.3, immediate reload)")
    func incrementalUpdateSystemPromptUsesInjectedProviderPlusContract() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(5, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")

        let injectedPolicyBody = "テスト用の方針層本文"
        let updater = SummaryUpdater(
            sessionHandle: handle, llm: fakeLLM,
            promptBodyProvider: { id in id == .summary ? injectedPolicyBody : "unexpected id: \(id)" }
        )
        await updater.updateNow(reason: .manual)

        let request = try #require(await fakeLLM.receivedRequests.first)
        #expect(request.system == SummaryPromptBuilder.systemPrompt(policyBody: injectedPolicyBody))
    }

    @Test("pauseFlush reflects fewer than the segment threshold's worth of pending segments")
    func pauseFlushReflectsPartialBatch() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(7, to: handle) // fewer than default threshold of 20

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")

        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)
        await updater.updateNow(reason: .pauseFlush)

        #expect(await fakeLLM.callCount == 1)
        let state = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        #expect(state.lastSummarizedStartMs == 6 * 500)
    }

    // MARK: - LLM failure (§9)

    @Test("LLM failure during an update leaves state/cursor unchanged and does not throw")
    func llmFailureLeavesStateUnchanged() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(5, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setError(.processFailed(exitCode: 1, stderr: "boom"), for: "summary_patch")

        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)
        await updater.updateNow(reason: .manual) // must not throw / crash

        let state = try await handle.readJSON(.summaryState, as: SummaryState.self)
        #expect(state == nil) // never written

        // A subsequent successful call still works normally (no poisoned internal state).
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")
        await updater.updateNow(reason: .manual)
        let recovered = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        #expect(recovered.overview == "概要です")
    }

    // MARK: - Cursor / high-water mark (§4.2)

    @Test("cursor uses strict > so a segment with startMs equal to the cursor is not re-included")
    func cursorUsesStrictGreaterThan() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        // Two segments sharing the same startMs (mic/system same-timestamp collision, §4.2's C10).
        _ = try await handle.appendTranscriptSegment(source: .mic, startMs: 1_000, endMs: 1_500, text: "first", confidence: 0.9)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(emptyPatchJSON, for: "summary_patch")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)
        await updater.updateNow(reason: .manual)
        #expect(await fakeLLM.callCount == 1)

        // A second segment at the exact same startMs=1000 arrives after the cursor was set to 1000.
        _ = try await handle.appendTranscriptSegment(source: .system, startMs: 1_000, endMs: 1_500, text: "same-time-collision", confidence: 0.9)
        await updater.updateNow(reason: .manual)

        // Documenting current (accepted) behavior: the same-startMs segment is dropped because the
        // cursor comparison is strict `>` (04-summary-updater.md §4.2's "等値 startMs の境界" caveat).
        #expect(await fakeLLM.callCount == 1)
    }

    @Test("loadPendingInput resolves a merged unit's non-leading source_seg_id to the same (already-refined) unit, not a raw fallback (§15.2.5)")
    func loadPendingInputExpandsMergedSourceSegIds() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        let segments = try await appendSegments(2, to: handle, textPrefix: "raw")

        // One merged derived unit covering both raw segments -- segments[1]'s own id never appears
        // as a top-level `id` in refined.jsonl, only inside `source_seg_ids` (§15.2.1).
        let mergedUnit = RefinedSegment(
            id: segments[0].id,
            startMs: segments[0].startMs,
            endMs: segments[1].endMs,
            speaker: .mic,
            rawText: "raw 0raw 1",
            refinedText: "整形済み結合テキスト",
            error: nil,
            refinedAt: Date(timeIntervalSince1970: 1_751_000_020),
            model: "claude-haiku-4-5-20251001",
            batchId: "batch_00001",
            sourceSegIds: [segments[0].id, segments[1].id]
        )
        try await handle.appendRefinedSegment(mergedUnit)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(emptyPatchJSON, for: "summary_patch")
        let config = SummaryConfig(updateTriggerSegments: 2, updateTriggerSeconds: 999)
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM, config: config)
        await updater.noteSegmentAppended()
        await updater.noteSegmentAppended()

        try await waitUntil { await fakeLLM.callCount >= 1 }

        let request = try #require(await fakeLLM.receivedRequests.first)
        #expect(request.user.contains("整形済み結合テキスト"), "both raw segments must resolve to the merged unit's refined text")
        #expect(!request.user.contains("raw 1"), "segments[1] (covered, non-leading) must not fall back to its own raw text")
    }

    @Test("a duplicate refined id in refined.jsonl does not crash loadPendingInput and the later row wins")
    func loadPendingInputToleratesDuplicateRefinedIdLastRowWins() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(1, to: handle, startingAt: 1_000, stepMs: 500)

        // Simulate a hand-edited / doubly-appended refined.jsonl: two rows share the same seg id
        // (03-refinement-batch.md §3.2's "防御の二重化" — `RefinementQueue`'s `knownIds` set is
        // supposed to prevent this from ever happening via the normal write path, but
        // `loadPendingInput()` must still degrade gracefully rather than trap via
        // `Dictionary(uniqueKeysWithValues:)` if it does).
        try await handle.appendRefinedSegment(makeRefinedSegment(id: "seg_00001", startMs: 1_000, refinedText: "古い整形結果"))
        try await handle.appendRefinedSegment(makeRefinedSegment(id: "seg_00001", startMs: 1_000, refinedText: "新しい整形結果"))

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(emptyPatchJSON, for: "summary_patch")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        // Must not crash / trap.
        await updater.updateNow(reason: .manual)

        #expect(await fakeLLM.callCount == 1)
        let sentUserPrompt = await fakeLLM.receivedRequests.first?.user
        #expect(sentUserPrompt?.contains("新しい整形結果") == true)
        #expect(sentUserPrompt?.contains("古い整形結果") == false)
    }

    // MARK: - Automatic title state machine (§3.1, §10)

    @Test("first automatic title patch reflects directly into meta.title and sets titleAutoNamedOnce")
    func firstAutoTitleReflectsDirectly() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta(title: "", titleAutoGenerated: true, titleAutoNamedOnce: false))
        try await appendSegments(5, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        await updater.updateNow(reason: .manual)

        let meta = await handle.meta
        #expect(meta.title == "新タイトル")
        #expect(meta.titleAutoNamedOnce == true)
        #expect(meta.titleProposal == nil)
    }

    @Test("second and later automatic title patches only set titleProposal, not meta.title")
    func secondAutoTitleOnlySetsProposal() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta(title: "初回タイトル", titleAutoGenerated: true, titleAutoNamedOnce: true))
        try await appendSegments(5, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch") // proposes "新タイトル"
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        await updater.updateNow(reason: .manual)

        let meta = await handle.meta
        #expect(meta.title == "初回タイトル") // unchanged
        #expect(meta.titleProposal == "新タイトル")
    }

    @Test("after manual title edit (titleAutoGenerated == false), automatic title patches do nothing")
    func manuallyEditedTitleSuppressesAutoTitle() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta(title: "ユーザーが決めたタイトル", titleAutoGenerated: false, titleAutoNamedOnce: true))
        try await appendSegments(5, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        await updater.updateNow(reason: .manual)

        let meta = await handle.meta
        #expect(meta.title == "ユーザーが決めたタイトル")
        #expect(meta.titleProposal == nil)
    }

    @Test("autoNaming == false suppresses automatic title reflection entirely")
    func autoNamingDisabledSuppressesTitle() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta(title: "", titleAutoGenerated: true, titleAutoNamedOnce: false))
        try await appendSegments(5, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")
        let config = SummaryConfig(autoNaming: false)
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM, config: config)

        await updater.updateNow(reason: .manual)

        let meta = await handle.meta
        #expect(meta.title == "")
        #expect(meta.titleAutoNamedOnce == false)
        #expect(meta.titleProposal == nil)
    }

    // MARK: - Final title proposal (§3.4)

    @Test("generateFinalTitleProposal sets titleProposal but never auto-reflects into meta.title")
    func finalTitleProposalSetsProposalOnly() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta(title: "既存タイトル", titleAutoGenerated: true, titleAutoNamedOnce: true))
        // Seed some state so the final-title prompt has material to work from.
        try await handle.writeJSON(
            SummaryState(title: "既存タイトル", participants: [], overview: "最終概要", decisions: [], actionItems: [], lastSummarizedStartMs: 1_000),
            to: .summaryState
        )

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(#"{"title":"最終提案タイトル"}"#, for: "final_title")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        await updater.generateFinalTitleProposal()

        let meta = await handle.meta
        #expect(meta.title == "既存タイトル") // unchanged
        #expect(meta.titleProposal == "最終提案タイトル")
    }

    @Test("generateFinalTitleProposal's LLM request.system is exactly promptBodyProvider(.finalTitle) (no contract layer for final-title, docs/design/42-prompt-overrides.md §2.2)")
    func finalTitleProposalSystemPromptUsesInjectedProviderVerbatim() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta(title: "既存タイトル", titleAutoGenerated: true, titleAutoNamedOnce: true))
        try await handle.writeJSON(
            SummaryState(title: "既存タイトル", participants: [], overview: "最終概要", decisions: [], actionItems: [], lastSummarizedStartMs: 1_000),
            to: .summaryState
        )

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(#"{"title":"最終提案タイトル"}"#, for: "final_title")

        let injectedPolicyBody = "テスト用の final-title 方針層本文"
        let updater = SummaryUpdater(
            sessionHandle: handle, llm: fakeLLM,
            promptBodyProvider: { id in id == .finalTitle ? injectedPolicyBody : "unexpected id: \(id)" }
        )
        await updater.generateFinalTitleProposal()

        let request = try #require(await fakeLLM.receivedRequests.first)
        #expect(request.system == injectedPolicyBody)
    }

    // MARK: - Full regeneration (§6)

    @Test("regenerateFromScratch rebuilds summary.state.json/summary.md idempotently from all segments")
    func regenerateFromScratchIsIdempotent() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(45, to: handle) // spans two chunks (40 + 5)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        await updater.regenerateFromScratch()
        let firstCallCount = await fakeLLM.callCount
        #expect(firstCallCount == 2) // two chunks: 40 + 5

        let firstState = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        #expect(firstState.overview == "概要です")

        // Idempotent: running again from scratch produces the same shape of result.
        await updater.regenerateFromScratch()
        let secondState = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        #expect(secondState.overview == firstState.overview)
        #expect(secondState.lastSummarizedStartMs == firstState.lastSummarizedStartMs)
    }

    // MARK: - §9 participant context injection (docs/design/22-participant-hints.md §9)

    private func makeVoiceprintStore(directory: URL) -> VoiceprintStore {
        VoiceprintStore(fileURL: directory.appendingPathComponent("voiceprints.json"))
    }

    @Test("a non-empty roster injects a 【参加者】 block into the incremental update's user prompt")
    func rosterInjectsParticipantBlockIntoIncrementalUpdate() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(5, to: handle)
        try await handle.writeContext("アジェンダ: 進捗確認")

        let voiceprintStore = makeVoiceprintStore(directory: directory)
        let tanaka = try await voiceprintStore.registerSpeaker(name: "田中さん", embedding: [])
        try await handle.updateParticipants { participants in
            participants.participantIds = [tanaka.id]
        }

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM, voiceprintStore: voiceprintStore)

        await updater.updateNow(reason: .manual)

        let requests = await fakeLLM.receivedRequests
        #expect(requests.count == 1)
        #expect(requests[0].user.contains("アジェンダ: 進捗確認"))
        #expect(requests[0].user.contains("【参加者】\n田中さん"))
    }

    @Test("an empty roster leaves the incremental update's user prompt exactly as before (no 【参加者】 block)")
    func emptyRosterLeavesIncrementalUpdatePromptUnchanged() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(5, to: handle)
        try await handle.writeContext("アジェンダ: 進捗確認")

        let voiceprintStore = makeVoiceprintStore(directory: directory)
        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM, voiceprintStore: voiceprintStore)

        await updater.updateNow(reason: .manual)

        let requests = await fakeLLM.receivedRequests
        #expect(requests.count == 1)
        #expect(requests[0].user.contains("アジェンダ: 進捗確認"))
        #expect(!requests[0].user.contains("【参加者】"))
    }

    @Test("a non-empty roster injects a 【参加者】 block into every chunk's user prompt during full regeneration")
    func rosterInjectsParticipantBlockIntoRegeneration() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(45, to: handle) // spans two chunks (40 + 5)
        try await handle.writeContext("アジェンダ: 進捗確認")

        let voiceprintStore = makeVoiceprintStore(directory: directory)
        let tanaka = try await voiceprintStore.registerSpeaker(name: "田中さん", embedding: [])
        try await handle.updateParticipants { participants in
            participants.participantIds = [tanaka.id]
        }

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(patchJSONWithTitle, for: "summary_patch")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM, voiceprintStore: voiceprintStore)

        await updater.regenerateFromScratch()

        let requests = await fakeLLM.receivedRequests
        #expect(requests.count == 2)
        for request in requests {
            #expect(request.user.contains("【参加者】\n田中さん"))
        }
    }

    // MARK: - Serialization (§4.1.1)

    @Test("concurrent manual and threshold-triggered updates do not lose updates or double-apply a patch")
    func concurrentUpdatesDoNotRaceOrDoubleApply() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(20, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(#"""
        {"title":null,"participants_add":null,"overview":null,"decisions_add":[{"text":"決定A","source_seg_ids":["seg_00001"]}],"action_items":null}
        """#, for: "summary_patch")

        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM, config: SummaryConfig(updateTriggerSegments: 20))

        // Interleave a threshold trigger (via noteSegmentAppended) with concurrent manual calls.
        await withTaskGroup(of: Void.self) { group in
            group.addTask { await updater.updateNow(reason: .manual) }
            group.addTask { await updater.updateNow(reason: .manual) }
            group.addTask { await updater.updateNow(reason: .manual) }
        }

        let state = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        // The same decision text must not be duplicated even though multiple update calls raced
        // (applyPatch's own de-duplication, exercised end-to-end through the serialized updater).
        #expect(state.decisions.count == 1)
        #expect(state.decisions.first?.text == "決定A")
    }

    // MARK: - mergeParticipants(_:) (docs/design/13-speaker-diarization.md §6.2, "R2 module 4")

    @Test("mergeParticipants merges new names, dedupes exact matches against existing participants, and re-renders summary.md")
    func mergeParticipantsMergesAndDedupes() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await handle.writeJSON(
            SummaryState(title: nil, participants: ["田中さん"], overview: "", decisions: [], actionItems: [], lastSummarizedStartMs: nil),
            to: .summaryState
        )

        let fakeLLM = FakeLLM()
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)
        var eventsIterator = updater.events.makeAsyncIterator()

        await updater.mergeParticipants(["田中さん", "佐藤さん"])

        let event = try #require(await eventsIterator.next())
        #expect(event.metaChanged == false)
        #expect(event.summaryMarkdown?.contains("佐藤さん") == true)

        let state = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        // "田中さん" already present -> not duplicated; "佐藤さん" newly appended, order preserved.
        #expect(state.participants == ["田中さん", "佐藤さん"])
        // The LLM must never be invoked for a pure participants merge.
        #expect(await fakeLLM.callCount == 0)
    }

    @Test("mergeParticipants starts from SummaryState.empty when no summary.state.json exists yet")
    func mergeParticipantsWithNoPriorState() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())

        let fakeLLM = FakeLLM()
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        await updater.mergeParticipants(["田中さん"])

        let state = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        #expect(state.participants == ["田中さん"])
        #expect(state.overview == "") // untouched, still SummaryState.empty's default
    }

    @Test("mergeParticipants with every name already present is a silent no-op: no write, no event")
    func mergeParticipantsAllAlreadyPresentIsNoOp() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await handle.writeJSON(
            SummaryState(title: nil, participants: ["田中さん"], overview: "既存概要", decisions: [], actionItems: [], lastSummarizedStartMs: 1_000),
            to: .summaryState
        )

        let fakeLLM = FakeLLM()
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)
        var eventsIterator = updater.events.makeAsyncIterator()

        await updater.mergeParticipants(["田中さん"])

        // No event fired -- nothing changed, so `mergeParticipants` returns without ever writing to
        // `eventsContinuation`. Prove no event arrived (rather than blocking forever waiting for one)
        // by racing against a manual update, whose event is guaranteed to arrive (startMs must be
        // past the seeded state's lastSummarizedStartMs=1000 cursor, or this segment would itself be
        // filtered out as already-summarized and never produce an event either).
        await fakeLLM.setResponse(emptyPatchJSON, for: "summary_patch")
        try await appendSegments(1, to: handle, startingAt: 2_000)
        await updater.updateNow(reason: .manual)
        let firstEvent = try #require(await eventsIterator.next())
        #expect(firstEvent.summaryMarkdown != nil) // this is the manual update's event, not a merge event

        let state = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        #expect(state.participants == ["田中さん"]) // unchanged by the no-op merge
        #expect(state.overview == "既存概要") // untouched by the no-op merge, then untouched by the empty patch
        // The cursor did advance -- but only because of the manual update that followed, proving the
        // no-op merge itself never touched anything (it ran first, against the still-1_000 cursor).
        #expect(state.lastSummarizedStartMs == 2_000)
    }

    @Test("mergeParticipants never touches lastSummarizedStartMs, even when it moves participants forward")
    func mergeParticipantsDoesNotTouchCursor() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await handle.writeJSON(
            SummaryState(title: nil, participants: [], overview: "", decisions: [], actionItems: [], lastSummarizedStartMs: 5_000),
            to: .summaryState
        )

        let fakeLLM = FakeLLM()
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        await updater.mergeParticipants(["鈴木さん"])

        let state = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        #expect(state.participants == ["鈴木さん"])
        #expect(state.lastSummarizedStartMs == 5_000, "unrelated to any newly-summarized segment; the cursor must be left exactly where it was")
    }

    @Test("a mergeParticipants call coalesced behind an in-flight update still applies once that update completes")
    func mergeParticipantsCoalescesBehindAnInFlightUpdate() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory, meta: baseMeta())
        try await appendSegments(5, to: handle)

        let fakeLLM = FakeLLM()
        await fakeLLM.setResponse(emptyPatchJSON, for: "summary_patch")
        let updater = SummaryUpdater(sessionHandle: handle, llm: fakeLLM)

        // Both requests started concurrently: whichever wins the race runs first and the other
        // coalesces behind it (§4.1.1), but both must eventually be reflected.
        await withTaskGroup(of: Void.self) { group in
            group.addTask { await updater.updateNow(reason: .manual) }
            group.addTask { await updater.mergeParticipants(["田中さん"]) }
        }

        let state = try #require(try await handle.readJSON(.summaryState, as: SummaryState.self))
        #expect(state.participants == ["田中さん"])
    }

    // MARK: - Helpers

    /// Polls `predicate` on a short interval until it returns `true` or a timeout elapses, since
    /// `noteSegmentAppended`'s auto-triggered update runs on a detached `Task` rather than being
    /// directly awaitable.
    private func waitUntil(
        timeout: Duration = .seconds(10),
        predicate: @escaping () async -> Bool
    ) async throws {
        let deadline = ContinuousClock.now + timeout
        while ContinuousClock.now < deadline {
            if await predicate() { return }
            try await Task.sleep(for: .milliseconds(20))
        }
        #expect(await predicate(), "condition did not become true within \(timeout)")
    }
}

// MARK: - FakeLLM configuration helpers

private extension FakeLLM {
    func setResponse(_ json: String, for stubKey: String) {
        responses[stubKey] = json
        errors[stubKey] = nil
    }

    func setError(_ error: LLMClientError, for stubKey: String) {
        errors[stubKey] = error
    }
}
