import Foundation
import Testing

@testable import Kikimi

/// Layer 1 (unit) coverage for `SessionStore`/`SessionHandle`, targeting the scenarios called out
/// in `docs/design/07-session-store.md` section 13. Every test roots `SessionStore` at a fresh
/// temporary directory (via the DI initializer, section 1.1) so nothing here ever touches a real
/// `~/.local/state/kikimi` or `~/.config/kikimi` on the machine running the suite.
@Suite("SessionStore / SessionHandle")
struct SessionStoreTests {
    // MARK: - Fixtures

    private func makeTemporaryDirectory() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("SessionStoreTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    /// Builds a `SessionStore` rooted at a fresh temporary directory. The default context/template/
    /// enabled-watchers files point at nonexistent paths under the same root unless overridden, so
    /// `createDraftSession()`'s fallback behavior (section 8/11, failure mode #2) is exercised by default.
    private func makeStore(
        defaultContextFileURL: URL? = nil,
        defaultSummaryTemplateFileURL: URL? = nil,
        defaultEnabledWatchersFileURL: URL? = nil,
        metaFlushInterval: TimeInterval = 5.0
    ) -> (store: SessionStore, root: URL) {
        let root = makeTemporaryDirectory()
        let store = SessionStore(
            sessionsRootDirectory: root.appendingPathComponent("sessions", isDirectory: true),
            defaultContextFileURL: defaultContextFileURL ?? root.appendingPathComponent("missing-context.md"),
            defaultSummaryTemplateFileURL: defaultSummaryTemplateFileURL ?? root.appendingPathComponent("missing-template.md"),
            defaultEnabledWatchersFileURL: defaultEnabledWatchersFileURL ?? root.appendingPathComponent("missing-enabled.yaml"),
            metaFlushInterval: metaFlushInterval
        )
        return (store, root)
    }

    private func sessionDirectory(root: URL, sessionId: String) -> URL {
        root.appendingPathComponent("sessions", isDirectory: true).appendingPathComponent(sessionId, isDirectory: true)
    }

    // MARK: - Codable round trips (section 13, kikimi.md 5 章)

    @Test("SessionMeta decodes kikimi.md's sample meta.json with snake_case keys and ISO 8601 dates")
    func sessionMetaDecodesKikimiSample() throws {
        let sample = """
        {
          "id": "2026-07-01T14-30-00_a1b2c3d4",
          "title": "デイリースクラム",
          "title_auto_generated": true,
          "title_auto_named_once": true,
          "title_proposal": null,
          "state": "ended",
          "created_at": "2026-07-01T14:28:12Z",
          "started_at": "2026-07-01T14:30:00Z",
          "ended_at": "2026-07-01T15:15:22Z",
          "duration_ms": 2722000,
          "based_on_session": "2026-06-24T14-30-00_x9y8z7w6",
          "segment_count": 342,
          "refined_count": 342,
          "app_version": "0.1.0"
        }
        """
        let meta = try SessionJSONCoding.makeDecoder().decode(SessionMeta.self, from: Data(sample.utf8))

        #expect(meta.id == "2026-07-01T14-30-00_a1b2c3d4")
        #expect(meta.title == "デイリースクラム")
        #expect(meta.titleAutoGenerated)
        #expect(meta.titleAutoNamedOnce)
        #expect(meta.titleProposal == nil)
        #expect(meta.state == .ended)
        #expect(meta.durationMs == 2_722_000)
        #expect(meta.basedOnSession == "2026-06-24T14-30-00_x9y8z7w6")
        #expect(meta.segmentCount == 342)
        #expect(meta.refinedCount == 342)
        #expect(meta.appVersion == "0.1.0")

        let expectedFormatter = ISO8601DateFormatter()
        #expect(meta.createdAt == expectedFormatter.date(from: "2026-07-01T14:28:12Z"))
        #expect(meta.startedAt == expectedFormatter.date(from: "2026-07-01T14:30:00Z"))
        #expect(meta.endedAt == expectedFormatter.date(from: "2026-07-01T15:15:22Z"))
    }

    @Test("SessionMeta round-trips through SessionJSONCoding's encoder/decoder with snake_case keys and ISO 8601 date strings")
    func sessionMetaRoundTripsThroughSessionJSONCoding() throws {
        let meta = SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: "デイリースクラム",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .draft,
            createdAt: Date(timeIntervalSince1970: 1_782_916_092), // 2026-07-01T14:28:12Z
            startedAt: nil,
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )

        let data = try SessionJSONCoding.makeEncoder().encode(meta)
        let jsonObject = try #require(JSONSerialization.jsonObject(with: data) as? [String: Any])

        // Field names on disk must be snake_case, not the Swift camelCase property names.
        #expect(jsonObject["title_auto_generated"] as? Bool == true)
        #expect(jsonObject["title_auto_named_once"] as? Bool == false)
        #expect(jsonObject["segment_count"] as? Int == 0)

        // Dates must be ISO 8601 strings, not Foundation's default epoch-seconds encoding.
        let createdAtString = try #require(jsonObject["created_at"] as? String)
        #expect(createdAtString == "2026-07-01T14:28:12Z")

        let decoded = try SessionJSONCoding.makeDecoder().decode(SessionMeta.self, from: data)
        #expect(decoded == meta)
    }

    @Test("TranscriptSegment/RefinedSegment round-trip kikimi.md's sample line shapes")
    func transcriptAndRefinedSegmentRoundTrip() throws {
        let transcriptSample = """
        {"id": "seg_00042", "start_ms": 125300, "end_ms": 128100, "speaker": "mic", "text": "そうですね、次のスプリントで対応します", "confidence": 0.87}
        """
        let segment = try SessionJSONCoding.makeDecoder().decode(TranscriptSegment.self, from: Data(transcriptSample.utf8))
        #expect(segment.id == "seg_00042")
        #expect(segment.startMs == 125_300)
        #expect(segment.endMs == 128_100)
        #expect(segment.speaker == .mic)
        #expect(segment.confidence == 0.87)

        let refined = RefinedSegment(
            id: segment.id,
            startMs: segment.startMs,
            endMs: segment.endMs,
            speaker: segment.speaker,
            rawText: segment.text,
            refinedText: "次のスプリントで対応します。",
            error: nil,
            refinedAt: Date(timeIntervalSince1970: 1_782_916_335), // 2026-07-01T14:32:15Z
            model: "claude-haiku-4-5-20251001",
            batchId: "batch_00004"
        )
        let encoded = try SessionJSONCoding.makeEncoder().encode(refined)
        // transcript.jsonl/refined.jsonl lines must never contain an embedded newline.
        #expect(!String(data: encoded, encoding: .utf8)!.contains("\n"))
        let decoded = try SessionJSONCoding.makeDecoder().decode(RefinedSegment.self, from: encoded)
        #expect(decoded == refined)
    }

    // MARK: - createDraftSession (section 5.1/8)

    @Test("createDraftSession creates the standard file layout with an empty context/built-in template fallback")
    func createDraftSessionInitializesLayout() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        #expect(meta.state == .draft)
        #expect(meta.basedOnSession == nil)

        let directory = sessionDirectory(root: root, sessionId: meta.id)
        #expect(FileManager.default.fileExists(atPath: directory.appendingPathComponent("meta.json").path))
        #expect(FileManager.default.fileExists(atPath: directory.appendingPathComponent("context.md").path))
        #expect(FileManager.default.fileExists(atPath: directory.appendingPathComponent("summary_template.md").path))
        #expect(FileManager.default.fileExists(atPath: directory.appendingPathComponent("watchers/enabled.yaml").path))
        #expect(FileManager.default.fileExists(atPath: directory.appendingPathComponent("transcript.jsonl").path))
        #expect(FileManager.default.fileExists(atPath: directory.appendingPathComponent("refined.jsonl").path))

        let handle = try await store.openSession(meta.id)
        let context = await handle.readContext()
        #expect(context.isEmpty)
        let template = await handle.readSummaryTemplate()
        #expect(template == SessionStore.builtInDefaultSummaryTemplate)
    }

    @Test("SessionStore.shared's AppConfig.data.defaults wiring pattern copies default context/template content into a new Draft session (docs/design/26-settings-ui.md §4.2)")
    func createDraftSessionUsesAppConfigDrivenDefaults() async throws {
        let root = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: root) }

        // A standalone AppConfig (not AppConfig.shared) pointed at absolute paths under `root`, so
        // this never touches the real ~/.config/kikimi -- same DI convention as AppConfigTests.
        let configDirectory = root.appendingPathComponent("config", isDirectory: true)
        let contextURL = root.appendingPathComponent("custom-context.md")
        let templateURL = root.appendingPathComponent("custom-template.md")
        try "# 事前メモ\n次回定例のアジェンダ".write(to: contextURL, atomically: true, encoding: .utf8)
        try "# {{title}}\nカスタムテンプレート".write(to: templateURL, atomically: true, encoding: .utf8)

        let appConfig = AppConfig(directory: configDirectory, credentialStore: InMemoryCredentialStore())
        appConfig.update { config in
            config.defaults = DefaultsConfig(contextFile: contextURL.path, summaryTemplateFile: templateURL.path)
        }

        // Mirrors `SessionStore.shared`'s own construction line exactly: `FileManager.
        // expandingTildePath(AppConfig...data.defaults.xxx)` feeding `SessionStore.init(...)`.
        let store = SessionStore(
            sessionsRootDirectory: root.appendingPathComponent("sessions", isDirectory: true),
            defaultContextFileURL: FileManager.expandingTildePath(appConfig.data.defaults.contextFile),
            defaultSummaryTemplateFileURL: FileManager.expandingTildePath(appConfig.data.defaults.summaryTemplateFile)
        )

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)
        #expect(await handle.readContext() == "# 事前メモ\n次回定例のアジェンダ")
        #expect(await handle.readSummaryTemplate() == "# {{title}}\nカスタムテンプレート")
    }

    @Test("createDraftSession(basedOn:) copies context.md/summary_template.md from the source session and records basedOnSession")
    func createDraftSessionCopiesFromSource() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let source = try await store.createDraftSession()
        let sourceHandle = try await store.openSession(source.id)
        try await sourceHandle.writeContext("# 参加者\n- 田中さん")
        try await sourceHandle.writeSummaryTemplate("# {{title}}\n## ヒアリング内容")

        let derived = try await store.createDraftSession(basedOn: source.id)
        #expect(derived.basedOnSession == source.id)

        let derivedHandle = try await store.openSession(derived.id)
        #expect(await derivedHandle.readContext() == "# 参加者\n- 田中さん")
        #expect(await derivedHandle.readSummaryTemplate() == "# {{title}}\n## ヒアリング内容")
    }

    @Test("createDraftSession(basedOn:) copies only participant_ids from the source session's participants.json, never removed_participant_ids (docs/design/22-participant-hints.md section 1.3)")
    func createDraftSessionCopiesParticipantIdsOnly() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let source = try await store.createDraftSession()
        let sourceHandle = try await store.openSession(source.id)
        try await sourceHandle.updateParticipants { participants in
            participants.addParticipant("speaker-a")
            participants.addParticipant("speaker-b")
            participants.removeParticipant("speaker-b")
            participants.addParticipant("speaker-c")
        }

        let derived = try await store.createDraftSession(basedOn: source.id)
        let derivedHandle = try await store.openSession(derived.id)
        let copied = await derivedHandle.readParticipants()

        #expect(copied.participantIds == ["speaker-a", "speaker-c"])
        #expect(copied.removedParticipantIds.isEmpty, "removed_participant_ids must never carry across a based_on duplication")
    }

    @Test("createDraftSession(basedOn:) writes no participants.json when the source session has none, without erroring")
    func createDraftSessionWritesNoParticipantsFileWhenSourceHasNone() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let source = try await store.createDraftSession()
        let derived = try await store.createDraftSession(basedOn: source.id)

        let derivedDirectory = sessionDirectory(root: root, sessionId: derived.id)
        #expect(!FileManager.default.fileExists(atPath: derivedDirectory.appendingPathComponent("participants.json").path))

        let derivedHandle = try await store.openSession(derived.id)
        let participants = await derivedHandle.readParticipants()
        #expect(participants.participantIds.isEmpty)
        #expect(participants.removedParticipantIds.isEmpty)
    }

    // MARK: - openSession caching (section 5.1)

    @Test("openSession returns the same SessionHandle instance for repeated calls with the same id")
    func openSessionReturnsCachedInstance() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let first = try await store.openSession(meta.id)
        let second = try await store.openSession(meta.id)
        #expect(first === second)
    }

    @Test("openSession throws .sessionNotFound for a session id with no folder on disk")
    func openSessionThrowsForMissingSession() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        await #expect(throws: SessionStoreError.sessionNotFound("does-not-exist")) {
            _ = try await store.openSession("does-not-exist")
        }
    }

    @Test("openSession on an existing session with prior transcript.jsonl content never truncates it (design doc section 7)")
    func openSessionPreservesExistingTranscriptContent() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let firstHandle = try await store.openSession(meta.id)
        let existing = try await firstHandle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "existing", confidence: 0.9)

        // Simulate a relaunch: drop the cached handle and re-open the same session from disk, exactly
        // as `SessionStore.shared` would after the app restarts.
        let freshStore = SessionStore(sessionsRootDirectory: root.appendingPathComponent("sessions", isDirectory: true))
        let reopenedHandle = try await freshStore.openSession(meta.id)

        #expect(try await reopenedHandle.readTranscriptSegments() == [existing])
    }

    // MARK: - listSessions / deleteSession (section 5.1, failure modes #8/#9/#10)

    @Test("listSessions skips a session with a corrupt meta.json but still returns the others")
    func listSessionsSkipsCorruptMeta() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let good = try await store.createDraftSession()
        _ = try await store.createDraftSession() // a second valid session, deliberately left un-corrupted

        let corruptDirectory = root.appendingPathComponent("sessions", isDirectory: true)
            .appendingPathComponent("corrupt-session", isDirectory: true)
        try FileManager.default.createDirectory(at: corruptDirectory, withIntermediateDirectories: true)
        try Data("{ not valid json".utf8).write(to: corruptDirectory.appendingPathComponent("meta.json"))

        let sessions = await store.listSessions()
        #expect(sessions.count == 2)
        #expect(sessions.contains { $0.id == good.id })
        #expect(!sessions.contains { $0.id == "corrupt-session" })
    }

    @Test("deleteSession removes a Draft session's folder")
    func deleteSessionRemovesFolder() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let directory = sessionDirectory(root: root, sessionId: meta.id)
        #expect(FileManager.default.fileExists(atPath: directory.path))

        try await store.deleteSession(meta.id)
        #expect(!FileManager.default.fileExists(atPath: directory.path))
    }

    @Test("deleteSession throws .cannotDeleteActiveRecording for the currently recording session")
    func deleteSessionRefusesActiveRecording() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        _ = try await store.beginRecording(meta.id)

        await #expect(throws: SessionStoreError.cannotDeleteActiveRecording(meta.id)) {
            try await store.deleteSession(meta.id)
        }
    }

    // MARK: - Session id validation (path traversal defense)

    @Test("openSession/deleteSession/createDraftSession(basedOn:) reject session ids that would escape sessionsRootDirectory")
    func rejectsPathTraversalSessionIds() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        for maliciousId in ["../../etc/passwd", "a/b", "..", "."] {
            await #expect(throws: SessionStoreError.invalidSessionId(maliciousId)) {
                _ = try await store.openSession(maliciousId)
            }
            await #expect(throws: SessionStoreError.invalidSessionId(maliciousId)) {
                try await store.deleteSession(maliciousId)
            }
            await #expect(throws: SessionStoreError.invalidSessionId(maliciousId)) {
                _ = try await store.createDraftSession(basedOn: maliciousId)
            }
        }
    }

    @Test("deleteSession never touches anything outside sessionsRootDirectory even when the traversal check is bypassed")
    func deleteSessionCannotEscapeSessionsRoot() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        // A canary file placed as a sibling of `sessionsRootDirectory`, one level up — exactly where
        // `sessionsRootDirectory.appendingPathComponent("../canary.txt")` would resolve to if the id
        // validation added to guard against this were ever removed or bypassed.
        let canaryURL = root.appendingPathComponent("canary.txt")
        try Data("do not delete me".utf8).write(to: canaryURL)

        await #expect(throws: SessionStoreError.invalidSessionId("../canary.txt")) {
            try await store.deleteSession("../canary.txt")
        }
        #expect(FileManager.default.fileExists(atPath: canaryURL.path))
    }

    // MARK: - Recording exclusivity (section 9)

    @Test("beginRecording enforces single-session exclusivity and endMeeting releases it")
    func recordingExclusivity() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let first = try await store.createDraftSession()
        let second = try await store.createDraftSession()

        _ = try await store.beginRecording(first.id)
        #expect(await store.recordingSessionId == first.id)

        await #expect(throws: SessionStoreError.anotherSessionRecording(activeSessionId: first.id)) {
            _ = try await store.beginRecording(second.id)
        }

        try await store.endMeeting(first.id)
        #expect(await store.recordingSessionId == nil)

        let firstHandle = try await store.openSession(first.id)
        #expect(await firstHandle.meta.state == .ended)
        #expect(await firstHandle.meta.durationMs >= 0)

        // Now that the exclusivity flag is released, the second (still-Draft) session can begin.
        _ = try await store.beginRecording(second.id)
        #expect(await store.recordingSessionId == second.id)
    }

    @Test("beginRecording throws .sessionNotInDraftState when the target session is not Draft")
    func beginRecordingRequiresDraftState() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        _ = try await store.beginRecording(meta.id)
        try await store.endMeeting(meta.id)

        await #expect(throws: SessionStoreError.sessionNotInDraftState(meta.id)) {
            _ = try await store.beginRecording(meta.id)
        }
    }

    // MARK: - Recording segment lifecycle: begin -> pause -> resume -> pause -> end -> reopen
    // (kikimi.md 4 章 "「停止」と「終了」を分離する", 5/6 章 recordings[]/duration_ms/start_ms_offset)

    @Test("begin -> pause -> resume -> pause -> end builds recordings[] with correct index/startMsOffset, and durationMs accumulates only closed segments")
    func fullPauseResumeCycleBuildsCorrectRecordings() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let created = try await store.createDraftSession()

        // Segment 0: Draft -> Recording.
        _ = try await store.beginRecording(created.id)
        var meta = try await store.openSession(created.id).meta
        #expect(meta.state == .recording)
        #expect(meta.recordings.count == 1)
        #expect(meta.recordings[0].index == 0)
        #expect(meta.recordings[0].startMsOffset == 0)
        #expect(meta.recordings[0].endedAt == nil)
        #expect(meta.durationMs == 0)

        // Segment 0 closes: Recording -> Paused. Pausing releases the recording-exclusivity flag
        // (kikimi.md 4 章: "他ウィンドウのため音声リソースが解放される").
        try await store.pauseRecording(created.id)
        #expect(await store.recordingSessionId == nil)
        meta = try await store.openSession(created.id).meta
        #expect(meta.state == .paused)
        #expect(meta.recordings.count == 1)
        #expect(meta.recordings[0].endedAt != nil)
        let firstSegmentDurationMs = meta.durationMs
        #expect(firstSegmentDurationMs >= 0)

        // Segment 1 opens: Paused -> Recording, offset by the first segment's length.
        _ = try await store.resumeRecording(created.id)
        #expect(await store.recordingSessionId == created.id)
        meta = try await store.openSession(created.id).meta
        #expect(meta.state == .recording)
        #expect(meta.recordings.count == 2)
        #expect(meta.recordings[1].index == 1)
        #expect(meta.recordings[1].startMsOffset == firstSegmentDurationMs)
        #expect(meta.recordings[1].endedAt == nil)
        // durationMs still reflects only the first (closed) segment while the second is open.
        #expect(meta.durationMs == firstSegmentDurationMs)

        // Segment 1 closes: Recording -> Paused again.
        try await store.pauseRecording(created.id)
        meta = try await store.openSession(created.id).meta
        #expect(meta.state == .paused)
        #expect(meta.recordings.count == 2)
        #expect(meta.recordings[1].endedAt != nil)
        #expect(meta.durationMs >= firstSegmentDurationMs)

        // Paused -> Ended: the sole confirmation operation. No new segment opens; endedAt is set.
        try await store.endMeeting(created.id)
        meta = try await store.openSession(created.id).meta
        #expect(meta.state == .ended)
        #expect(meta.recordings.count == 2)
        #expect(meta.endedAt != nil)
        let durationMsAtEnd = meta.durationMs

        // Ended -> Recording (救済パス): opens a third segment and clears endedAt.
        _ = try await store.reopenForRecording(created.id)
        #expect(await store.recordingSessionId == created.id)
        meta = try await store.openSession(created.id).meta
        #expect(meta.state == .recording)
        #expect(meta.endedAt == nil)
        #expect(meta.recordings.count == 3)
        #expect(meta.recordings[2].index == 2)
        #expect(meta.recordings[2].startMsOffset == durationMsAtEnd)
    }

    @Test("pauseRecording throws .sessionNotInRecordingState when not currently Recording")
    func pauseRecordingRequiresRecordingState() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        await #expect(throws: SessionStoreError.sessionNotInRecordingState(meta.id)) {
            try await store.pauseRecording(meta.id)
        }
    }

    @Test("resumeRecording throws .sessionNotInPausedState when not currently Paused")
    func resumeRecordingRequiresPausedState() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        await #expect(throws: SessionStoreError.sessionNotInPausedState(meta.id)) {
            _ = try await store.resumeRecording(meta.id)
        }
    }

    @Test("resumeRecording enforces single-session exclusivity like beginRecording")
    func resumeRecordingEnforcesExclusivity() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let paused = try await store.createDraftSession()
        _ = try await store.beginRecording(paused.id)
        try await store.pauseRecording(paused.id)

        let other = try await store.createDraftSession()
        _ = try await store.beginRecording(other.id)

        await #expect(throws: SessionStoreError.anotherSessionRecording(activeSessionId: other.id)) {
            _ = try await store.resumeRecording(paused.id)
        }
    }

    @Test("endMeeting throws .sessionNotRecordingOrPaused when the session is Draft or already Ended")
    func endMeetingRequiresRecordingOrPausedState() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let draft = try await store.createDraftSession()
        await #expect(throws: SessionStoreError.sessionNotRecordingOrPaused(draft.id)) {
            try await store.endMeeting(draft.id)
        }

        _ = try await store.beginRecording(draft.id)
        try await store.endMeeting(draft.id)
        await #expect(throws: SessionStoreError.sessionNotRecordingOrPaused(draft.id)) {
            try await store.endMeeting(draft.id)
        }
    }

    @Test("reopenForRecording throws .sessionNotInEndedState when not currently Ended")
    func reopenForRecordingRequiresEndedState() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        await #expect(throws: SessionStoreError.sessionNotInEndedState(meta.id)) {
            _ = try await store.reopenForRecording(meta.id)
        }
    }

    @Test("cancelRecordingStart(revertingTo: .paused) discards the just-opened segment and restores .paused without touching durationMs")
    func cancelRecordingStartRevertsToPaused() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let created = try await store.createDraftSession()
        _ = try await store.beginRecording(created.id)
        try await store.pauseRecording(created.id)
        let pausedMeta = try await store.openSession(created.id).meta

        _ = try await store.resumeRecording(created.id)
        try await store.cancelRecordingStart(created.id, revertingTo: .paused)

        let revertedMeta = try await store.openSession(created.id).meta
        #expect(revertedMeta.state == .paused)
        #expect(revertedMeta.recordings.count == 1, "the second (failed) segment must be discarded")
        #expect(revertedMeta.durationMs == pausedMeta.durationMs)
        #expect(await store.recordingSessionId == nil)
    }

    @Test("cancelRecordingStart(revertingTo: .ended) discards the just-opened segment and restores the prior endedAt")
    func cancelRecordingStartRevertsToEnded() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let created = try await store.createDraftSession()
        _ = try await store.beginRecording(created.id)
        try await store.endMeeting(created.id)
        let endedMeta = try await store.openSession(created.id).meta

        _ = try await store.reopenForRecording(created.id)
        try await store.cancelRecordingStart(created.id, revertingTo: .ended)

        let revertedMeta = try await store.openSession(created.id).meta
        #expect(revertedMeta.state == .ended)
        #expect(revertedMeta.recordings.count == 1, "the second (failed) segment must be discarded")
        #expect(revertedMeta.endedAt == endedMeta.endedAt)
    }

    // MARK: - meta.json read-modify-write / flush throttling (section 7)

    @Test("updateMeta is idempotent: applying the same mutation twice yields the same persisted meta.json")
    func updateMetaIsIdempotent() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)

        try await handle.updateMeta { $0.title = "Standup" }
        let firstResult = await handle.meta
        try await handle.updateMeta { $0.title = "Standup" }
        let secondResult = await handle.meta
        #expect(firstResult == secondResult)

        // Compare against a JSON-round-tripped `secondResult` rather than the raw in-memory value:
        // `SessionJSONCoding`'s `.iso8601` date strategy (no fractional seconds, matching kikimi.md 5 章's
        // sample `"created_at": "2026-07-01T14:28:12Z"`) necessarily drops `createdAt`'s sub-second
        // precision once it round-trips through disk, so comparing the on-disk value directly against the
        // full-precision in-memory `Date()` would fail even though persistence is behaving correctly.
        let directory = sessionDirectory(root: root, sessionId: meta.id)
        let onDisk = try SessionJSONCoding.makeDecoder().decode(SessionMeta.self, from: Data(contentsOf: directory.appendingPathComponent("meta.json")))
        let secondResultRoundTripped = try SessionJSONCoding.makeDecoder().decode(
            SessionMeta.self,
            from: SessionJSONCoding.makeEncoder().encode(secondResult)
        )
        #expect(onDisk == secondResultRoundTripped)
    }

    @Test("appendTranscriptSegment assigns monotonically increasing seg_ ids in call order")
    func appendTranscriptSegmentAssignsSequentialIds() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)

        let first = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 100, text: "one", confidence: 0.9)
        let second = try await handle.appendTranscriptSegment(source: .system, startMs: 100, endMs: 200, text: "two", confidence: 0.8)
        let third = try await handle.appendTranscriptSegment(source: .mic, startMs: 200, endMs: 300, text: "three", confidence: 0.7)

        #expect(first.id == "seg_00001")
        #expect(second.id == "seg_00002")
        #expect(third.id == "seg_00003")
    }

    @Test("segmentCount/refinedCount reflect the actual transcript.jsonl/refined.jsonl line counts once flushed")
    func countersMatchLineCountsAfterFlush() async throws {
        // A very long flush interval forces every append to go through the in-memory throttling
        // path, so this test actually exercises `flush()` rather than the interval elapsing on its own.
        let (store, root) = makeStore(metaFlushInterval: 3_600)
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)

        for index in 0..<5 {
            try await handle.appendTranscriptSegment(source: .mic, startMs: index * 100, endMs: index * 100 + 50, text: "segment \(index)", confidence: 0.5)
        }
        for index in 0..<3 {
            try await handle.appendRefinedSegment(
                RefinedSegment(
                    id: "seg_0000\(index + 1)",
                    startMs: index * 100,
                    endMs: index * 100 + 50,
                    speaker: .mic,
                    rawText: "segment \(index)",
                    refinedText: "refined \(index)",
                    error: nil,
                    refinedAt: Date(),
                    model: "claude-haiku-4-5-20251001",
                    batchId: "batch_00001"
                )
            )
        }
        try await handle.flush()

        let directory = sessionDirectory(root: root, sessionId: meta.id)
        let onDisk = try SessionJSONCoding.makeDecoder().decode(SessionMeta.self, from: Data(contentsOf: directory.appendingPathComponent("meta.json")))
        #expect(onDisk.segmentCount == 5)
        #expect(onDisk.refinedCount == 3)

        let transcriptLineCount = try lineCount(at: directory.appendingPathComponent("transcript.jsonl"))
        let refinedLineCount = try lineCount(at: directory.appendingPathComponent("refined.jsonl"))
        #expect(transcriptLineCount == 5)
        #expect(refinedLineCount == 3)
    }

    @Test("flush() is a no-op (does not throw) when there are no pending counter changes")
    func flushIsIdempotentWithNothingPending() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)

        try await handle.flush()
        try await handle.flush()
    }

    // MARK: - Crash-tolerant JSONL reads (section 7/12, failure modes #6/#7)

    @Test("readTranscriptSegments skips a malformed trailing line but keeps the valid ones")
    func readTranscriptSegmentsToleratesCorruptTrailingLine() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)
        try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 100, text: "ok", confidence: 0.9)

        let transcriptURL = sessionDirectory(root: root, sessionId: meta.id).appendingPathComponent("transcript.jsonl")
        let corruptingHandle = try FileHandle(forWritingTo: transcriptURL)
        _ = try corruptingHandle.seekToEnd()
        try corruptingHandle.write(contentsOf: Data("{not valid json".utf8))
        try corruptingHandle.close()

        let segments = try await handle.readTranscriptSegments()
        #expect(segments.count == 1)
        #expect(segments[0].text == "ok")
    }

    // MARK: - Crash recovery (section 10)

    @Test("detectIncompleteSessions returns only sessions left in the .recording state")
    func detectIncompleteSessionsFindsOnlyRecordingSessions() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let recording = try await store.createDraftSession()
        _ = try await store.createDraftSession() // stays Draft

        // Simulate a crash: `meta.json` left with state == .recording on disk, but nobody currently
        // holds `recordingSessionId` (a fresh `SessionStore` instance, as if just relaunched).
        let handle = try await store.openSession(recording.id)
        try await handle.updateMeta { meta in
            meta.state = .recording
            meta.startedAt = Date()
        }

        let freshStore = SessionStore(sessionsRootDirectory: root.appendingPathComponent("sessions", isDirectory: true))
        let incomplete = await freshStore.detectIncompleteSessions()
        #expect(incomplete.map(\.id) == [recording.id])
    }

    @Test("finalizeCrashedSession estimates durationMs from the last transcript segment and sets state to .paused")
    func finalizeCrashedSessionEstimatesFromTranscript() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)
        let startedAt = Date()
        try await handle.updateMeta { meta in
            meta.state = .recording
            meta.startedAt = startedAt
            meta.recordings = [RecordingSegment(index: 0, startedAt: startedAt, endedAt: nil, startMsOffset: 0)]
        }
        try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 1_000, text: "one", confidence: 0.9)
        try await handle.appendTranscriptSegment(source: .mic, startMs: 1_000, endMs: 4_200, text: "two", confidence: 0.9)

        let finalized = try await store.finalizeCrashedSession(meta.id)
        // Crash recovery lands on .paused, not .ended (kikimi.md 15 章): the session stays resumable.
        #expect(finalized.state == .paused)
        #expect(finalized.durationMs == 4_200)
        #expect(finalized.recordings.last?.endedAt == startedAt.addingTimeInterval(4.2))
        #expect(finalized.endedAt == nil)
    }

    @Test("finalizeCrashedSession falls back to durationMs == 0 when transcript.jsonl has no segments")
    func finalizeCrashedSessionHandlesEmptyTranscript() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)
        let startedAt = Date()
        try await handle.updateMeta { meta in
            meta.state = .recording
            meta.startedAt = startedAt
            meta.recordings = [RecordingSegment(index: 0, startedAt: startedAt, endedAt: nil, startMsOffset: 0)]
        }

        let finalized = try await store.finalizeCrashedSession(meta.id)
        #expect(finalized.state == .paused)
        #expect(finalized.durationMs == 0)
        #expect(finalized.recordings.last?.endedAt == startedAt)
        #expect(finalized.endedAt == nil)
    }

    // MARK: - Generic primitives / GenericAccessibleFile path resolution (section 5.2.1/11)

    @Test("writeJSON(_:to:.summaryState) / readJSON(.summaryState) round-trip through summary.state.json")
    func genericJSONPrimitivesRoundTripSummaryState() async throws {
        struct DummySummaryState: Codable, Equatable {
            var overview: String
        }

        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)

        let missing = try await handle.readJSON(.summaryState, as: DummySummaryState.self)
        #expect(missing == nil)

        let value = DummySummaryState(overview: "顧客A向け提案書作成の支援")
        try await handle.writeJSON(value, to: .summaryState)

        let onDiskPath = sessionDirectory(root: root, sessionId: meta.id).appendingPathComponent("summary.state.json")
        #expect(FileManager.default.fileExists(atPath: onDiskPath.path))

        let readBack = try await handle.readJSON(.summaryState, as: DummySummaryState.self)
        #expect(readBack == value)
    }

    @Test("writeText(_:to:.watcherState(id:))/.watcherDefinition(id:) resolve to watchers/<id>.state.json / watchers/<id>.md")
    func genericPrimitivesResolveWatcherPaths() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)

        try await handle.writeText("# System\n...", to: .watcherDefinition(id: "pre-check"))
        try await handle.writeText("{\"items\": []}", to: .watcherState(id: "pre-check"))

        let directory = sessionDirectory(root: root, sessionId: meta.id)
        #expect(FileManager.default.fileExists(atPath: directory.appendingPathComponent("watchers/pre-check.md").path))
        #expect(FileManager.default.fileExists(atPath: directory.appendingPathComponent("watchers/pre-check.state.json").path))

        let definition = try await handle.readText(.watcherDefinition(id: "pre-check"))
        #expect(definition == "# System\n...")
    }

    @Test("listSessionLocalWatcherIds lists watchers/<id>.md basenames, excluding enabled.yaml")
    func listSessionLocalWatcherIdsExcludesEnabledYAML() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)

        try await handle.writeText("# System", to: .watcherDefinition(id: "risk-check"))
        try await handle.writeText("# System", to: .watcherDefinition(id: "action-items"))

        let ids = try await handle.listSessionLocalWatcherIds()
        #expect(ids == ["action-items", "risk-check"])
    }

    // MARK: - watchers/enabled.yaml (YAML, section 11)

    @Test("readEnabledWatchers/writeEnabledWatchers round-trip through watchers/enabled.yaml")
    func enabledWatchersRoundTripsThroughYAML() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)

        // createDraftSession() with no readable default_watchers.yaml starts with an empty list.
        #expect(try await handle.readEnabledWatchers() == [])

        try await handle.writeEnabledWatchers(["pre-check", "action-items"])
        #expect(try await handle.readEnabledWatchers() == ["pre-check", "action-items"])

        let yamlPath = sessionDirectory(root: root, sessionId: meta.id).appendingPathComponent("watchers/enabled.yaml")
        let yamlContent = try String(contentsOf: yamlPath, encoding: .utf8)
        #expect(yamlContent.contains("pre-check"))
    }

    @Test("createDraftSession seeds watchers/enabled.yaml from the default enabled-watchers file when present")
    func createDraftSessionSeedsEnabledWatchersFromDefault() async throws {
        let root = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: root) }

        let defaultEnabledFile = root.appendingPathComponent("default_watchers.yaml")
        try "enabled:\n  - pre-check\n  - action-items\n".write(to: defaultEnabledFile, atomically: true, encoding: .utf8)

        let store = SessionStore(
            sessionsRootDirectory: root.appendingPathComponent("sessions", isDirectory: true),
            defaultContextFileURL: root.appendingPathComponent("missing-context.md"),
            defaultSummaryTemplateFileURL: root.appendingPathComponent("missing-template.md"),
            defaultEnabledWatchersFileURL: defaultEnabledFile
        )

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)
        #expect(try await handle.readEnabledWatchers() == ["pre-check", "action-items"])
    }

    // MARK: - context.md / summary_template.md size-limit warnings (section 8, failure mode #12)

    @Test("writeContext/writeSummaryTemplate save oversized content anyway instead of rejecting it")
    func writeOversizedContextAndTemplateStillSaves() async throws {
        let (store, root) = makeStore()
        defer { try? FileManager.default.removeItem(at: root) }

        let meta = try await store.createDraftSession()
        let handle = try await store.openSession(meta.id)

        let oversizedContext = String(repeating: "a", count: 32 * 1024 + 1)
        try await handle.writeContext(oversizedContext)
        #expect(await handle.readContext() == oversizedContext)

        let oversizedTemplate = String(repeating: "b", count: 16 * 1024 + 1)
        try await handle.writeSummaryTemplate(oversizedTemplate)
        #expect(await handle.readSummaryTemplate() == oversizedTemplate)
    }

    // MARK: - Helpers

    private func lineCount(at url: URL) throws -> Int {
        try String(contentsOf: url, encoding: .utf8)
            .split(separator: "\n", omittingEmptySubsequences: true)
            .count
    }
}
