import Foundation
import Testing

@testable import Kikimi

/// Layer 1 coverage for `SessionHandle+Chat.swift` (`docs/design/38-session-chat.md` §7): the
/// `chat.jsonl` append/read round trip and its corrupt-line tolerance.
@Suite("SessionHandle+Chat")
struct SessionHandleChatTests {
    private func makeTemporaryDirectory(prefix: String) -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(prefix)-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func makeSessionHandle(directory: URL) -> SessionHandle {
        let meta = SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: "定例MTG",
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .ended,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_100),
            endedAt: nil,
            durationMs: 0,
            recordings: [],
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
        return SessionHandle(directoryURL: directory, meta: meta)
    }

    @Test("chat.jsonl resolves to its documented filename")
    func chatFileNameIsStable() throws {
        #expect(try SessionFile.chatJSONL.relativePath() == "chat.jsonl")
    }

    @Test("readChatTurns returns an empty list when the file does not exist yet")
    func missingFileReadsAsEmpty() async throws {
        let directory = makeTemporaryDirectory(prefix: "SessionHandleChatTests-empty")
        defer { try? FileManager.default.removeItem(at: directory) }

        #expect(try await makeSessionHandle(directory: directory).readChatTurns().isEmpty)
    }

    @Test("turns round-trip in append order with every field intact")
    func turnsRoundTrip() async throws {
        let directory = makeTemporaryDirectory(prefix: "SessionHandleChatTests-roundtrip")
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeSessionHandle(directory: directory)

        let question = ChatTurn(
            id: "u1",
            role: .user,
            text: "決まったことは？",
            createdAt: Date(timeIntervalSince1970: 1_751_000_200)
        )
        let answer = ChatTurn(
            id: "a1",
            role: .assistant,
            text: "## 決定事項\n- リリースは来週火曜",
            createdAt: Date(timeIntervalSince1970: 1_751_000_210),
            parentTurnId: "u1",
            replacesTurnId: "a0",
            usage: LLMUsageRecord(
                timestamp: Date(timeIntervalSince1970: 1_751_000_210),
                purpose: "chat",
                model: "claude-haiku-4-5-20251001",
                inputTokens: 1_200,
                outputTokens: 300,
                cacheReadInputTokens: 40,
                cacheCreationInputTokens: 10,
                reportedCostUSD: 0.0031
            ),
            contextScope: .summaryAndRecent
        )

        try await handle.appendChatTurn(question)
        try await handle.appendChatTurn(answer)

        let read = try await handle.readChatTurns()

        #expect(read == [question, answer])
        // `reportedCostUSD` is the field that silently decoded to `nil` before `LLMUsageRecord`
        // spelled out its `CodingKeys` -- the exact reason `ChatTurn` persists `LLMUsageRecord`
        // rather than `LLMUsage` (CH8).
        #expect(read.last?.usage?.reportedCostUSD == 0.0031)
        #expect(read.last?.contextScope == .summaryAndRecent)
        #expect(read.last?.replacesTurnId == "a0")
    }

    @Test("a failed turn round-trips with its error and no usage")
    func failedTurnRoundTrips() async throws {
        let directory = makeTemporaryDirectory(prefix: "SessionHandleChatTests-failure")
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeSessionHandle(directory: directory)

        let failure = ChatTurn(
            id: "a1",
            role: .assistant,
            text: "",
            createdAt: Date(timeIntervalSince1970: 1_751_000_210),
            parentTurnId: "u1",
            error: "claude CLI call timed out after 180 seconds"
        )
        try await handle.appendChatTurn(failure)

        let read = try await handle.readChatTurns()
        #expect(read == [failure])
        #expect(read.first?.usage == nil)
    }

    @Test("deleteChatTurns removes the file, and a later append starts a fresh one")
    func deleteRemovesTheLog() async throws {
        let directory = makeTemporaryDirectory(prefix: "SessionHandleChatTests-delete")
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeSessionHandle(directory: directory)
        let created = Date(timeIntervalSince1970: 1_751_000_200)

        try await handle.appendChatTurn(ChatTurn(id: "u1", role: .user, text: "q1", createdAt: created))
        try await handle.deleteChatTurns()

        #expect(!FileManager.default.fileExists(atPath: directory.appendingPathComponent("chat.jsonl").path))
        #expect(try await handle.readChatTurns().isEmpty)

        // Clearing must not leave the session unable to chat again.
        try await handle.appendChatTurn(ChatTurn(id: "u2", role: .user, text: "q2", createdAt: created))
        #expect(try await handle.readChatTurns().map(\.id) == ["u2"])
    }

    @Test("deleting an already-absent log is a no-op, not an error")
    func deletingMissingLogIsANoOp() async throws {
        let directory = makeTemporaryDirectory(prefix: "SessionHandleChatTests-delete-missing")
        defer { try? FileManager.default.removeItem(at: directory) }

        try await makeSessionHandle(directory: directory).deleteChatTurns()
    }

    @Test("a corrupt line is skipped without losing the surrounding turns")
    func corruptLineIsSkipped() async throws {
        let directory = makeTemporaryDirectory(prefix: "SessionHandleChatTests-corrupt")
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeSessionHandle(directory: directory)

        try await handle.appendChatTurn(
            ChatTurn(id: "u1", role: .user, text: "q1", createdAt: Date(timeIntervalSince1970: 1_751_000_200))
        )

        // Simulates a torn write in the middle of the file.
        let fileURL = directory.appendingPathComponent("chat.jsonl")
        let existing = try String(contentsOf: fileURL, encoding: .utf8)
        try (existing + "{\"id\": \"broken\"\n").write(to: fileURL, atomically: true, encoding: .utf8)

        try await handle.appendChatTurn(
            ChatTurn(id: "u2", role: .user, text: "q2", createdAt: Date(timeIntervalSince1970: 1_751_000_300))
        )

        let read = try await handle.readChatTurns()
        #expect(read.map(\.id) == ["u1", "u2"], "one bad line must not cost the user the rest of the history")
    }
}
