import Foundation
import Testing

@testable import Kikimi

/// Unit tests for `SessionHandle`'s core surface (`docs/design/07-session-store.md` section 5.2:
/// identity, `meta.json` read-modify-write/flush, and the atomic read/write primitives shared with
/// `SessionHandle+*` extension files). See section 13's layer-1 bullets this file targets:
/// `meta.json` read-modify-write idempotency, the `metaFlushInterval` throttle/exception, and
/// `flush()`'s idempotency.
@Suite("SessionHandle")
struct SessionHandleTests {
    /// A controllable, thread-safe stand-in for `Date()` so tests can assert `metaFlushInterval`
    /// throttling behavior deterministically instead of sleeping in real time.
    private final class MutableClock: @unchecked Sendable {
        private let lock = NSLock()
        private var current: Date

        init(_ initial: Date) {
            self.current = initial
        }

        func now() -> Date {
            lock.lock()
            defer { lock.unlock() }
            return current
        }

        func advance(by seconds: TimeInterval) {
            lock.lock()
            defer { lock.unlock() }
            current = current.addingTimeInterval(seconds)
        }
    }

    private func makeTempSessionDirectory() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("SessionHandleTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func baseMeta(id: String = "2026-07-01T14-30-00_a1b2c3d4") -> SessionMeta {
        SessionMeta(
            id: id,
            title: "Test Session",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .draft,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: nil,
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func onDiskMeta(in directoryURL: URL) throws -> SessionMeta? {
        let url = directoryURL.appendingPathComponent("meta.json")
        guard FileManager.default.fileExists(atPath: url.path) else { return nil }
        let data = try Data(contentsOf: url)
        return try SessionJSONCoding.makeDecoder().decode(SessionMeta.self, from: data)
    }

    // MARK: - Identity / init

    @Test("sessionId is derived from the injected meta's id, not the directory name")
    func sessionIdDerivedFromMeta() async {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(id: "custom-id"))

        #expect(await handle.sessionId == "custom-id")
        #expect(await handle.directoryURL == directory)
    }

    @Test("init does not read meta.json from disk; the injected meta is used as-is")
    func initDoesNotReadMetaFromDisk() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        // Write a *different* meta.json directly to disk before constructing the handle.
        let onDisk = baseMeta(id: "on-disk-id")
        let data = try SessionJSONCoding.makeEncoder().encode(onDisk)
        try data.write(to: directory.appendingPathComponent("meta.json"), options: [.atomic])

        let injected = baseMeta(id: "injected-id")
        let handle = SessionHandle(directoryURL: directory, meta: injected)

        #expect(await handle.meta == injected)
        #expect(await handle.sessionId == "injected-id")
    }

    // MARK: - updateMeta: immediate-write path

    @Test("updateMeta writes meta.json immediately when a non-counter field changes")
    func updateMetaWritesImmediatelyForNonCounterField() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)

        try await handle.updateMeta { meta in
            meta.title = "New Title"
        }

        let persisted = try #require(try onDiskMeta(in: directory))
        #expect(persisted.title == "New Title")
    }

    @Test("updateMeta flushes immediately for a state change even with a huge flush interval")
    func updateMetaFlushesImmediatelyForStateChange() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)

        try await handle.updateMeta { meta in meta.state = .recording }

        let persisted = try #require(try onDiskMeta(in: directory))
        #expect(persisted.state == .recording)
    }

    @Test("updateMeta flushes immediately for a startedAt change even with a huge flush interval")
    func updateMetaFlushesImmediatelyForStartedAtChange() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)
        let startedAt = Date(timeIntervalSince1970: 1_751_000_100)

        try await handle.updateMeta { meta in meta.startedAt = startedAt }

        let persisted = try #require(try onDiskMeta(in: directory))
        #expect(persisted.startedAt == startedAt)
    }

    @Test("updateMeta flushes immediately for an endedAt change even with a huge flush interval")
    func updateMetaFlushesImmediatelyForEndedAtChange() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)
        let endedAt = Date(timeIntervalSince1970: 1_751_000_200)

        try await handle.updateMeta { meta in meta.endedAt = endedAt }

        let persisted = try #require(try onDiskMeta(in: directory))
        #expect(persisted.endedAt == endedAt)
    }

    @Test("updateMeta flushes immediately for a durationMs change even with a huge flush interval")
    func updateMetaFlushesImmediatelyForDurationMsChange() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)

        try await handle.updateMeta { meta in meta.durationMs = 1_000 }

        let persisted = try #require(try onDiskMeta(in: directory))
        #expect(persisted.durationMs == 1_000)
    }

    @Test("updateMeta writes immediately when segmentCount changes alongside another field")
    func updateMetaWritesImmediatelyForMixedChange() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)

        try await handle.updateMeta { meta in
            meta.segmentCount += 1
            meta.title = "Mixed Change"
        }

        let persisted = try #require(try onDiskMeta(in: directory))
        #expect(persisted.segmentCount == 1)
        #expect(persisted.title == "Mixed Change")
    }

    @Test("updateMeta writes immediately even when the mutation is a no-op")
    func updateMetaWritesImmediatelyForNoOp() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)

        try await handle.updateMeta { _ in }

        #expect(try onDiskMeta(in: directory) != nil)
    }

    @Test("updateMeta is idempotent: applying the same resulting content twice leaves meta.json unchanged")
    func updateMetaIsIdempotentForRepeatedIdenticalContent() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)

        try await handle.updateMeta { meta in meta.title = "Idempotent Title" }
        let firstWrite = try #require(try onDiskMeta(in: directory))

        try await handle.updateMeta { meta in meta.title = "Idempotent Title" }
        let secondWrite = try #require(try onDiskMeta(in: directory))

        #expect(firstWrite == secondWrite)
        #expect(await handle.meta.title == "Idempotent Title")
    }

    // MARK: - updateMeta: throttled path (segmentCount/refinedCount only)

    @Test("updateMeta defers the disk write when only segmentCount/refinedCount change, before the flush interval elapses")
    func updateMetaDefersCounterOnlyChanges() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let clock = MutableClock(Date(timeIntervalSince1970: 1_751_000_000))
        let handle = SessionHandle(
            directoryURL: directory,
            meta: baseMeta(),
            metaFlushInterval: 5.0,
            now: { clock.now() }
        )

        try await handle.updateMeta { meta in meta.segmentCount += 1 }
        try await handle.updateMeta { meta in meta.refinedCount += 1 }

        // In-memory state reflects both increments immediately...
        #expect(await handle.meta.segmentCount == 1)
        #expect(await handle.meta.refinedCount == 1)
        // ...but neither was written to disk yet, since less than metaFlushInterval has elapsed.
        #expect(try onDiskMeta(in: directory) == nil)
    }

    @Test("updateMeta writes the deferred counters once metaFlushInterval has elapsed")
    func updateMetaWritesOnceIntervalElapses() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let clock = MutableClock(Date(timeIntervalSince1970: 1_751_000_000))
        let handle = SessionHandle(
            directoryURL: directory,
            meta: baseMeta(),
            metaFlushInterval: 5.0,
            now: { clock.now() }
        )

        try await handle.updateMeta { meta in meta.segmentCount += 1 }
        #expect(try onDiskMeta(in: directory) == nil)

        clock.advance(by: 5.0)
        try await handle.updateMeta { meta in meta.segmentCount += 1 }

        let persisted = try #require(try onDiskMeta(in: directory))
        #expect(persisted.segmentCount == 2)
    }

    @Test("flush() persists a deferred counter change immediately, ignoring metaFlushInterval")
    func flushPersistsDeferredChangeImmediately() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)

        try await handle.updateMeta { meta in meta.segmentCount += 1 }
        #expect(try onDiskMeta(in: directory) == nil)

        try await handle.flush()

        let persisted = try #require(try onDiskMeta(in: directory))
        #expect(persisted.segmentCount == 1)
    }

    @Test("flush() is a no-op (does not create meta.json) when there is nothing pending")
    func flushIsIdempotentWhenNothingPending() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(), metaFlushInterval: 999)

        try await handle.flush()
        #expect(try onDiskMeta(in: directory) == nil)

        // Also idempotent right after a real write (nothing left pending).
        try await handle.updateMeta { meta in meta.title = "Written" }
        try await handle.flush()
        try await handle.flush()
        let persisted = try #require(try onDiskMeta(in: directory))
        #expect(persisted.title == "Written")
    }

    // MARK: - updateMeta: error propagation

    @Test("updateMeta propagates the mutate closure's error and leaves meta unchanged")
    func updateMetaPropagatesMutateError() async throws {
        struct MutationError: Error, Equatable {}

        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let original = baseMeta()
        let handle = SessionHandle(directoryURL: directory, meta: original)

        await #expect(throws: MutationError.self) {
            try await handle.updateMeta { meta in
                meta.title = "Should not stick"
                throw MutationError()
            }
        }

        #expect(await handle.meta == original)
        #expect(try onDiskMeta(in: directory) == nil)
    }

    // MARK: - Atomic JSON primitives

    private struct JSONFixture: Codable, Equatable {
        var value: Int
        var name: String
    }

    @Test("atomicWriteJSON/readJSONIfPresent round-trip through the cached encoder/decoder")
    func atomicJSONRoundTrips() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let fixture = JSONFixture(value: 42, name: "hello")

        try await handle.atomicWriteJSON(fixture, to: .summaryState)
        let read = try await handle.readJSONIfPresent(.summaryState, as: JSONFixture.self)

        #expect(read == fixture)
    }

    @Test("readJSONIfPresent returns nil when the file does not exist")
    func readJSONIfPresentReturnsNilWhenMissing() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let read = try await handle.readJSONIfPresent(.summaryState, as: JSONFixture.self)
        #expect(read == nil)
    }

    @Test("atomicWriteJSON creates the parent directory for nested files (e.g. watchers/<id>.state.json)")
    func atomicWriteJSONCreatesParentDirectory() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let fixture = JSONFixture(value: 1, name: "pre-check")

        try await handle.atomicWriteJSON(fixture, to: .watcherState(id: "pre-check"))

        let expectedURL = directory.appendingPathComponent("watchers/pre-check.state.json")
        #expect(FileManager.default.fileExists(atPath: expectedURL.path))
        let read = try await handle.readJSONIfPresent(.watcherState(id: "pre-check"), as: JSONFixture.self)
        #expect(read == fixture)
    }

    // MARK: - Atomic text primitives

    @Test("atomicWriteText/readTextIfPresent round-trip")
    func atomicTextRoundTrips() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        try await handle.atomicWriteText("# Context\n- agenda item", to: .context)
        let read = try await handle.readTextIfPresent(.context)

        #expect(read == "# Context\n- agenda item")
    }

    @Test("readTextIfPresent returns nil when the file does not exist")
    func readTextIfPresentReturnsNilWhenMissing() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let read = try await handle.readTextIfPresent(.summaryTemplate)
        #expect(read == nil)
    }

    @Test("readTextIfPresent throws invalidTextEncoding for non-UTF8 bytes")
    func readTextIfPresentThrowsForInvalidEncoding() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        // 0xFF 0xFE is not valid UTF-8.
        let invalidBytes = Data([0xFF, 0xFE, 0x00, 0x01])
        try invalidBytes.write(to: directory.appendingPathComponent("context.md"))

        await #expect(throws: SessionHandleError.invalidTextEncoding(relativePath: "context.md")) {
            try await handle.readTextIfPresent(.context)
        }
    }
}
