import Foundation
import Testing

@testable import Kikimi

/// Unit tests for `SessionHandle+Transcript.swift` (`docs/design/07-session-store.md` section 5.2/6/7;
/// kikimi.md 5 章/6 章). Mirrors `SessionHandleTests.swift`'s pattern of constructing `SessionHandle`
/// directly (`SessionHandle(directoryURL:meta:)`) rather than going through `SessionStore`, since
/// these tests only exercise this extension's own surface
/// (`appendTranscriptSegment`/`appendRefinedSegment`/`readTranscriptSegments`/`readRefinedSegments`).
///
/// See design doc section 13's layer-1 bullets this file targets: sequential `seg_id` assignment,
/// `segmentCount`/`refinedCount` matching the actual line counts, and corrupt-trailing-line vs.
/// corrupt-non-trailing-line read tolerance.
@Suite("SessionHandle+Transcript")
struct SessionHandleTranscriptTests {
    private func makeTempSessionDirectory() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("SessionHandleTranscriptTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func baseMeta(id: String = "2026-07-01T14-30-00_a1b2c3d4", segmentCount: Int = 0, refinedCount: Int = 0) -> SessionMeta {
        SessionMeta(
            id: id,
            title: "Test Session",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_010),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: segmentCount,
            refinedCount: refinedCount,
            appVersion: "0.1.0"
        )
    }

    private func makeRefinedSegment(
        id: String,
        startMs: Int = 0,
        endMs: Int = 1_000,
        refinedText: String? = "refined text",
        error: String? = nil,
        batchId: String = "batch_00001"
    ) -> RefinedSegment {
        RefinedSegment(
            id: id,
            startMs: startMs,
            endMs: endMs,
            speaker: .mic,
            rawText: "raw text",
            refinedText: refinedText,
            error: error,
            refinedAt: Date(timeIntervalSince1970: 1_751_000_020),
            model: "claude-haiku-4-5-20251001",
            batchId: batchId
        )
    }

    // MARK: - appendTranscriptSegment: id assignment

    @Test("appendTranscriptSegment assigns sequential seg_ + 5-digit zero-padded ids in call order")
    func appendTranscriptSegmentAssignsSequentialIds() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let first = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "one", confidence: 0.9)
        let second = try await handle.appendTranscriptSegment(source: .system, startMs: 500, endMs: 1_000, text: "two", confidence: 0.8)
        let third = try await handle.appendTranscriptSegment(source: .mic, startMs: 1_000, endMs: 1_500, text: "three", confidence: 0.95)

        #expect(first.id == "seg_00001")
        #expect(second.id == "seg_00002")
        #expect(third.id == "seg_00003")
    }

    @Test("appendTranscriptSegment continues the sequence from an already-nonzero segmentCount")
    func appendTranscriptSegmentContinuesFromExistingCount() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(segmentCount: 41))

        let segment = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "resumed", confidence: 0.9)

        #expect(segment.id == "seg_00042")
    }

    // MARK: - appendTranscriptSegment: meta.segmentCount / file content

    @Test("appendTranscriptSegment increments meta.segmentCount by exactly one per call")
    func appendTranscriptSegmentIncrementsSegmentCount() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "one", confidence: 0.9)
        try await handle.appendTranscriptSegment(source: .mic, startMs: 500, endMs: 1_000, text: "two", confidence: 0.9)

        #expect(await handle.meta.segmentCount == 2)
    }

    @Test("appendTranscriptSegment writes exactly one JSON line per call to transcript.jsonl")
    func appendTranscriptSegmentWritesOneLinePerCall() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "one", confidence: 0.9)
        try await handle.appendTranscriptSegment(source: .system, startMs: 500, endMs: 1_000, text: "two", confidence: 0.8)

        let fileURL = directory.appendingPathComponent("transcript.jsonl")
        let content = try String(contentsOf: fileURL, encoding: .utf8)
        let lines = content.split(separator: "\n", omittingEmptySubsequences: true)
        #expect(lines.count == 2)
    }

    // MARK: - appendTranscriptSegment: sttSource (docs/design/33-meeting-two-pass-decode.md MT9)

    @Test("appendTranscriptSegment defaults sttSource to nil when the caller omits it")
    func appendTranscriptSegmentDefaultsSttSourceToNil() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let segment = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "one", confidence: 0.9)

        #expect(segment.sttSource == nil)
    }

    @Test("appendTranscriptSegment threads an explicit sttSource through to the returned segment")
    func appendTranscriptSegmentThreadsExplicitSttSource() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let segment = try await handle.appendTranscriptSegment(
            source: .mic,
            startMs: 0,
            endMs: 500,
            text: "one",
            confidence: 0.9,
            sttSource: "batch"
        )

        #expect(segment.sttSource == "batch")
    }

    @Test("appendTranscriptSegment persists sttSource to transcript.jsonl as the stt_source key, round-tripping on read")
    func appendTranscriptSegmentPersistsSttSourceToDisk() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let appended = try await handle.appendTranscriptSegment(
            source: .mic,
            startMs: 0,
            endMs: 500,
            text: "one",
            confidence: 0.9,
            sttSource: "batch"
        )

        let fileURL = directory.appendingPathComponent("transcript.jsonl")
        let content = try String(contentsOf: fileURL, encoding: .utf8)
        let object = try #require(JSONSerialization.jsonObject(with: Data(content.utf8)) as? [String: Any])
        #expect(object["stt_source"] as? String == "batch")

        let read = try await handle.readTranscriptSegments()
        #expect(read == [appended])
        #expect(read.first?.sttSource == "batch")
    }

    @Test("appendTranscriptSegment omits the stt_source key entirely on disk when sttSource is nil (MT9 byte-for-byte compatibility)")
    func appendTranscriptSegmentOmitsSttSourceKeyOnDiskWhenNil() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "one", confidence: 0.9)

        let fileURL = directory.appendingPathComponent("transcript.jsonl")
        let content = try String(contentsOf: fileURL, encoding: .utf8)
        let object = try #require(JSONSerialization.jsonObject(with: Data(content.utf8)) as? [String: Any])
        #expect(object["stt_source"] == nil)
        #expect(object.keys.contains("stt_source") == false)
    }

    @Test("appendTranscriptSegment supports a mix of batch-sourced and fallback (nil sttSource) segments in the same session")
    func appendTranscriptSegmentSupportsMixedSttSourceSegments() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let batchSourced = try await handle.appendTranscriptSegment(
            source: .mic,
            startMs: 0,
            endMs: 500,
            text: "one",
            confidence: 0.9,
            sttSource: "batch"
        )
        let fallback = try await handle.appendTranscriptSegment(source: .mic, startMs: 500, endMs: 1_000, text: "two", confidence: 0.9)

        let read = try await handle.readTranscriptSegments()
        #expect(read == [batchSourced, fallback])
        #expect(read[0].sttSource == "batch")
        #expect(read[1].sttSource == nil)
    }

    // MARK: - appendRefinedSegment

    @Test("appendRefinedSegment increments meta.refinedCount and appends one line to refined.jsonl")
    func appendRefinedSegmentIncrementsRefinedCountAndAppendsLine() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        try await handle.appendRefinedSegment(makeRefinedSegment(id: "seg_00001"))
        try await handle.appendRefinedSegment(makeRefinedSegment(id: "seg_00002"))

        #expect(await handle.meta.refinedCount == 2)

        let fileURL = directory.appendingPathComponent("refined.jsonl")
        let content = try String(contentsOf: fileURL, encoding: .utf8)
        let lines = content.split(separator: "\n", omittingEmptySubsequences: true)
        #expect(lines.count == 2)
    }

    @Test("appendRefinedSegment still counts and appends a refinement failure (refinedText == nil, error set)")
    func appendRefinedSegmentCountsRefinementFailures() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let failed = makeRefinedSegment(id: "seg_00001", refinedText: nil, error: "LLM request timed out")
        try await handle.appendRefinedSegment(failed)

        #expect(await handle.meta.refinedCount == 1)
        let segments = try await handle.readRefinedSegments()
        #expect(segments.count == 1)
        #expect(segments[0].refinedText == nil)
        #expect(segments[0].error == "LLM request timed out")
    }

    // MARK: - readTranscriptSegments / readRefinedSegments: round-trip

    @Test("readTranscriptSegments returns an empty array when transcript.jsonl does not exist")
    func readTranscriptSegmentsReturnsEmptyWhenMissing() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        #expect(try await handle.readTranscriptSegments().isEmpty)
    }

    @Test("readRefinedSegments returns an empty array when refined.jsonl does not exist")
    func readRefinedSegmentsReturnsEmptyWhenMissing() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        #expect(try await handle.readRefinedSegments().isEmpty)
    }

    @Test("readTranscriptSegments round-trips every appended segment in append order")
    func readTranscriptSegmentsRoundTrips() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let appended = [
            try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "one", confidence: 0.9),
            try await handle.appendTranscriptSegment(source: .system, startMs: 500, endMs: 1_000, text: "two", confidence: 0.8),
            try await handle.appendTranscriptSegment(source: .mic, startMs: 1_000, endMs: 1_500, text: "three", confidence: 0.7)
        ]

        let read = try await handle.readTranscriptSegments()
        #expect(read == appended)
    }

    @Test("readRefinedSegments round-trips every appended segment, including the ISO8601 refinedAt date")
    func readRefinedSegmentsRoundTrips() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let appended = [
            makeRefinedSegment(id: "seg_00001", batchId: "batch_00001"),
            makeRefinedSegment(id: "seg_00002", batchId: "batch_00001")
        ]
        for segment in appended {
            try await handle.appendRefinedSegment(segment)
        }

        let read = try await handle.readRefinedSegments()
        #expect(read == appended)
    }

    // MARK: - readTranscriptSegments: corrupt-line tolerance (design doc section 7/12)

    @Test("readTranscriptSegments skips a corrupt trailing line and still returns the valid ones (mid-write crash)")
    func readTranscriptSegmentsSkipsCorruptTrailingLine() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let first = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "one", confidence: 0.9)
        let second = try await handle.appendTranscriptSegment(source: .mic, startMs: 500, endMs: 1_000, text: "two", confidence: 0.9)

        // Simulate a crash mid-write: append a truncated, invalid trailing line directly to disk.
        let fileURL = directory.appendingPathComponent("transcript.jsonl")
        let handleForCorruption = try #require(FileHandle(forWritingAtPath: fileURL.path))
        try handleForCorruption.seekToEnd()
        try handleForCorruption.write(contentsOf: Data("{\"id\": \"seg_00003\", \"start_ms\": tr".utf8))
        try handleForCorruption.close()

        let read = try await handle.readTranscriptSegments()
        #expect(read == [first, second])
    }

    @Test("readTranscriptSegments skips a corrupt non-trailing line but still returns valid lines before and after it")
    func readTranscriptSegmentsSkipsCorruptNonTrailingLine() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let encoder = SessionJSONCoding.makeEncoder()
        let validFirst = TranscriptSegment(id: "seg_00001", startMs: 0, endMs: 500, speaker: .mic, text: "one", confidence: 0.9)
        let validThird = TranscriptSegment(id: "seg_00003", startMs: 1_000, endMs: 1_500, speaker: .mic, text: "three", confidence: 0.9)

        var fileContent = ""
        fileContent += String(data: try encoder.encode(validFirst), encoding: .utf8)! + "\n"
        fileContent += "{this is not valid json at all}\n"
        fileContent += String(data: try encoder.encode(validThird), encoding: .utf8)! + "\n"

        let fileURL = directory.appendingPathComponent("transcript.jsonl")
        try fileContent.write(to: fileURL, atomically: true, encoding: .utf8)

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let read = try await handle.readTranscriptSegments()

        #expect(read == [validFirst, validThird])
    }

    // MARK: - Re-opening: "open once, seek once" append continuity

    @Test("appending against pre-existing transcript.jsonl content (from a previous run) appends after it instead of overwriting it")
    func appendPreservesPreExistingFileContent() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        // Simulate content already on disk from a previous run, written *before* any `SessionHandle`
        // for this directory has ever touched `transcript.jsonl` — so the append-only writer this
        // extension caches per file path (`AppendOnlyLogFileRegistry`) has no entry for this path
        // yet, and its first `appendTranscriptSegment` call below must open the file fresh and seek
        // to its existing end, exactly like a real app relaunch discovering a session's existing log
        // (design doc section 7, "開いたら追記のみ、seekしない" applied once at open time).
        let existing = TranscriptSegment(id: "seg_00001", startMs: 0, endMs: 500, speaker: .mic, text: "existing", confidence: 0.9)
        let encoder = SessionJSONCoding.makeEncoder()
        let existingLine = String(data: try encoder.encode(existing), encoding: .utf8)! + "\n"
        try existingLine.write(to: directory.appendingPathComponent("transcript.jsonl"), atomically: true, encoding: .utf8)

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(segmentCount: 1))
        let appended = try await handle.appendTranscriptSegment(source: .mic, startMs: 500, endMs: 1_000, text: "new", confidence: 0.9)

        let read = try await handle.readTranscriptSegments()
        #expect(read == [existing, appended])
    }

    // MARK: - ensureTranscriptAndRefinedLogFilesExist (design doc section 7: "SessionHandle が
    // セッションを開いた時点で FileHandle を1つ開きっぱなしにし")

    @Test("ensureTranscriptAndRefinedLogFilesExist creates empty transcript.jsonl/refined.jsonl when neither exists yet")
    func ensureTranscriptAndRefinedLogFilesExistCreatesMissingFiles() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let transcriptURL = directory.appendingPathComponent("transcript.jsonl")
        let refinedURL = directory.appendingPathComponent("refined.jsonl")
        #expect(!FileManager.default.fileExists(atPath: transcriptURL.path))
        #expect(!FileManager.default.fileExists(atPath: refinedURL.path))

        try await handle.ensureTranscriptAndRefinedLogFilesExist()

        #expect(FileManager.default.fileExists(atPath: transcriptURL.path))
        #expect(FileManager.default.fileExists(atPath: refinedURL.path))
        #expect(try await handle.readTranscriptSegments().isEmpty)
        #expect(try await handle.readRefinedSegments().isEmpty)
    }

    @Test("ensureTranscriptAndRefinedLogFilesExist does not truncate pre-existing transcript.jsonl/refined.jsonl content")
    func ensureTranscriptAndRefinedLogFilesExistPreservesExistingContent() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let existingTranscript = TranscriptSegment(id: "seg_00001", startMs: 0, endMs: 500, speaker: .mic, text: "existing", confidence: 0.9)
        let encoder = SessionJSONCoding.makeEncoder()
        let existingTranscriptLine = String(data: try encoder.encode(existingTranscript), encoding: .utf8)! + "\n"
        try existingTranscriptLine.write(to: directory.appendingPathComponent("transcript.jsonl"), atomically: true, encoding: .utf8)

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta(segmentCount: 1))
        try await handle.ensureTranscriptAndRefinedLogFilesExist()

        #expect(try await handle.readTranscriptSegments() == [existingTranscript])

        // Appending afterward must continue after the pre-existing content, not overwrite it — the same
        // "open once, seek once" continuity `appendPreservesPreExistingFileContent` verifies without this
        // extra `ensureTranscriptAndRefinedLogFilesExist()` call.
        let appended = try await handle.appendTranscriptSegment(source: .mic, startMs: 500, endMs: 1_000, text: "new", confidence: 0.9)
        #expect(try await handle.readTranscriptSegments() == [existingTranscript, appended])
    }

    @Test("ensureTranscriptAndRefinedLogFilesExist is idempotent across repeated calls")
    func ensureTranscriptAndRefinedLogFilesExistIsIdempotent() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        try await handle.ensureTranscriptAndRefinedLogFilesExist()
        let appended = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "one", confidence: 0.9)
        try await handle.ensureTranscriptAndRefinedLogFilesExist()

        #expect(try await handle.readTranscriptSegments() == [appended])
    }

    // MARK: - closeAppendOnlyLogFiles (SessionStore.deleteSession(_:) FileHandle cleanup)

    @Test("closeAppendOnlyLogFiles evicts the cached FileHandle so a path reused after deletion starts from a fresh file, not the old open handle")
    func closeAppendOnlyLogFilesEvictsCachedHandle() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        // Simulate a session that was opened and written to (as `SessionStore.deleteSession(_:)`
        // would find one keyed in `AppendOnlyLogFileRegistry` by this exact path).
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        _ = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "before delete", confidence: 0.9)

        // `SessionStore.deleteSession(_:)` calls this before removing the directory.
        SessionHandle.closeAppendOnlyLogFiles(inSessionDirectory: directory)
        try FileManager.default.removeItem(at: directory)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        // Without evicting the cache, `AppendOnlyLogFileRegistry` (keyed by this same absolute path)
        // would hand back the stale `FileHandle` left pointing at the now-unlinked inode, so this
        // append would silently vanish instead of landing in the freshly recreated file.
        let freshHandle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let appended = try await freshHandle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 500, text: "after delete", confidence: 0.9)

        #expect(try await freshHandle.readTranscriptSegments() == [appended])
    }

    @Test("closeAppendOnlyLogFiles is a no-op for a directory whose log files were never opened")
    func closeAppendOnlyLogFilesIsNoOpWhenNeverOpened() {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        SessionHandle.closeAppendOnlyLogFiles(inSessionDirectory: directory)
    }
}
