import Foundation
import Testing

@testable import Kikimi

/// Unit tests for `SessionHandle+LLMUsage.swift` (`docs/design/16-llm-usage-stats.md` sections
/// 2/6). Mirrors `SessionHandleTranscriptTests`'s pattern of constructing `SessionHandle` directly
/// rather than going through `SessionStore`.
@Suite("SessionHandle+LLMUsage")
struct SessionHandleLLMUsageTests {
    private func makeTempSessionDirectory() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("SessionHandleLLMUsageTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func baseMeta(id: String = "2026-07-01T14-30-00_a1b2c3d4") -> SessionMeta {
        SessionMeta(
            id: id,
            title: "Test Session",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_010),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func makeRecord(
        purpose: String = "refinement",
        model: String = "claude-haiku-4-5-20251001",
        inputTokens: Int = 850,
        outputTokens: Int = 320,
        cacheReadInputTokens: Int = 2_100,
        cacheCreationInputTokens: Int = 0,
        reportedCostUSD: Double? = 0.0042,
        provider: String? = nil
    ) -> LLMUsageRecord {
        LLMUsageRecord(
            timestamp: Date(timeIntervalSince1970: 1_751_000_100),
            purpose: purpose,
            model: model,
            inputTokens: inputTokens,
            outputTokens: outputTokens,
            cacheReadInputTokens: cacheReadInputTokens,
            cacheCreationInputTokens: cacheCreationInputTokens,
            reportedCostUSD: reportedCostUSD,
            provider: provider
        )
    }

    // MARK: - readLLMUsageRecords with no file yet

    @Test("readLLMUsageRecords returns an empty array when llm_usage.jsonl does not exist yet")
    func readReturnsEmptyWhenFileMissing() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let records = try await handle.readLLMUsageRecords()
        #expect(records.isEmpty)
    }

    // MARK: - append -> read round-trip

    @Test("appendLLMUsageRecord followed by readLLMUsageRecords round-trips a single record")
    func appendThenReadRoundTripsOneRecord() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let record = makeRecord()
        try await handle.appendLLMUsageRecord(record)

        let records = try await handle.readLLMUsageRecords()
        #expect(records == [record])
    }

    @Test("multiple appendLLMUsageRecord calls accumulate in call order")
    func multipleAppendsAccumulateInOrder() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let first = makeRecord(purpose: "refinement")
        let second = makeRecord(purpose: "summary_patch", reportedCostUSD: nil)
        let third = makeRecord(purpose: "final_title", cacheCreationInputTokens: 500)

        try await handle.appendLLMUsageRecord(first)
        try await handle.appendLLMUsageRecord(second)
        try await handle.appendLLMUsageRecord(third)

        let records = try await handle.readLLMUsageRecords()
        #expect(records == [first, second, third])
    }

    @Test("appendLLMUsageRecord round-trips a nil reportedCostUSD")
    func appendRoundTripsNilReportedCost() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let record = makeRecord(reportedCostUSD: nil)
        try await handle.appendLLMUsageRecord(record)

        let records = try await handle.readLLMUsageRecords()
        #expect(records.first?.reportedCostUSD == nil)
    }

    // MARK: - provider field (docs/design/44-llm-model-config.md §7)

    @Test("appendLLMUsageRecord followed by readLLMUsageRecords round-trips a non-nil provider")
    func appendThenReadRoundTripsProvider() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let record = makeRecord(provider: "azure")
        try await handle.appendLLMUsageRecord(record)

        let records = try await handle.readLLMUsageRecords()
        #expect(records == [record])
        #expect(records.first?.provider == "azure")
    }

    @Test("a pre-44-章 line with no provider key decodes with provider == nil, not a decode failure")
    func readDecodesLegacyLineWithoutProviderAsNil() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let legacyLine = """
        {"timestamp":"2026-07-01T14:00:00Z","purpose":"refinement","model":"claude-haiku-4-5-20251001",\
        "input_tokens":850,"output_tokens":320,"cache_read_input_tokens":2100,"cache_creation_input_tokens":0,\
        "reported_cost_usd":0.0042}\n
        """
        let fileURL = directory.appendingPathComponent("llm_usage.jsonl")
        FileManager.default.createFile(atPath: fileURL.path, contents: nil)
        try legacyLine.data(using: .utf8)!.append(to: fileURL)

        let records = try await handle.readLLMUsageRecords()
        let record = try #require(records.first)
        #expect(record.provider == nil)
        #expect(record.purpose == "refinement")
        #expect(record.model == "claude-haiku-4-5-20251001")
    }

    // MARK: - Corrupt-line tolerance (design section 6: same contract as transcript.jsonl)

    @Test("readLLMUsageRecords skips a malformed non-trailing line and still returns the rest")
    func readSkipsCorruptNonTrailingLine() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let first = makeRecord(purpose: "refinement")
        try await handle.appendLLMUsageRecord(first)

        // Inject a corrupt line between two well-formed ones directly on disk.
        let fileURL = directory.appendingPathComponent("llm_usage.jsonl")
        try "not valid json at all\n".data(using: .utf8)!.append(to: fileURL)

        let third = makeRecord(purpose: "final_title")
        try await handle.appendLLMUsageRecord(third)

        let records = try await handle.readLLMUsageRecords()
        #expect(records == [first, third])
    }

    @Test("readLLMUsageRecords tolerates a corrupt trailing line (mid-write crash simulation)")
    func readToleratesCorruptTrailingLine() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())

        let first = makeRecord(purpose: "refinement")
        try await handle.appendLLMUsageRecord(first)

        let fileURL = directory.appendingPathComponent("llm_usage.jsonl")
        try "{\"timestamp\":\"broken\n".data(using: .utf8)!.append(to: fileURL)

        let records = try await handle.readLLMUsageRecords()
        #expect(records == [first])
    }
}

// MARK: - Data.append(to:) helper

private extension Data {
    func append(to fileURL: URL) throws {
        guard let handle = FileHandle(forWritingAtPath: fileURL.path) else {
            throw CocoaError(.fileWriteUnknown)
        }
        defer { try? handle.close() }
        _ = try handle.seekToEnd()
        try handle.write(contentsOf: self)
    }
}
