import Foundation
import Testing

@testable import Kikimi

/// Unit tests for `SessionStore+CrashRecovery.swift` (`docs/design/07-session-store.md` section 10,
/// section 13 "レイヤ1" bullet: "`detectIncompleteSessions()`/`finalizeCrashedSession()` を、一時ディレクトリ
/// 上に `state: recording` の `meta.json` を手動で用意した fixture で検証").
///
/// Fixtures are written directly to disk with `SessionJSONCoding`/`FileManager` (bypassing
/// `SessionHandle`, matching section 13's "手動で用意した fixture" instruction and the same pattern
/// `WavFileWriterTests`/`AudioCaptureIntegrationTests` use of reading/writing bytes independently of
/// the component under test), so these tests exercise `SessionStore` purely through its public API
/// against a session layout that looks exactly like one left behind by a crashed previous run.
///
/// `SessionStore(sessionsRootDirectory:)` is assumed to be the test-only initializer alongside
/// `SessionStore.shared` (mirroring `AudioCapture`'s/`WavFileWriter`'s constructor-injection style
/// elsewhere in this module) so each test gets an isolated root directory instead of sharing global
/// state through `.shared`.
@Suite("SessionStore crash recovery")
struct SessionStoreCrashRecoveryTests {
    private func makeTempRoot() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("SessionStoreCrashRecoveryTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func baseMeta(
        id: String,
        state: SessionState,
        startedAt: Date?,
        recordings: [RecordingSegment] = []
    ) -> SessionMeta {
        SessionMeta(
            id: id,
            title: "Test Session",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: state,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: startedAt,
            endedAt: nil,
            durationMs: 0,
            recordings: recordings,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    /// Writes `meta.json` for a session directly to disk, creating the session folder if needed.
    @discardableResult
    private func writeFixtureSession(root: URL, meta: SessionMeta) throws -> URL {
        let sessionDirectory = root.appendingPathComponent(meta.id, isDirectory: true)
        try FileManager.default.createDirectory(at: sessionDirectory, withIntermediateDirectories: true)
        let data = try SessionJSONCoding.makeEncoder().encode(meta)
        try data.write(to: sessionDirectory.appendingPathComponent("meta.json"), options: [.atomic])
        return sessionDirectory
    }

    /// Writes `transcript.jsonl` with the given segments, one JSON object per line, in the order
    /// given (which is deliberately not always `endMs`-sorted in these tests, since
    /// `finalizeCrashedSession(_:)` is documented to use the *last line*, not the maximum `endMs`).
    private func writeTranscript(_ segments: [TranscriptSegment], in sessionDirectory: URL) throws {
        let encoder = SessionJSONCoding.makeEncoder()
        var text = ""
        for segment in segments {
            let data = try encoder.encode(segment)
            text += String(data: data, encoding: .utf8)! + "\n"
        }
        try text.write(
            to: sessionDirectory.appendingPathComponent("transcript.jsonl"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func makeSegment(id: String, startMs: Int, endMs: Int) -> TranscriptSegment {
        TranscriptSegment(id: id, startMs: startMs, endMs: endMs, speaker: .mic, text: "text \(id)", confidence: 0.9)
    }

    // MARK: - detectIncompleteSessions

    @Test("detectIncompleteSessions returns only sessions left in .recording state")
    func detectIncompleteSessionsReturnsOnlyRecording() async throws {
        let root = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: root) }

        try writeFixtureSession(root: root, meta: baseMeta(id: "session-draft", state: .draft, startedAt: nil))
        try writeFixtureSession(
            root: root,
            meta: baseMeta(id: "session-recording", state: .recording, startedAt: Date(timeIntervalSince1970: 1_751_000_100))
        )
        try writeFixtureSession(
            root: root,
            meta: baseMeta(id: "session-ended", state: .ended, startedAt: Date(timeIntervalSince1970: 1_751_000_200))
        )

        let store = SessionStore(sessionsRootDirectory: root)
        let incomplete = await store.detectIncompleteSessions()

        #expect(incomplete.count == 1)
        #expect(incomplete.first?.id == "session-recording")
    }

    @Test("detectIncompleteSessions returns an empty array when no session is left recording")
    func detectIncompleteSessionsReturnsEmptyWhenNoneRecording() async throws {
        let root = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: root) }

        try writeFixtureSession(root: root, meta: baseMeta(id: "session-draft", state: .draft, startedAt: nil))
        try writeFixtureSession(
            root: root,
            meta: baseMeta(id: "session-ended", state: .ended, startedAt: Date(timeIntervalSince1970: 1_751_000_200))
        )

        let store = SessionStore(sessionsRootDirectory: root)
        let incomplete = await store.detectIncompleteSessions()

        #expect(incomplete.isEmpty)
    }

    @Test("detectIncompleteSessions returns every crashed session when there is more than one (failure mode #13)")
    func detectIncompleteSessionsReturnsAllCrashedSessions() async throws {
        let root = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: root) }

        try writeFixtureSession(
            root: root,
            meta: baseMeta(id: "session-recording-1", state: .recording, startedAt: Date(timeIntervalSince1970: 1_751_000_100))
        )
        try writeFixtureSession(
            root: root,
            meta: baseMeta(id: "session-recording-2", state: .recording, startedAt: Date(timeIntervalSince1970: 1_751_000_300))
        )

        let store = SessionStore(sessionsRootDirectory: root)
        let incomplete = await store.detectIncompleteSessions()

        #expect(Set(incomplete.map(\.id)) == Set(["session-recording-1", "session-recording-2"]))
    }

    // MARK: - finalizeCrashedSession

    @Test("finalizeCrashedSession derives durationMs/endedAt from the last transcript segment and sets state to .paused")
    func finalizeCrashedSessionEstimatesFromLastSegment() async throws {
        let root = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: root) }

        let startedAt = Date(timeIntervalSince1970: 1_751_000_000)
        let openSegment = RecordingSegment(index: 0, startedAt: startedAt, endedAt: nil, startMsOffset: 0)
        let sessionDirectory = try writeFixtureSession(
            root: root,
            meta: baseMeta(id: "session-crashed", state: .recording, startedAt: startedAt, recordings: [openSegment])
        )
        // Deliberately out of `endMs` order: the *last line* (seg_00003, endMs 9_000) should win,
        // not the segment with the largest `endMs` (seg_00002, endMs 12_000).
        try writeTranscript(
            [
                makeSegment(id: "seg_00001", startMs: 0, endMs: 5_000),
                makeSegment(id: "seg_00002", startMs: 5_000, endMs: 12_000),
                makeSegment(id: "seg_00003", startMs: 12_000, endMs: 9_000)
            ],
            in: sessionDirectory
        )

        let store = SessionStore(sessionsRootDirectory: root)
        let finalized = try await store.finalizeCrashedSession("session-crashed")

        // Crash recovery lands on .paused, not .ended: a crash is not the user deciding the meeting
        // is over (kikimi.md 15 章). The session is resumable/endable like any other Paused session.
        #expect(finalized.state == .paused)
        #expect(finalized.durationMs == 9_000)
        #expect(finalized.recordings.last?.endedAt == startedAt.addingTimeInterval(9.0))
        #expect(finalized.endedAt == nil)

        // The estimate must also have been persisted to disk, not just returned.
        let onDiskData = try Data(contentsOf: sessionDirectory.appendingPathComponent("meta.json"))
        let onDiskMeta = try SessionJSONCoding.makeDecoder().decode(SessionMeta.self, from: onDiskData)
        #expect(onDiskMeta.state == .paused)
        #expect(onDiskMeta.durationMs == 9_000)
    }

    @Test("finalizeCrashedSession falls back to durationMs = 0 when transcript.jsonl has no segments (failure mode #14)")
    func finalizeCrashedSessionFallsBackWhenTranscriptEmpty() async throws {
        let root = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: root) }

        let startedAt = Date(timeIntervalSince1970: 1_751_000_000)
        let openSegment = RecordingSegment(index: 0, startedAt: startedAt, endedAt: nil, startMsOffset: 0)
        // No transcript.jsonl written at all -- simulates a crash before any segment was appended.
        try writeFixtureSession(
            root: root,
            meta: baseMeta(id: "session-crashed-empty", state: .recording, startedAt: startedAt, recordings: [openSegment])
        )

        let store = SessionStore(sessionsRootDirectory: root)
        let finalized = try await store.finalizeCrashedSession("session-crashed-empty")

        #expect(finalized.state == .paused)
        #expect(finalized.durationMs == 0)
        #expect(finalized.recordings.last?.endedAt == startedAt)
        #expect(finalized.endedAt == nil)
    }

    @Test("finalizeCrashedSession throws sessionNotFound for a session id with no folder on disk")
    func finalizeCrashedSessionThrowsForMissingSession() async throws {
        let root = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: root) }

        let store = SessionStore(sessionsRootDirectory: root)

        await #expect(throws: SessionStoreError.sessionNotFound("does-not-exist")) {
            try await store.finalizeCrashedSession("does-not-exist")
        }
    }

    @Test("finalizeCrashedSession throws sessionNotInRecordingState for a session that is not .recording")
    func finalizeCrashedSessionThrowsForNonRecordingSession() async throws {
        let root = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: root) }

        try writeFixtureSession(root: root, meta: baseMeta(id: "session-draft", state: .draft, startedAt: nil))

        let store = SessionStore(sessionsRootDirectory: root)

        await #expect(throws: SessionStoreError.sessionNotInRecordingState("session-draft")) {
            try await store.finalizeCrashedSession("session-draft")
        }
    }
}
