import Foundation
import Testing

@testable import Kikimi

// MARK: - Fakes (docs/design/37-transcript-markdown-copy.md §7's "フェイク PasteboardWriting")

/// Records every string written and lets a test control whether the write "succeeds"
/// (`docs/design/37-transcript-markdown-copy.md` §3.3/TC10). `@unchecked Sendable` because
/// `PasteboardWriting` requires `Sendable` but this fake is only ever touched from the
/// `@MainActor` test body -- the same pattern the file's other fakes below use.
private final class FakePasteboard: PasteboardWriting, @unchecked Sendable {
    private(set) var writtenStrings: [String] = []
    var writeResult = true

    func writeString(_ string: String) -> Bool {
        writtenStrings.append(string)
        return writeResult
    }
}

/// Trivial `AudioInputEnumerating` stand-in so `hydrateFromSessionHandle()`'s automatic
/// `enumerateAudioInputs()` call (fired from `MeetingWorkspaceViewModel.init`'s unstructured
/// hydrate `Task`) never touches real `AVCaptureDevice`/CoreAudio enumeration, mirroring
/// `MeetingWorkspaceViewModelTests.swift`'s own `FakeAudioInputEnumerator` (kept as a separate,
/// file-private copy here since that one is not visible outside its file).
private struct FakeAudioInputEnumerator: AudioInputEnumerating {
    func inputDevices() -> [AudioDeviceInfo] { [] }
    func systemAudioProcesses() -> [AudioProcessInfo] { [] }
    func registeredSystemAudioApps() -> [AudioProcessInfo] { [] }
}

/// A `WikiExporting` that never touches disk. None of this suite's tests call `endMeeting()`, so
/// `export(sessionHandle:)` is never actually invoked -- this only exists to satisfy
/// `MeetingWorkspaceViewModel.init`'s `wikiExporter` parameter without evaluating the production
/// default (`defaultWikiExporter()`, which reads `AppConfig.shared`).
private struct NoOpWikiExporter: WikiExporting {
    func export(sessionHandle: SessionHandle) async throws {}
}

/// An `LLMCompleting` that fails loudly if ever called. None of this suite's tests run a Watcher,
/// but `MeetingWorkspaceViewModel.init` constructs a `WatcherRunner` synchronously (`watcherRunner
/// = watcherRunnerFactory(sessionHandle)`), which needs *some* `LLMCompleting` to hold onto.
private struct UnusedLLM: LLMCompleting {
    struct NotImplemented: Error {}
    func complete<T: Decodable & Sendable>(_ request: LLMRequest) async throws -> LLMResult<T> { throw NotImplemented() }
    func completeRaw(_ request: LLMRequest) async throws -> LLMResult<Data> { throw NotImplemented() }
}

// MARK: - MeetingWorkspaceViewModel + Copy (docs/design/37-transcript-markdown-copy.md §7)

/// Layer 1 (unit) coverage for `MeetingWorkspaceViewModel+Copy.swift`'s live-adapter Markdown copy
/// (`docs/design/37-transcript-markdown-copy.md` §3.2(a)/§3.3/§7): `copyMarkdown(scope:)` and
/// `copyRowMarkdown(rowId:)`. Every test constructs a real `MeetingWorkspaceViewModel` against a
/// temp-directory `SessionHandle` (never a real session under `~/.local/state/kikimi/sessions`) and
/// a `FakePasteboard`, then drives `transcriptRows`/`speakerLabels`/`summaryMarkdown` directly --
/// this is the live adapter, so there is no disk round-trip to simulate (unlike
/// `TranscriptMarkdownSourceTests`, which builds its fixtures through `SessionHandle`'s own
/// append/read API).
@Suite("MeetingWorkspaceViewModel+Copy")
@MainActor
struct MeetingWorkspaceViewModelCopyTests {
    // MARK: - Fixtures

    private func makeTemporaryDirectory(prefix: String) -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(prefix)-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func makeSessionMeta(
        id: String = "2026-07-01T14-30-00_a1b2c3d4",
        title: String = "定例MTG",
        recordings: [RecordingSegment] = [
            RecordingSegment(
                index: 0,
                startedAt: Date(timeIntervalSince1970: 1_751_000_100),
                endedAt: nil,
                startMsOffset: 0
            )
        ]
    ) -> SessionMeta {
        SessionMeta(
            id: id,
            title: title,
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_100),
            endedAt: nil,
            durationMs: 0,
            recordings: recordings,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func makeRow(
        id: String,
        startMs: Int = 0,
        endMs: Int = 1_000,
        speaker: AudioSourceKind = .mic,
        rawText: String = "raw text",
        state: TranscriptRowState = .raw
    ) -> TranscriptRowViewModel {
        TranscriptRowViewModel(id: id, startMs: startMs, endMs: endMs, speaker: speaker, rawText: rawText, state: state)
    }

    /// Constructs a real `MeetingWorkspaceViewModel` with every non-copy-related collaborator faked
    /// out or temp-directory-backed, so `init`'s unstructured hydrate `Task` (`hydrateFromSessionHandle()`)
    /// and the synchronous `watcherRunnerFactory(sessionHandle)` call never touch a real user
    /// directory/network. `diarizationSelfName` configures `appConfig.data.diarization.selfName`,
    /// consulted by (e)'s fallback test.
    private func makeViewModel(
        sessionHandle: SessionHandle,
        pasteboard: PasteboardWriting,
        diarizationSelfName: String = "自分"
    ) -> MeetingWorkspaceViewModel {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests")
        let appConfig = AppConfig(directory: root.appendingPathComponent("appconfig", isDirectory: true))
        appConfig.update { $0.diarization.selfName = diarizationSelfName }
        let appState = AppState(directory: root.appendingPathComponent("appstate", isDirectory: true))
        let voiceprintStore = VoiceprintStore(fileURL: root.appendingPathComponent("voiceprints.json"))
        let watcherLibrary = WatcherLibrary(presetsDirectory: root.appendingPathComponent("watcher-presets", isDirectory: true))

        return MeetingWorkspaceViewModel(
            sessionHandle: sessionHandle,
            inputEnumerator: FakeAudioInputEnumerator(),
            appState: appState,
            appConfig: appConfig,
            voiceprintStore: voiceprintStore,
            watcherLibrary: watcherLibrary,
            watcherRunnerFactory: { sessionHandle in
                WatcherRunner(sessionHandle: sessionHandle, llm: UnusedLLM(), library: watcherLibrary, resolveModel: { _ in ResolvedModel(provider: ModelResolver.builtinProviderName, model: "test-model") })
            },
            wikiExporter: NoOpWikiExporter(),
            pasteboard: pasteboard
        )
    }

    // MARK: - (a) scope 3 種

    @Test("copyMarkdown(scope:) renders frontmatter+summary+transcript for .full, and only the matching section for .transcript/.summary")
    func copyMarkdownRendersEachScope() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-a")
        defer { try? FileManager.default.removeItem(at: root) }
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta())
        let pasteboard = FakePasteboard()
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard)

        viewModel.transcriptRows = [makeRow(id: "seg_00001", startMs: 0, speaker: .mic, rawText: "raw", state: .refined("整形済みテキスト"))]
        viewModel.summaryMarkdown = "会議のサマリ本文"

        await viewModel.copyMarkdown(scope: .full)
        let full = try #require(pasteboard.writtenStrings.last)
        #expect(full.contains("---"))
        #expect(full.contains("# 定例MTG"))
        #expect(full.contains("## サマリ"))
        #expect(full.contains("会議のサマリ本文"))
        #expect(full.contains("## 書き起こし"))
        #expect(full.contains("整形済みテキスト"))
        #expect(viewModel.copyFeedbackToken == 1, "a successful copy must bump copyFeedbackToken (TC11)")
        #expect(viewModel.copyFeedbackRowId == nil, "a scope copy is not row-specific")

        await viewModel.copyMarkdown(scope: .transcript)
        let transcriptOnly = try #require(pasteboard.writtenStrings.last)
        #expect(!transcriptOnly.contains("---"), "scope == .transcript must omit frontmatter (TC6)")
        #expect(!transcriptOnly.contains("## サマリ"))
        #expect(transcriptOnly.contains("## 書き起こし"))
        #expect(transcriptOnly.contains("整形済みテキスト"))

        await viewModel.copyMarkdown(scope: .summary)
        let summaryOnly = try #require(pasteboard.writtenStrings.last)
        #expect(!summaryOnly.contains("---"))
        #expect(summaryOnly.contains("## サマリ"))
        #expect(!summaryOnly.contains("## 書き起こし"))
        #expect(!summaryOnly.contains("整形済みテキスト"))

        #expect(pasteboard.writtenStrings.count == 3)
        #expect(viewModel.copyFeedbackToken == 3)
    }

    // MARK: - (b) 行単体コピー

    @Test("copyRowMarkdown(rowId:) copies exactly one row in §4.4's format, with the raw-fallback marker and no trailing newline")
    func copyRowMarkdownFormatsOneRow() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-b1")
        defer { try? FileManager.default.removeItem(at: root) }
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta())
        let pasteboard = FakePasteboard()
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard, diarizationSelfName: "自分")

        // `startMs: 5_000` = 5s into the recording segment, whose `startedAt` is
        // `1_751_000_100` (`makeSessionMeta()`'s default recording) -> wall clock `1_751_000_105`.
        viewModel.transcriptRows = [makeRow(id: "seg_00001", startMs: 5_000, speaker: .mic, rawText: "raw fallback text", state: .raw)]

        await viewModel.copyRowMarkdown(rowId: "seg_00001")

        let written = try #require(pasteboard.writtenStrings.last)
        let expectedTime = DateFormatter.hhmmss.string(from: Date(timeIntervalSince1970: 1_751_000_105))
        #expect(written == "**\(expectedTime) 自分** raw fallback text *(raw)*")
        #expect(!written.hasSuffix("\n"), "renderLine must not append a trailing newline (§4.4)")
        #expect(viewModel.copyFeedbackRowId == "seg_00001")
        // A per-row copy must not also bump the toolbar's `copyFeedbackToken` -- the two controls
        // show independent feedback (`recordCopyResult(_:rowId:context:)`'s `rowId == nil` guard).
        #expect(viewModel.copyFeedbackToken == 0)
    }

    @Test("copyRowMarkdown(rowId:) is a silent no-op for a rowId that isn't currently visible (dropped/merged/nonexistent)")
    func copyRowMarkdownNoOpForMissingRow() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-b2")
        defer { try? FileManager.default.removeItem(at: root) }
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta())
        let pasteboard = FakePasteboard()
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard)

        viewModel.transcriptRows = [
            makeRow(id: "seg_dropped", state: .refined("")),
            makeRow(id: "seg_merged", state: .mergedInto(leaderId: "seg_00001"))
        ]

        await viewModel.copyRowMarkdown(rowId: "seg_does_not_exist")
        await viewModel.copyRowMarkdown(rowId: "seg_dropped")
        await viewModel.copyRowMarkdown(rowId: "seg_merged")

        #expect(pasteboard.writtenStrings.isEmpty)
        #expect(viewModel.copyFeedbackRowId == nil)
        #expect(viewModel.copyFeedbackToken == 0)
    }

    // MARK: - (c) isDroppedByRefinement / isMergedAway excluded (volatile rows are never in transcriptRows at all)

    @Test("copyMarkdown(scope:) excludes rows dropped by refinement (refined(\"\")) and rows merged away, keeping only the visible row")
    func copyMarkdownExcludesDroppedAndMergedRows() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-c")
        defer { try? FileManager.default.removeItem(at: root) }
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta())
        let pasteboard = FakePasteboard()
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard)

        viewModel.transcriptRows = [
            makeRow(id: "seg_dropped", startMs: 0, rawText: "意味のない発話", state: .refined("")),
            makeRow(id: "seg_merged", startMs: 1_000, rawText: "b", state: .mergedInto(leaderId: "seg_leader")),
            makeRow(id: "seg_leader", startMs: 2_000, rawText: "a b", state: .refined("残る発言"))
        ]

        await viewModel.copyMarkdown(scope: .transcript)

        let written = try #require(pasteboard.writtenStrings.last)
        #expect(written.contains("残る発言"))
        #expect(!written.contains("意味のない発話"))
        // The merged-away row's own raw text never appears as its own line -- only through the
        // leader row's already-merged `refinedText` above.
        #expect(written.components(separatedBy: "\n").filter { $0.contains("**") }.count == 1)
    }

    // MARK: - (c2) markdownBody(for:rawText:) の全 switch ケース (TC12/§4.3): .raw/.refining/.refinedFailed
    // はいずれも rawText + rawFallbackMarker、.refined(非空) は整形済みテキストのみ

    @Test("copyMarkdown(scope:) renders .raw/.refining/.refinedFailed rows as rawText with the *(raw)* marker, and .refined(non-empty) without it")
    func copyMarkdownAppliesRawFallbackMarkerPerRowState() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-c2")
        defer { try? FileManager.default.removeItem(at: root) }
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta())
        let pasteboard = FakePasteboard()
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard)

        // A row still awaiting refinement (recording in progress, TC12's "録音中の未整形行" case).
        viewModel.transcriptRows = [
            makeRow(id: "seg_raw", startMs: 0, rawText: "生テキスト・未整形", state: .raw),
            makeRow(id: "seg_refining", startMs: 1_000, rawText: "生テキスト・整形中", state: .refining),
            makeRow(id: "seg_failed", startMs: 2_000, rawText: "生テキスト・整形失敗", state: .refinedFailed("boom")),
            makeRow(id: "seg_ok", startMs: 3_000, rawText: "raw", state: .refined("整形済みテキスト"))
        ]

        await viewModel.copyMarkdown(scope: .transcript)

        let written = try #require(pasteboard.writtenStrings.last)
        #expect(written.contains("生テキスト・未整形 *(raw)*"), ".raw must fall back to rawText with the marker")
        #expect(written.contains("生テキスト・整形中 *(raw)*"), ".refining must fall back to rawText with the marker")
        #expect(written.contains("生テキスト・整形失敗 *(raw)*"), ".refinedFailed must fall back to rawText with the marker (kikimi.md 8.5 章)")
        #expect(written.contains("整形済みテキスト"))
        #expect(!written.contains("整形済みテキスト *(raw)*"), ".refined(non-empty) must not carry the raw-fallback marker")
    }

    // MARK: - (d) 録音中に meta を読み直していること (TC13)

    @Test("copyMarkdown(scope:) re-reads sessionHandle.meta on every call, reflecting a recordings[] segment appended after the view model was constructed")
    func copyMarkdownRereadsMetaEachCall() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-d")
        defer { try? FileManager.default.removeItem(at: root) }
        let initialRecording = RecordingSegment(
            index: 0, startedAt: Date(timeIntervalSince1970: 1_751_000_100), endedAt: Date(timeIntervalSince1970: 1_751_000_110), startMsOffset: 0
        )
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta(recordings: [initialRecording]))
        let pasteboard = FakePasteboard()
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard)

        // Simulates a pause/resume: a second recording segment starts a long time after the first
        // one ended, at a wall clock the first segment's own arithmetic could never produce.
        let secondSegmentStart = Date(timeIntervalSince1970: 1_751_010_000)
        try await handle.updateMeta { meta in
            meta.recordings.append(
                RecordingSegment(index: 1, startedAt: secondSegmentStart, endedAt: nil, startMsOffset: 10_000)
            )
        }

        // 5s into the *second* segment (`startMsOffset: 10_000` + 5_000).
        viewModel.transcriptRows = [makeRow(id: "seg_00002", startMs: 15_000, speaker: .mic, rawText: "raw", state: .refined("後半の発言"))]

        await viewModel.copyMarkdown(scope: .transcript)

        let written = try #require(pasteboard.writtenStrings.last)
        let expectedTime = DateFormatter.hhmmss.string(from: secondSegmentStart.addingTimeInterval(5))
        let staleTime = DateFormatter.hhmmss.string(from: initialRecording.startedAt.addingTimeInterval(15))
        #expect(written.contains(expectedTime), "must use the freshly-appended recordings[1], not the stale meta captured at construction time")
        #expect(!written.contains(staleTime))
    }

    // MARK: - (e) speakerLabels が空でも selfName / system になること (§3.2(a) のフォールバック)

    @Test("copyMarkdown(scope:) falls back to selfName for mic and \"system\" for system when speakerLabels has no entry for the row")
    func copyMarkdownFallsBackWhenSpeakerLabelsMissing() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-e")
        defer { try? FileManager.default.removeItem(at: root) }
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta())
        let pasteboard = FakePasteboard()
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard, diarizationSelfName: "テスト太郎")

        viewModel.transcriptRows = [
            makeRow(id: "seg_mic", startMs: 0, speaker: .mic, rawText: "こんにちは", state: .refined("こんにちは。")),
            makeRow(id: "seg_system", startMs: 1_000, speaker: .system, rawText: "よろしくお願いします", state: .refined("よろしくお願いします。"))
        ]
        // `speakerLabels` is deliberately left empty (diarization disabled / not yet computed).
        #expect(viewModel.speakerLabels.isEmpty)

        await viewModel.copyMarkdown(scope: .transcript)

        let written = try #require(pasteboard.writtenStrings.last)
        #expect(written.contains("テスト太郎"), "mic must fall back to the injected selfName, never an empty speaker name")
        #expect(written.contains("system"), "system must fall back to \"system\" (systemFallback), matching TranscriptTabView's own `resolvedLabel ?? .systemFallback`")
    }

    // MARK: - (e2) §4.2 の話者表記マッピング全ケース (named/anonymous/mixed/recognizing/unknown) と TC4 の overlap marker 無視

    @Test("copyMarkdown(scope:) maps every SpeakerDisplayLabel case in speakerLabels through §4.2's table for system rows, ignoring hasOverlapMarker (TC4)")
    func copyMarkdownMapsEverySpeakerDisplayLabelCase() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-e2")
        defer { try? FileManager.default.removeItem(at: root) }
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta())
        let pasteboard = FakePasteboard()
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard)

        viewModel.transcriptRows = [
            makeRow(id: "seg_named", startMs: 0, speaker: .system, rawText: "raw", state: .refined("名前解決済み")),
            makeRow(id: "seg_anonymous", startMs: 1_000, speaker: .system, rawText: "raw", state: .refined("匿名スロット")),
            makeRow(id: "seg_mixed", startMs: 2_000, speaker: .system, rawText: "raw", state: .refined("混在発話")),
            makeRow(id: "seg_recognizing", startMs: 3_000, speaker: .system, rawText: "raw", state: .refined("認識中")),
            makeRow(id: "seg_unknown", startMs: 4_000, speaker: .system, rawText: "raw", state: .refined("未帰属")),
            makeRow(id: "seg_overlap", startMs: 5_000, speaker: .system, rawText: "raw", state: .refined("同時発話マーカー付き"))
        ]
        viewModel.speakerLabels = [
            "seg_named": ResolvedSpeakerLabel(label: .named("田中さん"), hasOverlapMarker: false),
            "seg_anonymous": ResolvedSpeakerLabel(label: .anonymous(slotNumber: 2), hasOverlapMarker: false),
            "seg_mixed": ResolvedSpeakerLabel(label: .mixed(primary: "田中さん", secondary: "Speaker 3"), hasOverlapMarker: false),
            "seg_recognizing": ResolvedSpeakerLabel(label: .recognizing, hasOverlapMarker: false),
            "seg_unknown": ResolvedSpeakerLabel(label: .unknown, hasOverlapMarker: false),
            // `hasOverlapMarker: true` deliberately paired with `.systemFallback` here -- TC4 says the
            // marker must never leak into the copied text regardless of which label it rides along with.
            "seg_overlap": ResolvedSpeakerLabel(label: .systemFallback, hasOverlapMarker: true)
        ]

        await viewModel.copyMarkdown(scope: .transcript)

        let written = try #require(pasteboard.writtenStrings.last)
        #expect(written.contains("**\(DateFormatter.hhmmss.string(from: Date(timeIntervalSince1970: 1_751_000_100))) 田中さん** 名前解決済み"))
        #expect(written.contains("**\(DateFormatter.hhmmss.string(from: Date(timeIntervalSince1970: 1_751_000_101))) Speaker 2** 匿名スロット"))
        #expect(written.contains("**\(DateFormatter.hhmmss.string(from: Date(timeIntervalSince1970: 1_751_000_102))) 田中さん + Speaker 3** 混在発話"))
        #expect(written.contains("**\(DateFormatter.hhmmss.string(from: Date(timeIntervalSince1970: 1_751_000_103))) Speaker ?** 認識中"))
        #expect(written.contains("**\(DateFormatter.hhmmss.string(from: Date(timeIntervalSince1970: 1_751_000_104))) Speaker ?** 未帰属"))
        #expect(written.contains("**\(DateFormatter.hhmmss.string(from: Date(timeIntervalSince1970: 1_751_000_105))) system** 同時発話マーカー付き"))
        #expect(!written.contains("⚠"), "hasOverlapMarker must never appear in the copied Markdown (TC4)")
    }

    // MARK: - (f) フェイクが false を返したとき copyFeedbackToken を更新しないこと

    @Test("copyMarkdown(scope:) does not bump copyFeedbackToken (or set copyFeedbackRowId) when the pasteboard write fails")
    func copyMarkdownDoesNotUpdateFeedbackOnPasteboardFailure() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-f1")
        defer { try? FileManager.default.removeItem(at: root) }
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta())
        let pasteboard = FakePasteboard()
        pasteboard.writeResult = false
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard)

        viewModel.transcriptRows = [makeRow(id: "seg_00001", state: .refined("テキスト"))]

        await viewModel.copyMarkdown(scope: .full)

        #expect(pasteboard.writtenStrings.count == 1, "the write is still attempted")
        #expect(viewModel.copyFeedbackToken == 0, "a failed write must not bump copyFeedbackToken")
        #expect(viewModel.copyFeedbackRowId == nil)
    }

    @Test("copyRowMarkdown(rowId:) does not set copyFeedbackRowId when the pasteboard write fails")
    func copyRowMarkdownDoesNotUpdateFeedbackOnPasteboardFailure() async throws {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelCopyTests-f2")
        defer { try? FileManager.default.removeItem(at: root) }
        let handle = SessionHandle(directoryURL: root, meta: makeSessionMeta())
        let pasteboard = FakePasteboard()
        pasteboard.writeResult = false
        let viewModel = makeViewModel(sessionHandle: handle, pasteboard: pasteboard)

        viewModel.transcriptRows = [makeRow(id: "seg_00001", state: .refined("テキスト"))]

        await viewModel.copyRowMarkdown(rowId: "seg_00001")

        #expect(pasteboard.writtenStrings.count == 1)
        #expect(viewModel.copyFeedbackRowId == nil)
        #expect(viewModel.copyFeedbackToken == 0)
    }
}

// MARK: - DateFormatter.hhmmss

/// Shared `HH:mm:ss` formatter matching `TranscriptMarkdownRenderer`'s own private `timeFormatter`
/// (`Kikimi/Markdown/TranscriptMarkdownRenderer.swift`) exactly, so this file's assertions compute
/// expected times the same way the renderer does, without reaching into that `private` formatter.
private extension DateFormatter {
    static let hhmmss: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = .current
        formatter.dateFormat = "HH:mm:ss"
        return formatter
    }()
}
