import Foundation
import Testing

@testable import Kikimi

// MARK: - Test suite

/// Layer 1 (unit) coverage for `MeetingWorkspaceViewModel+OutputRoute.swift`
/// (`docs/design/24-system-audio-leak-mitigation.md` §5), the module's own file with zero prior test
/// coverage. `OutputRouteClassification.classify(transportType:)` (the other half of this design's
/// testable surface) is already covered by `KikimiTests/AudioCapture/OutputRouteMonitorTests.swift`,
/// and `AudioConfig`'s decode/default behavior by `KikimiTests/Config/AppConfigTests.swift` -- neither
/// is duplicated here.
///
/// Every test below deliberately avoids exercising `OutputRouteMonitor`'s *actual* CoreAudio polling
/// result: design §8's layer-2 section explicitly scopes real device-dependent behavior (does the
/// banner actually appear for a real built-in-speaker output) out of automated testing, since it
/// depends on whatever output device happens to be the default on the machine running the test suite.
/// Tests that need a "monitor already exists" precondition either (a) never call `.start()` on it (so
/// no CoreAudio call ever happens), or (b) call `startOutputRouteMonitorIfNeeded()` itself but only
/// assert on facts that don't depend on which classification the real hardware read happens to
/// produce (e.g. "a monitor now exists", never "the banner is/isn't showing").
@Suite("MeetingWorkspaceViewModel+OutputRoute")
@MainActor
struct MeetingWorkspaceViewModelOutputRouteTests {
    private func makeTemporaryDirectory(prefix: String) -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(prefix)-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func baseMeta(id: String) -> SessionMeta {
        SessionMeta(
            id: id,
            title: "",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .draft,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: nil,
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    /// Builds a hermetic `MeetingWorkspaceViewModel` with a temp-directory-backed `sessionHandle`/
    /// `appConfig`/`appState`/`sessionStore` (never `.shared`, so no test ever touches the real
    /// `~/.local/state/kikimi/`/`~/.config/kikimi/`). None of these tests call `onAppear()`/
    /// `startRecording()`, so the audio/transcript/diarization/refinement factories are left at their
    /// production defaults -- they're never invoked.
    private func makeViewModel(audioConfig: AudioConfig = .default) -> MeetingWorkspaceViewModel {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelOutputRouteTests")
        let sessionDirectory = root.appendingPathComponent("session", isDirectory: true)
        try? FileManager.default.createDirectory(at: sessionDirectory, withIntermediateDirectories: true)
        let handle = SessionHandle(directoryURL: sessionDirectory, meta: baseMeta(id: "session-output-route"))

        let appConfig = AppConfig(directory: root.appendingPathComponent("config", isDirectory: true))
        appConfig.update { $0.audio = audioConfig }

        let store = SessionStore(
            sessionsRootDirectory: root.appendingPathComponent("sessions", isDirectory: true),
            defaultContextFileURL: root.appendingPathComponent("missing-context.md"),
            defaultSummaryTemplateFileURL: root.appendingPathComponent("missing-template.md"),
            defaultEnabledWatchersFileURL: root.appendingPathComponent("missing-enabled.yaml")
        )

        return MeetingWorkspaceViewModel(
            sessionHandle: handle,
            sessionStore: store,
            appState: AppState(directory: root.appendingPathComponent("state", isDirectory: true)),
            appConfig: appConfig,
            voiceprintStore: VoiceprintStore(
                fileURL: root.appendingPathComponent("voiceprints.json")
            )
        )
    }

    // MARK: - startOutputRouteMonitorIfNeeded() config gate (§5.3)

    @Test("startOutputRouteMonitorIfNeeded() does not create a monitor when audio.suggest_headphones_on_builtin_speaker is false")
    func startDoesNothingWhenConfigDisabled() {
        let viewModel = makeViewModel(audioConfig: AudioConfig(suggestHeadphonesOnBuiltInSpeaker: false))

        viewModel.startOutputRouteMonitorIfNeeded()

        #expect(viewModel.outputRoute.monitor == nil)
    }

    @Test("startOutputRouteMonitorIfNeeded() resets systemAudioDegradedInCurrentSegment even when the config toggle is off")
    func startResetsDegradedFlagEvenWhenConfigDisabled() {
        let viewModel = makeViewModel(audioConfig: AudioConfig(suggestHeadphonesOnBuiltInSpeaker: false))
        viewModel.outputRoute.systemAudioDegradedInCurrentSegment = true

        viewModel.startOutputRouteMonitorIfNeeded()

        #expect(viewModel.outputRoute.systemAudioDegradedInCurrentSegment == false)
        #expect(viewModel.outputRoute.monitor == nil, "a disabled config must still skip monitor creation")
    }

    @Test("startOutputRouteMonitorIfNeeded() constructs a monitor when the config toggle is on and none exists yet")
    func startCreatesMonitorWhenConfigEnabled() {
        let viewModel = makeViewModel(audioConfig: .default)

        viewModel.startOutputRouteMonitorIfNeeded()
        defer { viewModel.stopOutputRouteMonitor() }

        #expect(viewModel.outputRoute.monitor != nil)
        #expect(viewModel.outputRoute.systemAudioDegradedInCurrentSegment == false)
    }

    @Test("startOutputRouteMonitorIfNeeded() is idempotent: it never replaces an already-set monitor")
    func startIsIdempotentAcrossRepeatedCalls() {
        let viewModel = makeViewModel(audioConfig: .default)
        // A never-started monitor stands in for "a monitor from a prior call already exists" --
        // deliberately never `.start()`-ed so this test makes zero real CoreAudio calls and its
        // outcome cannot depend on the test machine's actual default output device.
        let existingMonitor = OutputRouteMonitor()
        viewModel.outputRoute.monitor = existingMonitor

        viewModel.startOutputRouteMonitorIfNeeded()

        #expect(viewModel.outputRoute.monitor === existingMonitor, "must not overwrite the existing monitor with a freshly constructed one")
    }

    // MARK: - stopOutputRouteMonitor() (§5.1/§5.2)

    @Test("stopOutputRouteMonitor() is a safe no-op when no monitor was ever started")
    func stopIsNoOpWhenNeverStarted() {
        let viewModel = makeViewModel(audioConfig: .default)

        viewModel.stopOutputRouteMonitor()

        #expect(viewModel.outputRoute.monitor == nil)
        #expect(viewModel.banners.isEmpty)
    }

    @Test("stopOutputRouteMonitor() discards the monitor and removes an already-shown builtInSpeakerOutputDetected banner")
    func stopDiscardsMonitorAndRemovesBanner() {
        let viewModel = makeViewModel(audioConfig: .default)
        // Never started (see `startIsIdempotentAcrossRepeatedCalls`'s doc comment for why): this test
        // only cares about `stopOutputRouteMonitor()`'s own two documented effects, not about
        // `OutputRouteMonitor`'s real polling behavior.
        viewModel.outputRoute.monitor = OutputRouteMonitor()
        viewModel.banners.append(.builtInSpeakerOutputDetected)
        viewModel.banners.append(.transcriptWriteFailed)

        viewModel.stopOutputRouteMonitor()

        #expect(viewModel.outputRoute.monitor == nil)
        #expect(!viewModel.banners.contains(where: { $0.id == WorkspaceBanner.builtInSpeakerOutputDetected.id }))
        // Only the built-in-speaker banner is this method's concern -- every unrelated banner must
        // survive untouched.
        #expect(viewModel.banners.contains(where: { $0.id == WorkspaceBanner.transcriptWriteFailed.id }))
    }

    // MARK: - dismissBuiltInSpeakerBanner() (§5.2 "永続 dismiss")

    @Test("dismissBuiltInSpeakerBanner() removes the banner and permanently latches dismissedBuiltInSpeakerBanner")
    func dismissRemovesBannerAndLatchesFlag() {
        let viewModel = makeViewModel(audioConfig: .default)
        viewModel.banners.append(.builtInSpeakerOutputDetected)
        #expect(viewModel.outputRoute.dismissedBuiltInSpeakerBanner == false)

        viewModel.dismissBuiltInSpeakerBanner()

        #expect(viewModel.outputRoute.dismissedBuiltInSpeakerBanner == true)
        #expect(!viewModel.banners.contains(where: { $0.id == WorkspaceBanner.builtInSpeakerOutputDetected.id }))
    }

    @Test("dismissBuiltInSpeakerBanner() latches the flag even when the banner isn't currently showing")
    func dismissLatchesFlagEvenWithoutBanner() {
        let viewModel = makeViewModel(audioConfig: .default)

        viewModel.dismissBuiltInSpeakerBanner()

        #expect(viewModel.outputRoute.dismissedBuiltInSpeakerBanner == true)
        #expect(viewModel.banners.isEmpty)
    }
}
