import Foundation
import Testing

@testable import Kikimi

// MARK: - Fakes

/// Records writes and lets a test fail the write, mirroring `MeetingWorkspaceViewModel+CopyTests`'s
/// own fake. `@unchecked Sendable` because `PasteboardWriting` demands `Sendable` while this is only
/// ever touched from the `@MainActor` test body.
private final class FakeChatPasteboard: PasteboardWriting, @unchecked Sendable {
    private(set) var writtenStrings: [String] = []
    var writeResult = true

    func writeString(_ string: String) -> Bool {
        writtenStrings.append(string)
        return writeResult
    }
}

/// An `LLMCompleting` whose per-call outcome the test scripts: either a canned answer or a thrown
/// error. `actor` so the recorded calls are race-free.
private actor ScriptedChatLLM: LLMCompleting {
    enum Outcome: Sendable {
        case answer(String)
        case failure
    }

    struct ScriptedFailure: Error, LocalizedError {
        var errorDescription: String? { "scripted failure" }
    }

    private var outcomes: [Outcome]
    private(set) var callCount = 0

    init(outcomes: [Outcome]) {
        self.outcomes = outcomes
    }

    func complete<T: Decodable & Sendable>(_ request: LLMRequest) async throws -> LLMResult<T> {
        callCount += 1
        switch outcomes.isEmpty ? .failure : outcomes.removeFirst() {
        case .failure:
            throw ScriptedFailure()
        case .answer(let answer):
            let encoded = try JSONEncoder().encode(["answer": answer])
            let decoder = JSONDecoder()
            decoder.keyDecodingStrategy = .convertFromSnakeCase
            return LLMResult(value: try decoder.decode(T.self, from: encoded), usage: .zero)
        }
    }

    func completeRaw(_ request: LLMRequest) async throws -> LLMResult<Data> {
        throw ScriptedFailure()
    }
}

private struct FakeChatAudioInputEnumerator: AudioInputEnumerating {
    func inputDevices() -> [AudioDeviceInfo] { [] }
    func systemAudioProcesses() -> [AudioProcessInfo] { [] }
    func registeredSystemAudioApps() -> [AudioProcessInfo] { [] }
}

private struct NoOpChatWikiExporter: WikiExporting {
    func export(sessionHandle: SessionHandle) async throws {}
}

private struct UnusedChatLLM: LLMCompleting {
    struct NotImplemented: Error {}
    func complete<T: Decodable & Sendable>(_ request: LLMRequest) async throws -> LLMResult<T> { throw NotImplemented() }
    func completeRaw(_ request: LLMRequest) async throws -> LLMResult<Data> { throw NotImplemented() }
}

// MARK: - MeetingWorkspaceViewModel + Chat

/// Layer 1 coverage for `MeetingWorkspaceViewModel+Chat.swift` (`docs/design/38-session-chat.md`
/// §7). Every test drives a real view model against a temp-directory `SessionHandle`, so the
/// `chat.jsonl` writes these assertions rely on are the real ones.
@Suite("MeetingWorkspaceViewModel+Chat")
@MainActor
struct MeetingWorkspaceViewModelChatTests {
    // MARK: - Fixtures

    private func makeTemporaryDirectory(prefix: String) -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(prefix)-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func makeSessionMeta() -> SessionMeta {
        SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: "定例MTG",
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .ended,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_100),
            endedAt: Date(timeIntervalSince1970: 1_751_000_500),
            durationMs: 400_000,
            recordings: [
                RecordingSegment(
                    index: 0,
                    startedAt: Date(timeIntervalSince1970: 1_751_000_100),
                    endedAt: Date(timeIntervalSince1970: 1_751_000_500),
                    startMsOffset: 0
                )
            ],
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func makeViewModel(
        sessionHandle: SessionHandle,
        chatLLM: any LLMCompleting = UnusedChatLLM(),
        pasteboard: PasteboardWriting = FakeChatPasteboard()
    ) -> MeetingWorkspaceViewModel {
        let root = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelChatTests-deps")
        let appConfig = AppConfig(directory: root.appendingPathComponent("appconfig", isDirectory: true))
        let appState = AppState(directory: root.appendingPathComponent("appstate", isDirectory: true))
        let voiceprintStore = VoiceprintStore(fileURL: root.appendingPathComponent("voiceprints.json"))
        let watcherLibrary = WatcherLibrary(presetsDirectory: root.appendingPathComponent("watcher-presets", isDirectory: true))

        return MeetingWorkspaceViewModel(
            sessionHandle: sessionHandle,
            inputEnumerator: FakeChatAudioInputEnumerator(),
            appState: appState,
            appConfig: appConfig,
            voiceprintStore: voiceprintStore,
            watcherLibrary: watcherLibrary,
            watcherRunnerFactory: { handle in
                WatcherRunner(sessionHandle: handle, llm: UnusedChatLLM(), library: watcherLibrary, defaultModel: "test-model")
            },
            chatRunnerFactory: { handle in
                ChatRunner(
                    llm: chatLLM,
                    source: TranscriptMarkdownSource(diarization: .default, voiceprintStore: voiceprintStore),
                    config: .default
                )
            },
            wikiExporter: NoOpChatWikiExporter(),
            pasteboard: pasteboard
        )
    }

    // MARK: - (a) the question is persisted before the answer is awaited

    @Test("sendChatMessage persists the question before the answer exists")
    func questionIsPersistedBeforeTheAnswer() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelChatTests-a")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = SessionHandle(directoryURL: sessionDir, meta: makeSessionMeta())
        let viewModel = makeViewModel(sessionHandle: handle, chatLLM: ScriptedChatLLM(outcomes: [.answer("回答本文")]))

        viewModel.chatDraft = "  決まったことは？  "
        await viewModel.sendChatMessage()

        #expect(viewModel.chatDraft.isEmpty, "the composer clears once the question is on record")
        #expect(viewModel.chatTurns.map(\.role) == [.user, .assistant])
        #expect(viewModel.chatTurns[0].text == "決まったことは？", "the draft is trimmed before it is stored")
        #expect(viewModel.chatTurns[1].text == "回答本文")
        #expect(viewModel.chatTurns[1].parentTurnId == viewModel.chatTurns[0].id)

        // Both lines actually reached disk, and the question is first -- which is what survives a
        // crash while the answer is still in flight.
        let persisted = try await handle.readChatTurns()
        #expect(persisted.map(\.role) == [.user, .assistant])
        #expect(persisted[0].id == viewModel.chatTurns[0].id)
    }

    @Test("a blank draft sends nothing")
    func blankDraftSendsNothing() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelChatTests-a2")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = SessionHandle(directoryURL: sessionDir, meta: makeSessionMeta())
        let viewModel = makeViewModel(sessionHandle: handle)

        viewModel.chatDraft = "   \n  "
        await viewModel.sendChatMessage()

        #expect(viewModel.chatTurns.isEmpty)
        #expect(try await handle.readChatTurns().isEmpty)
    }

    // MARK: - (b)/(c) failure and retry

    @Test("a failure is kept as an error turn, and a retry replaces it on screen and in the file")
    func failureThenRetry() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelChatTests-b")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = SessionHandle(directoryURL: sessionDir, meta: makeSessionMeta())
        let viewModel = makeViewModel(
            sessionHandle: handle,
            chatLLM: ScriptedChatLLM(outcomes: [.failure, .answer("再送で成功した回答")])
        )

        viewModel.chatDraft = "決まったことは？"
        await viewModel.sendChatMessage()

        #expect(viewModel.chatTurns.count == 2)
        let failedTurn = try #require(viewModel.chatTurns.last)
        #expect(failedTurn.error != nil)
        #expect(failedTurn.text.isEmpty)

        await viewModel.retryChatTurn(id: failedTurn.id)

        // The failure is gone from the list, not because it was rewritten but because the retry
        // supersedes it -- `chat.jsonl` still holds all three lines.
        #expect(viewModel.chatTurns.count == 2)
        let retried = try #require(viewModel.chatTurns.last)
        #expect(retried.text == "再送で成功した回答")
        #expect(retried.replacesTurnId == failedTurn.id)
        #expect(retried.parentTurnId == viewModel.chatTurns[0].id, "the retry answers the same question")

        let persisted = try await handle.readChatTurns()
        #expect(persisted.count == 3, "chat.jsonl is append-only; nothing is rewritten")
        #expect(ChatTurnLog.fold(persisted).map(\.id) == viewModel.chatTurns.map(\.id))
    }

    @Test("retrying an unknown id does nothing")
    func retryingUnknownIdIsANoOp() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelChatTests-b2")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = SessionHandle(directoryURL: sessionDir, meta: makeSessionMeta())
        let viewModel = makeViewModel(sessionHandle: handle)

        await viewModel.retryChatTurn(id: "nonexistent")

        #expect(viewModel.chatTurns.isEmpty)
    }

    // MARK: - (d) isChatResponding

    @Test("isChatResponding is false before and after a send, including on failure")
    func respondingFlagSettles() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelChatTests-d")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = SessionHandle(directoryURL: sessionDir, meta: makeSessionMeta())
        let viewModel = makeViewModel(sessionHandle: handle, chatLLM: ScriptedChatLLM(outcomes: [.failure]))

        #expect(!viewModel.isChatResponding)
        viewModel.chatDraft = "質問"
        await viewModel.sendChatMessage()
        #expect(!viewModel.isChatResponding, "a failed call must still re-enable the composer")
    }

    // MARK: - (e) history load

    @Test("loadChatHistory restores the log and folds superseded failures away")
    func loadChatHistoryFolds() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelChatTests-e")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = SessionHandle(directoryURL: sessionDir, meta: makeSessionMeta())

        let created = Date(timeIntervalSince1970: 1_751_000_200)
        try await handle.appendChatTurn(ChatTurn(id: "u1", role: .user, text: "q1", createdAt: created))
        try await handle.appendChatTurn(
            ChatTurn(id: "a1", role: .assistant, text: "", createdAt: created, parentTurnId: "u1", error: "boom")
        )
        try await handle.appendChatTurn(
            ChatTurn(id: "a2", role: .assistant, text: "answer", createdAt: created, parentTurnId: "u1", replacesTurnId: "a1")
        )

        let viewModel = makeViewModel(sessionHandle: handle)
        await viewModel.loadChatHistory()

        #expect(viewModel.chatTurns.map(\.id) == ["u1", "a2"])
    }

    // MARK: - Copy

    @Test("copyChatAnswer writes the answer's Markdown and marks that turn as copied")
    func copyChatAnswerWritesMarkdown() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelChatTests-copy")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = SessionHandle(directoryURL: sessionDir, meta: makeSessionMeta())
        let pasteboard = FakeChatPasteboard()
        let viewModel = makeViewModel(
            sessionHandle: handle,
            chatLLM: ScriptedChatLLM(outcomes: [.answer("## 決定事項\n- リリースは来週火曜")]),
            pasteboard: pasteboard
        )

        viewModel.chatDraft = "決まったことは？"
        await viewModel.sendChatMessage()
        let answerId = try #require(viewModel.chatTurns.last?.id)

        viewModel.copyChatAnswer(id: answerId)

        #expect(pasteboard.writtenStrings == ["## 決定事項\n- リリースは来週火曜"])
        #expect(viewModel.chatCopyFeedbackTurnId == answerId)
    }

    @Test("a failed pasteboard write shows no copy feedback")
    func failedCopyShowsNoFeedback() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "MeetingWorkspaceViewModelChatTests-copy2")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = SessionHandle(directoryURL: sessionDir, meta: makeSessionMeta())
        let pasteboard = FakeChatPasteboard()
        pasteboard.writeResult = false
        let viewModel = makeViewModel(
            sessionHandle: handle,
            chatLLM: ScriptedChatLLM(outcomes: [.answer("回答")]),
            pasteboard: pasteboard
        )

        viewModel.chatDraft = "質問"
        await viewModel.sendChatMessage()
        viewModel.copyChatAnswer(id: try #require(viewModel.chatTurns.last?.id))

        #expect(viewModel.chatCopyFeedbackTurnId == nil)
    }

    // MARK: - Composer

    @Test("ChatComposer.canSend rejects blank drafts and in-flight sends")
    func composerSendGuard() {
        #expect(ChatComposer.canSend(draft: "質問", isResponding: false))
        #expect(!ChatComposer.canSend(draft: "   \n ", isResponding: false))
        #expect(!ChatComposer.canSend(draft: "", isResponding: false))
        #expect(!ChatComposer.canSend(draft: "質問", isResponding: true))
    }
}
