import Foundation
import Testing

@testable import Kikimi

/// Layer 1 (unit) coverage for `SessionListViewModel`'s pure logic
/// (`Kikimi/ViewModels/SessionListViewModel.swift`, `docs/design/06-ui-panels.md` section 5.4/12).
///
/// `SessionListViewModel` itself talks to the `SessionStore`/`WindowManager` singletons (real
/// actor state, real `~/.local/state/kikimi`), so per section 12's own scoping this suite exercises
/// the pure `SessionListGrouping` core directly against fixture `SessionMeta` data — the same
/// approach `TranscriptRowListTests.swift` takes for `TranscriptRowList`. `SessionListViewModel
/// .groupedByMonth()` is a thin, untestable-in-isolation wrapper around this core (it reads from
/// `private(set) var sessions`, which only `SessionStore`-backed `refresh()` can populate).
@Suite("SessionListGrouping")
struct SessionListGroupingTests {
    // MARK: - Fixtures

    private func meta(
        id: String = "2026-07-01T14-30-00_a1b2c3d4",
        title: String = "デイリースクラム",
        state: SessionState = .ended,
        createdAt: Date
    ) -> SessionMeta {
        SessionMeta(
            id: id,
            title: title,
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: state,
            createdAt: createdAt,
            startedAt: nil,
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func date(_ year: Int, _ month: Int, _ day: Int, _ hour: Int = 0, _ minute: Int = 0, calendar: Calendar) -> Date {
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = day
        components.hour = hour
        components.minute = minute
        return calendar.date(from: components)!
    }

    private var calendar: Calendar { Calendar(identifier: .gregorian) }

    // MARK: - filtered(_:searchText:stateFilter:) — state filter

    @Test(".all keeps draft, recording, and ended sessions")
    func stateFilterAllKeepsEverything() {
        let sessions = [
            meta(id: "a", state: .draft, createdAt: date(2026, 7, 1, calendar: calendar)),
            meta(id: "b", state: .recording, createdAt: date(2026, 7, 2, calendar: calendar)),
            meta(id: "c", state: .ended, createdAt: date(2026, 7, 3, calendar: calendar))
        ]

        let result = SessionListGrouping.filtered(sessions, searchText: "", stateFilter: .all)

        #expect(result.map(\.id).sorted() == ["a", "b", "c"])
    }

    @Test(".draftOnly keeps only draft sessions, excluding recording")
    func stateFilterDraftOnlyExcludesRecording() {
        let sessions = [
            meta(id: "a", state: .draft, createdAt: date(2026, 7, 1, calendar: calendar)),
            meta(id: "b", state: .recording, createdAt: date(2026, 7, 2, calendar: calendar)),
            meta(id: "c", state: .ended, createdAt: date(2026, 7, 3, calendar: calendar))
        ]

        let result = SessionListGrouping.filtered(sessions, searchText: "", stateFilter: .draftOnly)

        #expect(result.map(\.id) == ["a"])
    }

    @Test(".endedOnly keeps only ended sessions, excluding recording")
    func stateFilterEndedOnlyExcludesRecording() {
        let sessions = [
            meta(id: "a", state: .draft, createdAt: date(2026, 7, 1, calendar: calendar)),
            meta(id: "b", state: .recording, createdAt: date(2026, 7, 2, calendar: calendar)),
            meta(id: "c", state: .ended, createdAt: date(2026, 7, 3, calendar: calendar))
        ]

        let result = SessionListGrouping.filtered(sessions, searchText: "", stateFilter: .endedOnly)

        #expect(result.map(\.id) == ["c"])
    }

    // MARK: - filtered(_:searchText:stateFilter:) — search text

    @Test("empty search text (including whitespace-only) keeps all sessions")
    func emptySearchTextKeepsEverything() {
        let sessions = [
            meta(id: "a", title: "デイリースクラム", createdAt: date(2026, 7, 1, calendar: calendar)),
            meta(id: "b", title: "顧客A打ち合わせ", createdAt: date(2026, 7, 2, calendar: calendar))
        ]

        #expect(SessionListGrouping.filtered(sessions, searchText: "", stateFilter: .all).count == 2)
        #expect(SessionListGrouping.filtered(sessions, searchText: "   ", stateFilter: .all).count == 2)
    }

    @Test("search text matches titles case-insensitively as a substring")
    func searchTextMatchesCaseInsensitiveSubstring() {
        let sessions = [
            meta(id: "a", title: "Daily Scrum", createdAt: date(2026, 7, 1, calendar: calendar)),
            meta(id: "b", title: "顧客A打ち合わせ", createdAt: date(2026, 7, 2, calendar: calendar))
        ]

        let result = SessionListGrouping.filtered(sessions, searchText: "daily", stateFilter: .all)

        #expect(result.map(\.id) == ["a"])
    }

    @Test("search text with no matches produces an empty result")
    func searchTextWithNoMatchesProducesEmptyResult() {
        let sessions = [meta(id: "a", title: "デイリースクラム", createdAt: date(2026, 7, 1, calendar: calendar))]

        let result = SessionListGrouping.filtered(sessions, searchText: "存在しない", stateFilter: .all)

        #expect(result.isEmpty)
    }

    @Test("state filter and search text combine (both must match)")
    func stateFilterAndSearchTextCombine() {
        let sessions = [
            meta(id: "a", title: "デイリースクラム", state: .draft, createdAt: date(2026, 7, 1, calendar: calendar)),
            meta(id: "b", title: "デイリースクラム", state: .ended, createdAt: date(2026, 7, 2, calendar: calendar)),
            meta(id: "c", title: "顧客A打ち合わせ", state: .ended, createdAt: date(2026, 7, 3, calendar: calendar))
        ]

        let result = SessionListGrouping.filtered(sessions, searchText: "デイリー", stateFilter: .endedOnly)

        #expect(result.map(\.id) == ["b"])
    }

    // MARK: - groupedByMonth(_:searchText:stateFilter:calendar:)

    @Test("groups sessions by calendar month, most-recent month first")
    func groupsByMonthMostRecentFirst() {
        let sessions = [
            meta(id: "june", title: "1on1", createdAt: date(2026, 6, 30, 15, 0, calendar: calendar)),
            meta(id: "july-early", title: "顧客A打ち合わせ", createdAt: date(2026, 7, 1, 10, 0, calendar: calendar)),
            meta(id: "july-late", title: "デイリースクラム", createdAt: date(2026, 7, 1, 14, 30, calendar: calendar))
        ]

        let groups = SessionListGrouping.groupedByMonth(sessions, searchText: "", stateFilter: .all, calendar: calendar)

        #expect(groups.map(\.month) == ["2026-07", "2026-06"])
        #expect(groups[0].sessions.map(\.id) == ["july-late", "july-early"])
        #expect(groups[1].sessions.map(\.id) == ["june"])
    }

    @Test("within a month, sessions are ordered by createdAt descending (newest first)")
    func withinMonthOrderedNewestFirst() {
        let sessions = [
            meta(id: "morning", createdAt: date(2026, 7, 1, 9, 0, calendar: calendar)),
            meta(id: "afternoon", createdAt: date(2026, 7, 1, 15, 0, calendar: calendar)),
            meta(id: "noon", createdAt: date(2026, 7, 1, 12, 0, calendar: calendar))
        ]

        let groups = SessionListGrouping.groupedByMonth(sessions, searchText: "", stateFilter: .all, calendar: calendar)

        #expect(groups.count == 1)
        #expect(groups[0].sessions.map(\.id) == ["afternoon", "noon", "morning"])
    }

    @Test("filtering to an empty result produces no month groups")
    func filteringToEmptyResultProducesNoGroups() {
        let sessions = [meta(id: "a", title: "デイリースクラム", createdAt: date(2026, 7, 1, calendar: calendar))]

        let groups = SessionListGrouping.groupedByMonth(sessions, searchText: "存在しない", stateFilter: .all, calendar: calendar)

        #expect(groups.isEmpty)
    }

    @Test("an empty session list produces no month groups")
    func emptySessionListProducesNoGroups() {
        let groups = SessionListGrouping.groupedByMonth([], searchText: "", stateFilter: .all, calendar: calendar)

        #expect(groups.isEmpty)
    }
}

// MARK: - SessionListToast

@Suite("SessionListToast")
struct SessionListToastTests {
    @Test("cannotDeleteActiveRecording has a stable id independent of the session id")
    func idIsStableAcrossSessionIds() {
        let first = SessionListToast.cannotDeleteActiveRecording(sessionId: "session-1")
        let second = SessionListToast.cannotDeleteActiveRecording(sessionId: "session-2")

        #expect(first.id == second.id)
    }

    @Test("cannotDeleteActiveRecording's message matches the design doc's failure mode #5 copy")
    func messageMatchesDesignDocCopy() {
        let toast = SessionListToast.cannotDeleteActiveRecording(sessionId: "session-1")

        #expect(toast.message == "録音中のセッションは削除できません")
    }

    @Test("Equatable distinguishes toasts by their associated sessionId")
    func equatableDistinguishesSessionId() {
        #expect(
            SessionListToast.cannotDeleteActiveRecording(sessionId: "a")
                != .cannotDeleteActiveRecording(sessionId: "b")
        )
    }
}

// MARK: - SessionListViewModel.SessionStateFilter

@Suite("SessionListViewModel.SessionStateFilter")
struct SessionStateFilterTests {
    @Test("exposes exactly the three cases the design doc's Session List mockup calls for")
    func allCasesMatchesDesignDoc() {
        #expect(SessionListViewModel.SessionStateFilter.allCases == [.all, .draftOnly, .endedOnly])
    }
}
