import AVFoundation
import Foundation
import Testing

@testable import Kikimi

/// Unit tests for `TranscriptPipeline` (`docs/design/11-streaming-stt.md` section 3.1/3.2/3.7).
/// `TranscriptPipeline` constructs its own `SttEngine`s but accepts an injectable
/// `SttEngine.BackendFactory` (section 3.12's "フェイク注入"), so these tests exercise `prepare()`
/// failure propagation and stop-without-prepare lifecycle safety without any real FluidAudio model
/// or network access.
@Suite("TranscriptPipeline")
struct TranscriptPipelineTests {
    private struct FakeBackendFactoryError: Error, Equatable {
        var message: String
    }

    private func makeTempSessionDirectory() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("TranscriptPipelineTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func makeSessionHandle() -> SessionHandle {
        let meta = SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: "Test Session",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_010),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
        return SessionHandle(directoryURL: makeTempSessionDirectory(), meta: meta)
    }

    private func makeMonoFloatBuffer(frameCount: AVAudioFrameCount = 10) throws -> AVAudioPCMBuffer {
        let format = try #require(AVAudioFormat(standardFormatWithSampleRate: 16_000, channels: 1))
        let buffer = try #require(AVAudioPCMBuffer(pcmFormat: format, frameCapacity: frameCount))
        buffer.frameLength = frameCount
        return buffer
    }

    // MARK: - prepare()

    @Test("prepare() propagates a backendFactory failure")
    func prepareBackendFactoryFailurePropagates() async {
        let pipeline = TranscriptPipeline(
            sessionHandle: makeSessionHandle(),
            backendFactory: { _, _ in throw FakeBackendFactoryError(message: "boom") }
        )

        await #expect(throws: FakeBackendFactoryError.self) {
            try await pipeline.prepare()
        }
    }

    // MARK: - Lifecycle safety without a successful prepare()

    @Test("stopAndDrain() without ever calling prepare() returns without hanging or crashing")
    func stopAndDrainWithoutPrepareIsSafe() async {
        let pipeline = TranscriptPipeline(
            sessionHandle: makeSessionHandle(),
            backendFactory: { _, _ in throw FakeBackendFactoryError(message: "should never be called") }
        )

        await pipeline.stopAndDrain()
    }

    @Test("stopAndDrain() after a failed prepare() returns without hanging or crashing")
    func stopAndDrainAfterFailedPrepareIsSafe() async {
        let pipeline = TranscriptPipeline(
            sessionHandle: makeSessionHandle(),
            backendFactory: { _, _ in throw FakeBackendFactoryError(message: "boom") }
        )

        await #expect(throws: FakeBackendFactoryError.self) {
            try await pipeline.prepare()
        }

        await pipeline.stopAndDrain()
    }

    @Test("AudioCaptureDelegate callbacks do not crash when the pipeline was never prepared")
    func delegateCallbacksAreSafeBeforePrepare() async throws {
        let pipeline = TranscriptPipeline(
            sessionHandle: makeSessionHandle(),
            backendFactory: { _, _ in throw FakeBackendFactoryError(message: "should never be called") }
        )
        // A real (but never `start()`-ed) `AudioCapture` instance, purely to satisfy the delegate
        // methods' `_ capture: AudioCapture` parameter -- none of the exercised callbacks actually
        // read from it.
        let dummyCapture = AudioCapture(sessionDirectory: makeTempSessionDirectory())
        let buffer = try makeMonoFloatBuffer()

        // `didCapture`/`didUpdateLevel`/`audioCaptureDidStop` only synchronously `yield`
        // (section 3.1) or are no-ops; `didDegrade` spawns a `Task { await engine.stop() }`. None of
        // these require `prepare()` to have succeeded first.
        pipeline.audioCapture(dummyCapture, didCapture: buffer, source: .mic, elapsed: 0)
        pipeline.audioCapture(dummyCapture, didUpdateLevel: 0.5, source: .mic)
        pipeline.audioCaptureDidStop(dummyCapture)

        await pipeline.stopAndDrain()
    }

    // MARK: - onSystemAudio forwarding (docs/design/13-speaker-diarization.md section 5)

    /// A `SttStreamingBackend` that never confirms anything -- `onSystemAudio` forwarding must not
    /// depend on `SttEngine` ever actually finalizing a segment (`TranscriptPipeline.onSystemAudio`'s
    /// doc comment: forwarded "right after they are fed to `systemEngine`", independent of STT output).
    private actor NoOpSttStreamingBackend: SttStreamingBackend {
        nonisolated let chunkSampleCount: Int

        init(chunkSampleCount: Int = 999_999) {
            self.chunkSampleCount = chunkSampleCount
        }

        func processChunk(_ samples: [Float]) async throws -> String { "" }
        func finish() async throws -> String { "" }
        func reset() async {}
    }

    private actor SampleRecorder {
        private(set) var forwarded: [[Float]] = []

        func record(_ samples: [Float]) {
            forwarded.append(samples)
        }
    }

    @Test("onSystemAudio is invoked with every system-source buffer's samples, in feed order, and never for mic")
    func onSystemAudioForwardsSystemSamplesOnlyInFeedOrder() async throws {
        let pipeline = TranscriptPipeline(
            sessionHandle: makeSessionHandle(),
            config: SttEngineConfig(twoPassDecode: false),
            backendFactory: { _, _ in NoOpSttStreamingBackend() }
        )
        try await pipeline.prepare()

        let recorder = SampleRecorder()
        pipeline.onSystemAudio = { samples in await recorder.record(samples) }

        let dummyCapture = AudioCapture(sessionDirectory: makeTempSessionDirectory())
        let micBuffer = try makeMonoFloatBuffer(frameCount: 10)
        let firstSystemBuffer = try makeMonoFloatBuffer(frameCount: 10)
        let secondSystemBuffer = try makeMonoFloatBuffer(frameCount: 20)

        pipeline.audioCapture(dummyCapture, didCapture: micBuffer, source: .mic, elapsed: 0)
        pipeline.audioCapture(dummyCapture, didCapture: firstSystemBuffer, source: .system, elapsed: 0)
        pipeline.audioCapture(dummyCapture, didCapture: secondSystemBuffer, source: .system, elapsed: 0.01)

        await pipeline.stopAndDrain()

        let forwarded = await recorder.forwarded
        #expect(forwarded.map(\.count) == [10, 20], "only system-source buffers must reach onSystemAudio, never mic, in feed order")
    }

    @Test("a nil onSystemAudio (the default, or diarization disabled) never crashes system-source feeding")
    func nilOnSystemAudioIsSafe() async throws {
        let pipeline = TranscriptPipeline(
            sessionHandle: makeSessionHandle(),
            config: SttEngineConfig(twoPassDecode: false),
            backendFactory: { _, _ in NoOpSttStreamingBackend() }
        )
        try await pipeline.prepare()

        let dummyCapture = AudioCapture(sessionDirectory: makeTempSessionDirectory())
        let systemBuffer = try makeMonoFloatBuffer(frameCount: 10)
        pipeline.audioCapture(dummyCapture, didCapture: systemBuffer, source: .system, elapsed: 0)

        await pipeline.stopAndDrain() // Must not hang or crash.
    }

    // MARK: - Regression: reabstraction-thunk wrapper-chain growth (meeting-end SIGSEGV, 2026-07-06)

    /// Guards against `onSystemAudioStorage`/`onDegradeStorage` regressing from a boxed
    /// (`SystemAudioHandlerBox?`/`DegradeHandlerBox?`) `OSAllocatedUnfairLock` `State` back to a bare
    /// closure `State`. Storing a function value directly as the lock's generic `State` makes every
    /// `withLock { $0 }` read re-abstract the closure through a reabstraction thunk and write the
    /// re-wrapped value back, so the stored closure grows one wrapper layer per read. In production
    /// this happened ~26 times/sec in the per-buffer `systemFeedTask` loop (`startForwarding()`); after
    /// a >30 min recording the chain exceeded 50k links and its recursive `deinit` overflowed the main
    /// thread's 8MB stack (SIGSEGV, ~160 bytes/frame => ~50k-frame threshold) once the pipeline was
    /// released at meeting end. 300,000 reads reproduce a chain roughly 6x deeper than the crashing
    /// production chains (52,214 layers) -- if boxing regresses, releasing `pipeline` below overflows
    /// the stack and crashes the test process; with boxing, each read only copies a class reference and
    /// no chain ever forms.
    @Test("300,000 onSystemAudio reads followed by pipeline deallocation do not overflow the stack")
    func onSystemAudioSurvivesManyReadsWithoutStackOverflowOnDeinit() async throws {
        var pipeline: TranscriptPipeline? = TranscriptPipeline(
            sessionHandle: makeSessionHandle(),
            config: SttEngineConfig(twoPassDecode: false),
            backendFactory: { _, _ in NoOpSttStreamingBackend() }
        )
        try await pipeline?.prepare()

        let recorder = SampleRecorder()
        pipeline?.onSystemAudio = { samples in await recorder.record(samples) }

        for _ in 0..<300_000 {
            _ = pipeline?.onSystemAudio
        }

        // The last handler read back must still be callable and behave identically to the one set
        // above -- boxing must not change `onSystemAudio`'s externally observable semantics.
        let handler = try #require(pipeline?.onSystemAudio)
        await handler([1, 2, 3])
        let forwarded = await recorder.forwarded
        #expect(forwarded == [[1, 2, 3]])

        await pipeline?.stopAndDrain()
        pipeline = nil // Would stack-overflow here if the fix regressed.
    }

    @Test("300,000 onDegrade reads followed by pipeline deallocation do not overflow the stack")
    func onDegradeSurvivesManyReadsWithoutStackOverflowOnDeinit() async throws {
        var pipeline: TranscriptPipeline? = TranscriptPipeline(
            sessionHandle: makeSessionHandle(),
            config: SttEngineConfig(twoPassDecode: false),
            backendFactory: { _, _ in NoOpSttStreamingBackend() }
        )
        try await pipeline?.prepare()

        pipeline?.onDegrade = { _, _ in }

        for _ in 0..<300_000 {
            _ = pipeline?.onDegrade
        }

        await pipeline?.stopAndDrain()
        pipeline = nil // Would stack-overflow here if the fix regressed.
    }
}
