import AVFoundation
import Foundation
import Testing

@testable import Kikimi

// MARK: - FakeIntegrationSttStreamingBackend

/// A trivial `SttStreamingBackend` for `TranscriptPipelineIntegrationTests`: returns the same
/// punctuation-terminated `finalizedText` from every `processChunk(_:)` call. Section 3.3's
/// punctuation route (route 1) therefore confirms exactly one segment the first time a full chunk is
/// decoded per source, then stays silent (the cumulative text never grows again, so
/// `SttEngine.computePendingText` keeps returning `""`) -- deterministic without needing to script a
/// response sequence keyed to how many real `AVAudioPCMBuffer`s happen to arrive.
private actor FakeIntegrationSttStreamingBackend: SttStreamingBackend {
    nonisolated let chunkSampleCount: Int
    private let finalizedText: String

    init(chunkSampleCount: Int, finalizedText: String) {
        self.chunkSampleCount = chunkSampleCount
        self.finalizedText = finalizedText
    }

    func processChunk(_ samples: [Float]) async throws -> String {
        finalizedText
    }

    func finish() async throws -> String {
        finalizedText
    }

    func reset() async {}
}

// MARK: - TranscriptPipelineIntegrationTests

/// End-to-end exercise of the streaming STT pipeline, wired to real production components except the
/// actual FluidAudio model call: real `TestFileAudioSource`-backed `AudioCapture`
/// (`docs/design/01-audio-capture.md` section 10/12's `KIKIMI_TEST_INPUT` seam) -> real
/// `TranscriptPipeline` -> two real `SttEngine` actors, each backed by a
/// `FakeIntegrationSttStreamingBackend` instead of `FluidAudioStreamingBackend` -> real
/// `SessionHandle` -> `transcript.jsonl` on disk. This is the "kikimi-verify via UI" substitute for
/// this module, mirroring `AudioCaptureIntegrationTests.swift`'s own precedent.
///
/// Replaces the previous sherpa-onnx-era `TranscriptPipelineIntegrationTests.swift`, which required a
/// pre-installed real model at `SttModelStore.defaultBaseDirectory` and skipped otherwise. That
/// approach is no longer appropriate now that the model is FluidAudio's ~1.5GB CoreML/Nemotron
/// download: `docs/design/11-streaming-stt.md` section 3.12 explicitly rules out
/// network-/real-model-dependent tests at this (layer 1) level ("ネットワーク・実モデルに依存するテストは書かない
/// （フェイク注入のみ）"). The equivalent real-model, real-transcript-content check (and the "volatile
/// テキストが表示されること" UI check) now lives in the `kikimi-verify` skill (section 3.12's layer 2).
@Suite("TranscriptPipeline integration (real AudioCapture + real SttEngine + fake SttStreamingBackend + real SessionHandle)")
struct TranscriptPipelineIntegrationTests {
    private let sampleRate: Double = 16_000

    /// Writes a short 16kHz mono sine wave to a temporary WAV file and returns its URL. Mirrors
    /// `AudioCaptureIntegrationTests.makeDummyWavFile(seconds:)`; duplicated rather than shared since
    /// each integration test file owns its own self-contained fixture setup (matching this repo's
    /// existing convention of not sharing `private` test helpers across files).
    private func makeDummyWavFile(seconds: Double) throws -> URL {
        let fileURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("TranscriptPipelineIntegrationTests-dummy-\(UUID().uuidString)")
            .appendingPathExtension("wav")

        let settings: [String: Any] = [
            AVFormatIDKey: kAudioFormatLinearPCM,
            AVSampleRateKey: sampleRate,
            AVNumberOfChannelsKey: 1,
            AVLinearPCMBitDepthKey: 16,
            AVLinearPCMIsFloatKey: false,
            AVLinearPCMIsBigEndianKey: false
        ]
        let file = try AVAudioFile(forWriting: fileURL, settings: settings)

        let format = try #require(AVAudioFormat(standardFormatWithSampleRate: sampleRate, channels: 1))
        let frameCount = AVAudioFrameCount(seconds * sampleRate)
        let buffer = try #require(AVAudioPCMBuffer(pcmFormat: format, frameCapacity: frameCount))
        buffer.frameLength = frameCount
        let samples = try #require(buffer.floatChannelData)[0]
        for frame in 0..<Int(frameCount) {
            samples[frame] = Float(sin(2.0 * Double.pi * 440.0 * Double(frame) / sampleRate)) * 0.1
        }
        try file.write(from: buffer)

        return fileURL
    }

    private func makeSessionDirectory() -> URL {
        FileManager.default.temporaryDirectory
            .appendingPathComponent("TranscriptPipelineIntegrationTests-session-\(UUID().uuidString)", isDirectory: true)
    }

    private func makeSessionHandle(directoryURL: URL) -> SessionHandle {
        let meta = SessionMeta(
            id: directoryURL.lastPathComponent,
            title: "STT Pipeline Integration Test",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(),
            startedAt: Date(),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
        return SessionHandle(directoryURL: directoryURL, meta: meta)
    }

    @Test(
        "prepare() -> AudioCapture.start() -> real buffer delivery through both sources -> AudioCapture.stop() -> stopAndDrain() produces transcript.jsonl segments for both mic and system"
    )
    func endToEndProducesTranscriptSegments() async throws {
        let dummyWav = try makeDummyWavFile(seconds: 1.5)
        defer { try? FileManager.default.removeItem(at: dummyWav) }

        let sessionDirectory = makeSessionDirectory()
        defer { try? FileManager.default.removeItem(at: sessionDirectory) }
        try FileManager.default.createDirectory(at: sessionDirectory, withIntermediateDirectories: true)

        let sessionHandle = makeSessionHandle(directoryURL: sessionDirectory)

        // Well below `AudioCaptureConfig.micTapBufferSize`'s default (1024), so a full fake chunk is
        // guaranteed to extract from the very first delivered buffer on both sources.
        let pipeline = TranscriptPipeline(
            sessionHandle: sessionHandle,
            // Two-pass off: this test exercises the streaming confirmation path end to end, not the
            // batch re-decode (`docs/design/33-meeting-two-pass-decode.md` is covered by
            // `TranscriptPipelineTests.swift`'s fake-decoder suite instead) -- leaving it on would
            // reach the real `BatchAsrDecoderPool`/FluidAudio network path (section 3.12 rules this
            // out at layer 1).
            config: SttEngineConfig(twoPassDecode: false),
            backendFactory: { _, _ in
                FakeIntegrationSttStreamingBackend(chunkSampleCount: 256, finalizedText: "テストです。")
            }
        )

        let config = AudioCaptureConfig(headerFlushInterval: 60)
        // `tickIntervalOverride` decouples delivery pacing from real (production) time -- unlike
        // `AudioCaptureIntegrationTests`, this test doesn't need real-time-paced delivery (it isn't
        // measuring host-time/elapsed pacing itself), so ticking as fast as the queue allows keeps
        // this test's wall-clock/CPU footprint small, which matters here specifically: a full
        // real-time-paced 500ms sleep was observed to add enough scheduling contention to
        // occasionally perturb unrelated timer-based tests (e.g. `PlainTextEditorTests`'s debounce
        // assertions) when the whole suite runs in parallel.
        let capture = AudioCapture(
            sessionDirectory: sessionDirectory,
            config: config,
            microphoneSource: TestFileAudioSource(fileURL: dummyWav, chunkFrameCount: config.micTapBufferSize, tickIntervalOverride: 0.005),
            systemAudioSource: TestFileAudioSource(fileURL: dummyWav, chunkFrameCount: config.micTapBufferSize, tickIntervalOverride: 0.005)
        )
        capture.delegate = pipeline

        // Section 9.2's call-order contract: prepare() (①②) before AudioCapture.start() (③).
        try await pipeline.prepare()
        try await capture.start()

        // Short but well above one accelerated tick interval on both sources -- only one full chunk
        // per source is ever needed to confirm a segment (see `FakeIntegrationSttStreamingBackend`'s
        // doc comment).
        try await Task.sleep(nanoseconds: 100_000_000)

        await capture.stop()
        await pipeline.stopAndDrain()

        let segments = try await sessionHandle.readTranscriptSegments()

        #expect(!segments.isEmpty)
        #expect(segments.contains { $0.speaker == .mic })
        #expect(segments.contains { $0.speaker == .system })

        for segment in segments {
            #expect(segment.startMs >= 0)
            #expect(segment.startMs <= segment.endMs)
            #expect(!segment.text.isEmpty)
            #expect(segment.confidence == 1.0)
        }

        // `id`s are assigned in append (call) order (kikimi.md 5章: "id は投入順に採番されるので、時系列とはズレる
        // 可能性がある"), which `readTranscriptSegments()` preserves as file order.
        let ids = segments.map(\.id)
        #expect(ids == ids.sorted())

        // What's on disk must match `meta.json`'s own in-memory bookkeeping (`07-session-store.md`'s
        // segmentCount invariant), same regression class `07-session-store.md`'s own layer-1 tests
        // guard.
        let meta = await sessionHandle.meta
        #expect(meta.segmentCount == segments.count)
    }
}
