import Foundation
import OSLog
import Testing

@testable import Kikimi

/// Unit tests for `TranscriptPipeline.liveSegments` and its backing `appendOrLog(_:source:to:logger:liveSegmentsContinuation:)`
/// (`docs/design/06-ui-panels.md` section 6.3). `TranscriptPipeline` has no injectable fake `SttEngine`
/// seam (see `TranscriptPipelineTests.swift`'s doc comment), so this file cannot drive a real segment
/// through `SttEngine.confirmedWindows` end-to-end without a real sherpa-onnx model. Instead it targets
/// `appendOrLog` directly — the exact unit section 6.3 describes ("追記が実際に成功した... セグメントのみを...
/// 追記成功の直後に yield する") — against a real `SessionHandle` and a test-owned
/// `AsyncStream<TranscriptSegment>.Continuation`, plus one lifecycle test that exercises the public
/// `liveSegments` property itself through `stopAndDrain()`.
@Suite("TranscriptPipeline.liveSegments")
struct TranscriptPipelineLiveSegmentsTests {
    private let logger = Logger(subsystem: "io.github.uphy.Kikimi", category: "TranscriptPipelineLiveSegmentsTests")

    private func makeTempSessionDirectory() -> URL {
        FileManager.default.temporaryDirectory
            .appendingPathComponent("TranscriptPipelineLiveSegmentsTests-\(UUID().uuidString)", isDirectory: true)
    }

    /// - Parameter createDirectory: When `false`, the session directory is never created on disk, so
    ///   `SessionHandle.appendTranscriptSegment` is guaranteed to fail (`AppendOnlyLogFile.init`'s
    ///   `FileManager.default.createFile` call fails when its parent directory does not exist) --
    ///   this is how the "failed append" side of `appendOrLog` is exercised below, without needing to
    ///   fake `SessionHandle` itself.
    private func makeSessionHandle(createDirectory: Bool = true) -> SessionHandle {
        let directoryURL = makeTempSessionDirectory()
        if createDirectory {
            try? FileManager.default.createDirectory(at: directoryURL, withIntermediateDirectories: true)
        }
        let meta = SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: "Test Session",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_010),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
        return SessionHandle(directoryURL: directoryURL, meta: meta)
    }

    private func makeFinalizedSegment(
        startMs: Int = 1_000,
        endMs: Int = 2_000,
        text: String = "hello",
        confidence: Double = 0.9
    ) -> SttFinalizedSegment {
        SttFinalizedSegment(startMs: startMs, endMs: endMs, text: text, confidence: confidence)
    }

    // MARK: - appendOrLog

    @Test("appendOrLog yields the id-assigned segment once the transcript.jsonl append actually succeeds")
    func appendOrLogYieldsOnSuccessfulAppend() async throws {
        let sessionHandle = makeSessionHandle()
        let (stream, continuation) = AsyncStream<TranscriptSegment>.makeStream()
        let finalized = makeFinalizedSegment()

        await TranscriptPipeline.appendOrLog(
            finalized,
            source: .mic,
            to: sessionHandle,
            logger: logger,
            liveSegmentsContinuation: continuation
        )
        continuation.finish()

        var received: [TranscriptSegment] = []
        for await segment in stream {
            received.append(segment)
        }

        #expect(received.count == 1)
        #expect(received.first?.id == "seg_00001")
        #expect(received.first?.startMs == finalized.startMs)
        #expect(received.first?.endMs == finalized.endMs)
        #expect(received.first?.speaker == .mic)
        #expect(received.first?.text == finalized.text)
        #expect(received.first?.confidence == finalized.confidence)

        // The yielded segment must match what actually landed in transcript.jsonl, not just what was
        // attempted (kikimi.md 8.5章 "リアルタイム表示は生 JSONL の内容で行われる").
        let persisted = try await sessionHandle.readTranscriptSegments()
        #expect(persisted == received)
    }

    @Test("appendOrLog passes sttSource through to the persisted/yielded segment (design 33 MT9)")
    func appendOrLogPassesThroughSttSource() async throws {
        let sessionHandle = makeSessionHandle()
        let (stream, continuation) = AsyncStream<TranscriptSegment>.makeStream()
        let finalized = makeFinalizedSegment()

        await TranscriptPipeline.appendOrLog(
            finalized,
            source: .mic,
            to: sessionHandle,
            logger: logger,
            liveSegmentsContinuation: continuation,
            sttSource: "batch"
        )
        continuation.finish()

        var received: [TranscriptSegment] = []
        for await segment in stream {
            received.append(segment)
        }

        #expect(received.first?.sttSource == "batch")
        let persisted = try await sessionHandle.readTranscriptSegments()
        #expect(persisted.first?.sttSource == "batch")
    }

    @Test("appendOrLog defaults sttSource to nil (fallback / two-pass off, design 33 MT9)")
    func appendOrLogDefaultsSttSourceToNil() async throws {
        let sessionHandle = makeSessionHandle()
        let (stream, continuation) = AsyncStream<TranscriptSegment>.makeStream()
        let finalized = makeFinalizedSegment()

        await TranscriptPipeline.appendOrLog(
            finalized,
            source: .mic,
            to: sessionHandle,
            logger: logger,
            liveSegmentsContinuation: continuation
        )
        continuation.finish()

        var received: [TranscriptSegment] = []
        for await segment in stream {
            received.append(segment)
        }

        #expect(received.first?.sttSource == nil)
    }

    @Test("appendOrLog yields nothing when the transcript.jsonl append fails")
    func appendOrLogDoesNotYieldOnFailedAppend() async {
        // `createDirectory: false` guarantees `appendTranscriptSegment` throws (see helper doc comment).
        let sessionHandle = makeSessionHandle(createDirectory: false)
        let (stream, continuation) = AsyncStream<TranscriptSegment>.makeStream()
        let finalized = makeFinalizedSegment()

        await TranscriptPipeline.appendOrLog(
            finalized,
            source: .system,
            to: sessionHandle,
            logger: logger,
            liveSegmentsContinuation: continuation
        )
        continuation.finish()

        var received: [TranscriptSegment] = []
        for await segment in stream {
            received.append(segment)
        }

        #expect(received.isEmpty)
    }

    @Test("appendOrLog adds startMsOffset to the persisted/yielded startMs/endMs (kikimi.md 5/6 章 cumulative timeline)")
    func appendOrLogAppliesStartMsOffset() async throws {
        let sessionHandle = makeSessionHandle()
        let (stream, continuation) = AsyncStream<TranscriptSegment>.makeStream()
        // Relative to this (second) recording segment's own AudioCapture.start(); the offset
        // (kikimi.md 6 章's `start_ms_offset`, equal to the first segment's total length) must be
        // added before the segment lands on transcript.jsonl's shared cumulative timeline.
        let finalized = makeFinalizedSegment(startMs: 500, endMs: 1_500)

        await TranscriptPipeline.appendOrLog(
            finalized,
            source: .mic,
            startMsOffset: 1_330_000,
            to: sessionHandle,
            logger: logger,
            liveSegmentsContinuation: continuation
        )
        continuation.finish()

        var received: [TranscriptSegment] = []
        for await segment in stream {
            received.append(segment)
        }

        #expect(received.count == 1)
        #expect(received.first?.startMs == 1_330_500)
        #expect(received.first?.endMs == 1_331_500)

        let persisted = try await sessionHandle.readTranscriptSegments()
        #expect(persisted == received)
    }

    @Test("appendOrLog defaults startMsOffset to 0, matching a session's first recording segment")
    func appendOrLogDefaultsStartMsOffsetToZero() async throws {
        let sessionHandle = makeSessionHandle()
        let (stream, continuation) = AsyncStream<TranscriptSegment>.makeStream()
        let finalized = makeFinalizedSegment(startMs: 500, endMs: 1_500)

        await TranscriptPipeline.appendOrLog(
            finalized,
            source: .mic,
            to: sessionHandle,
            logger: logger,
            liveSegmentsContinuation: continuation
        )
        continuation.finish()

        var received: [TranscriptSegment] = []
        for await segment in stream {
            received.append(segment)
        }

        #expect(received.first?.startMs == 500)
        #expect(received.first?.endMs == 1_500)
    }

    @Test("appendOrLog yields segments in call order across multiple successful appends")
    func appendOrLogYieldsInCallOrder() async throws {
        let sessionHandle = makeSessionHandle()
        let (stream, continuation) = AsyncStream<TranscriptSegment>.makeStream()

        await TranscriptPipeline.appendOrLog(
            makeFinalizedSegment(startMs: 0, endMs: 1_000, text: "first"),
            source: .mic,
            to: sessionHandle,
            logger: logger,
            liveSegmentsContinuation: continuation
        )
        await TranscriptPipeline.appendOrLog(
            makeFinalizedSegment(startMs: 1_000, endMs: 2_000, text: "second"),
            source: .system,
            to: sessionHandle,
            logger: logger,
            liveSegmentsContinuation: continuation
        )
        continuation.finish()

        var received: [TranscriptSegment] = []
        for await segment in stream {
            received.append(segment)
        }

        #expect(received.map(\.id) == ["seg_00001", "seg_00002"])
        #expect(received.map(\.text) == ["first", "second"])
    }

    // MARK: - liveSegments lifecycle (via stopAndDrain())

    @Test("liveSegments terminates cleanly once stopAndDrain() completes, even without a successful prepare()")
    func liveSegmentsFinishesAfterStopAndDrainWithoutPrepare() async {
        let pipeline = TranscriptPipeline(sessionHandle: makeSessionHandle())

        // `prepare()` is never called, so `startForwarding()` never runs and nothing will ever be
        // yielded -- this only asserts that consuming `liveSegments` doesn't hang forever, mirroring
        // `TranscriptPipelineTests.swift`'s "stopAndDrain() without ever calling prepare() returns
        // without hanging or crashing" lifecycle-safety test, applied to this new stream.
        let collectTask = Task {
            var count = 0
            for await _ in pipeline.liveSegments {
                count += 1
            }
            return count
        }

        await pipeline.stopAndDrain()

        let count = await collectTask.value
        #expect(count == 0)
    }
}
