import Foundation
import Testing

@testable import Kikimi

/// Layer 1 (unit) coverage for `WikiExportRenderer` (`docs/design/08-wiki-export.md` §4/§8), the pure
/// rendering half of the Wiki raw export feature. Every test constructs plain values directly --
/// never a `SessionHandle`/`AppConfig` -- since `WikiExporter` (tested separately, `WikiExporterTests
/// .swift`) owns all the I/O this type deliberately has none of.
///
/// Every `Date` fixture is built from `DateComponents` against `Calendar.current`/`TimeZone.current`
/// (via `date(...)` below), matching `WikiExportRenderer`'s own `.current`-timezone formatters, so
/// assertions never depend on which timezone actually runs the test.
@Suite("WikiExportRenderer")
struct WikiExportRendererTests {
    /// `static` (not an instance method) so it can also be used directly in another helper's default
    /// argument expressions (`makeMeta(...)`'s `createdAt`/`startedAt` defaults below), which run in a
    /// context with no `self`.
    private static func date(year: Int, month: Int, day: Int, hour: Int, minute: Int, second: Int) -> Date {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = .current
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = day
        components.hour = hour
        components.minute = minute
        components.second = second
        return calendar.date(from: components)!
    }

    /// - Parameter startedAt: Passed straight through to `SessionMeta.startedAt` with **no**
    ///   `?? fallback` substitution -- its default argument value is already the sensible non-nil
    ///   date most tests want, so a test that instead needs `meta.startedAt == nil` (to exercise the
    ///   "no startedAt yet" fallback-to-`createdAt` path,
    ///   `fileNameFallsBackToCreatedAtWhenStartedAtIsNil` below) can pass `startedAt: nil` explicitly
    ///   and have it actually land on the constructed `SessionMeta` as `nil`.
    private func makeMeta(
        id: String = "2026-07-01T14-30-00_a1b2c3d4",
        title: String = "デイリースクラム",
        createdAt: Date = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 28, second: 12),
        startedAt: Date? = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0),
        durationMs: Int = 2_722_000,
        recordings: [RecordingSegment] = []
    ) -> SessionMeta {
        SessionMeta(
            id: id,
            title: title,
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .ended,
            createdAt: createdAt,
            startedAt: startedAt,
            endedAt: Self.date(year: 2_026, month: 7, day: 1, hour: 15, minute: 15, second: 22),
            durationMs: durationMs,
            recordings: recordings,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func makeRefinedSegment(
        id: String,
        startMs: Int,
        speaker: AudioSourceKind = .mic,
        rawText: String = "raw",
        refinedText: String?
    ) -> RefinedSegment {
        RefinedSegment(
            id: id,
            startMs: startMs,
            endMs: startMs + 500,
            speaker: speaker,
            rawText: rawText,
            refinedText: refinedText,
            error: refinedText == nil ? "missing from LLM response" : nil,
            refinedAt: Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 32, second: 15),
            model: "claude-haiku-4-5-20251001",
            batchId: "batch_00001"
        )
    }

    // MARK: - slug(from:)

    @Test("slug(from:) keeps a plain Japanese title unchanged")
    func slugKeepsJapaneseTitleUnchanged() {
        #expect(WikiExportRenderer.slug(from: "デイリースクラム") == "デイリースクラム")
    }

    @Test("slug(from:) replaces filesystem-unsafe characters and whitespace with hyphens, collapsing runs")
    func slugReplacesUnsafeCharactersAndCollapsesRuns() {
        #expect(WikiExportRenderer.slug(from: "顧客A / 打ち合わせ: 議事録?") == "顧客A-打ち合わせ-議事録")
    }

    @Test("slug(from:) collapses whitespace runs and existing double hyphens alike")
    func slugCollapsesWhitespaceAndExistingHyphens() {
        #expect(WikiExportRenderer.slug(from: "foo   bar--baz") == "foo-bar-baz")
    }

    @Test("slug(from:) trims leading/trailing hyphens produced by leading/trailing unsafe characters")
    func slugTrimsLeadingTrailingHyphens() {
        #expect(WikiExportRenderer.slug(from: "  /タイトル/  ") == "タイトル")
    }

    @Test("slug(from:) falls back to \"untitled\" for an empty title")
    func slugFallsBackToUntitledForEmptyTitle() {
        #expect(WikiExportRenderer.slug(from: "") == "untitled")
    }

    @Test("slug(from:) falls back to \"untitled\" for a title made entirely of unsafe/whitespace characters")
    func slugFallsBackToUntitledForAllUnsafeTitle() {
        #expect(WikiExportRenderer.slug(from: "   ///:::   ") == "untitled")
    }

    @Test("slug(from:) truncates to 80 characters")
    func slugTruncatesToEightyCharacters() {
        let longTitle = String(repeating: "あ", count: 200)
        let slug = WikiExportRenderer.slug(from: longTitle)
        #expect(slug.count == 80)
        #expect(slug == String(repeating: "あ", count: 80))
    }

    // MARK: - fileName(for:)

    @Test("fileName(for:) combines the startedAt date with the title slug")
    func fileNameCombinesDateAndSlug() {
        let meta = makeMeta(title: "デイリースクラム")
        #expect(WikiExportRenderer.fileName(for: meta) == "2026-07-01-デイリースクラム.md")
    }

    @Test("fileName(for:) falls back to createdAt's date when startedAt is nil")
    func fileNameFallsBackToCreatedAtWhenStartedAtIsNil() {
        let created = Self.date(year: 2_026, month: 8, day: 15, hour: 9, minute: 0, second: 0)
        let meta = makeMeta(title: "無題", createdAt: created, startedAt: nil)
        #expect(WikiExportRenderer.fileName(for: meta) == "2026-08-15-無題.md")
    }

    // MARK: - displayText(for:)

    @Test("displayText(for:) returns refinedText as-is when non-nil and non-empty")
    func displayTextReturnsRefinedTextAsIs() {
        let segment = makeRefinedSegment(id: "seg_00001", startMs: 0, refinedText: "整形済みテキスト")
        #expect(WikiExportRenderer.displayText(for: segment) == "整形済みテキスト")
    }

    @Test("displayText(for:) falls back to rawText + the raw-fallback marker when refinedText is nil")
    func displayTextFallsBackToRawTextWithMarkerWhenRefinedTextIsNil() {
        let segment = makeRefinedSegment(id: "seg_00001", startMs: 0, rawText: "生テキスト", refinedText: nil)
        #expect(WikiExportRenderer.displayText(for: segment) == "生テキスト" + WikiExportRenderer.rawFallbackMarker)
    }

    @Test("displayText(for:) excludes the line entirely (nil) when refinedText is an empty string")
    func displayTextExcludesEmptyRefinedText() {
        let segment = makeRefinedSegment(id: "seg_00001", startMs: 0, refinedText: "")
        #expect(WikiExportRenderer.displayText(for: segment) == nil)
    }

    // MARK: - wallClockDate(startMs:recordings:fallback:)

    @Test("wallClockDate resolves a single-segment session's startMs directly against its startedAt")
    func wallClockDateSingleSegment() {
        let started = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let recordings = [RecordingSegment(index: 0, startedAt: started, endedAt: nil, startMsOffset: 0)]
        let result = WikiExportRenderer.wallClockDate(startMs: 5_000, recordings: recordings, fallback: started)
        #expect(result == started.addingTimeInterval(5))
    }

    @Test("wallClockDate resolves a startMs in the second of two recording segments (a pause/resume gap)")
    func wallClockDateAcrossTwoSegments() {
        let firstStart = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let secondStart = Self.date(year: 2_026, month: 7, day: 1, hour: 15, minute: 5, second: 30)
        let recordings = [
            RecordingSegment(index: 0, startedAt: firstStart, endedAt: firstStart.addingTimeInterval(1_330), startMsOffset: 0),
            RecordingSegment(index: 1, startedAt: secondStart, endedAt: nil, startMsOffset: 1_330_000),
        ]
        // 10 seconds into the second segment.
        let result = WikiExportRenderer.wallClockDate(startMs: 1_340_000, recordings: recordings, fallback: firstStart)
        #expect(result == secondStart.addingTimeInterval(10))
    }

    @Test("wallClockDate at exactly a segment boundary offset resolves to that segment's startedAt")
    func wallClockDateAtExactSegmentBoundary() {
        let firstStart = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let secondStart = Self.date(year: 2_026, month: 7, day: 1, hour: 15, minute: 5, second: 30)
        let recordings = [
            RecordingSegment(index: 0, startedAt: firstStart, endedAt: firstStart.addingTimeInterval(1_330), startMsOffset: 0),
            RecordingSegment(index: 1, startedAt: secondStart, endedAt: nil, startMsOffset: 1_330_000),
        ]
        let result = WikiExportRenderer.wallClockDate(startMs: 1_330_000, recordings: recordings, fallback: firstStart)
        #expect(result == secondStart)
    }

    @Test("wallClockDate falls back to fallback + startMs when recordings is empty")
    func wallClockDateFallsBackWhenRecordingsIsEmpty() {
        let fallback = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let result = WikiExportRenderer.wallClockDate(startMs: 2_500, recordings: [], fallback: fallback)
        #expect(result == fallback.addingTimeInterval(2.5))
    }

    // MARK: - durationLabel(durationMs:)

    @Test("durationLabel rounds to the nearest whole minute")
    func durationLabelRoundsToNearestMinute() {
        #expect(WikiExportRenderer.durationLabel(durationMs: 2_722_000) == "45m")
        #expect(WikiExportRenderer.durationLabel(durationMs: 90_000) == "2m") // 1.5min rounds up
        #expect(WikiExportRenderer.durationLabel(durationMs: 89_000) == "1m") // 1.483min rounds down
        #expect(WikiExportRenderer.durationLabel(durationMs: 0) == "0m")
    }

    // MARK: - render(_:)

    @Test("render(_:) produces kikimi.md 11 章's documented shape end-to-end")
    func renderProducesDocumentedShape() {
        let started = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let recordings = [RecordingSegment(index: 0, startedAt: started, endedAt: nil, startMsOffset: 0)]
        let meta = makeMeta(title: "デイリースクラム", durationMs: 2_722_000, recordings: recordings)

        let segments = [
            makeRefinedSegment(id: "seg_00001", startMs: 5_000, speaker: .mic, rawText: "raw1", refinedText: "次のスプリントで対応します。"),
            makeRefinedSegment(id: "seg_00002", startMs: 8_000, speaker: .system, rawText: "raw2", refinedText: "了解しました。"),
            // Refinement failed -- falls back to raw with the traceability marker.
            makeRefinedSegment(id: "seg_00003", startMs: 12_000, speaker: .mic, rawText: "raw fallback text", refinedText: nil),
            // Intentionally deleted (filler-only) -- must not appear in the output at all.
            makeRefinedSegment(id: "seg_00004", startMs: 15_000, speaker: .system, rawText: "えーと", refinedText: ""),
        ]

        let markdown = WikiExportRenderer.render(
            WikiExportRenderer.Input(meta: meta, summaryMarkdown: "## 概要\n\n会議の概要です。", refinedSegments: segments)
        )

        let expected = """
        ---
        date: 2026-07-01
        duration: 45m
        source: kikimi
        session_id: 2026-07-01T14-30-00_a1b2c3d4
        tags: [meeting, transcript]
        ---

        # デイリースクラム

        ## サマリ

        ## 概要

        会議の概要です。

        ## 書き起こし

        **14:30:05 (mic)** 次のスプリントで対応します。

        **14:30:08 (system)** 了解しました。

        **14:30:12 (mic)** raw fallback text\(WikiExportRenderer.rawFallbackMarker)

        """
        #expect(markdown == expected)
    }

    @Test("render(_:) omits the transcript section content entirely when every segment was refined away")
    func renderOmitsTranscriptWhenEveryLineIsExcluded() {
        let meta = makeMeta(title: "空の会議")
        let segments = [makeRefinedSegment(id: "seg_00001", startMs: 0, refinedText: "")]

        let markdown = WikiExportRenderer.render(
            WikiExportRenderer.Input(meta: meta, summaryMarkdown: "", refinedSegments: segments)
        )

        #expect(markdown.hasSuffix("## 書き起こし\n\n"))
    }
}
