import Foundation
import Testing

@testable import Kikimi

/// Layer 1 (unit) coverage for `WikiExporter` (`docs/design/08-wiki-export.md` §3/§6/§8), the I/O
/// half of the Wiki raw export feature. Every test roots `ExportConfig.targetDir` at a fresh
/// temporary directory (an absolute path, so `FileManager.expandingTildePath(_:)` passes it through
/// unchanged) so nothing here ever touches the real `~/Documents/Kikimi/export/`.
@Suite("WikiExporter")
struct WikiExporterTests {
    private func makeTemporaryDirectory(prefix: String = "WikiExporterTests") -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(prefix)-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func makeExportConfig(targetDir: URL, enabled: Bool = true) -> ExportConfig {
        ExportConfig(enabled: enabled, targetDir: targetDir.path)
    }

    private func makeSessionHandle(directory: URL, title: String = "デイリースクラム") -> SessionHandle {
        let meta = SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: title,
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .ended,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_100),
            endedAt: Date(timeIntervalSince1970: 1_751_002_822),
            durationMs: 2_722_000,
            recordings: [
                RecordingSegment(
                    index: 0,
                    startedAt: Date(timeIntervalSince1970: 1_751_000_100),
                    endedAt: Date(timeIntervalSince1970: 1_751_002_822),
                    startMsOffset: 0
                ),
            ],
            basedOnSession: nil,
            segmentCount: 1,
            refinedCount: 1,
            appVersion: "0.1.0"
        )
        return SessionHandle(directoryURL: directory, meta: meta)
    }

    // MARK: - enabled == false

    @Test("export(sessionHandle:) does nothing when ExportConfig.enabled == false")
    func exportDoesNothingWhenDisabled() async throws {
        let targetDir = makeTemporaryDirectory(prefix: "WikiExporterTests-target")
        defer { try? FileManager.default.removeItem(at: targetDir) }
        let sessionDir = makeTemporaryDirectory(prefix: "WikiExporterTests-session")
        defer { try? FileManager.default.removeItem(at: sessionDir) }

        let config = makeExportConfig(targetDir: targetDir, enabled: false)
        let handle = makeSessionHandle(directory: sessionDir)
        let exporter = WikiExporter(config: config)

        try await exporter.export(sessionHandle: handle)

        let entries = try FileManager.default.contentsOfDirectory(atPath: targetDir.path)
        #expect(entries.isEmpty)
    }

    // MARK: - writes the file

    @Test("export(sessionHandle:) writes a Markdown file named per WikiExportRenderer.fileName(for:)")
    func exportWritesFileWithExpectedName() async throws {
        let targetDir = makeTemporaryDirectory(prefix: "WikiExporterTests-target")
        defer { try? FileManager.default.removeItem(at: targetDir) }
        let sessionDir = makeTemporaryDirectory(prefix: "WikiExporterTests-session")
        defer { try? FileManager.default.removeItem(at: sessionDir) }

        let config = makeExportConfig(targetDir: targetDir)
        let handle = makeSessionHandle(directory: sessionDir, title: "デイリースクラム")
        try await handle.appendRefinedSegment(
            RefinedSegment(
                id: "seg_00001",
                startMs: 5_000,
                endMs: 5_500,
                speaker: .mic,
                rawText: "raw",
                refinedText: "次のスプリントで対応します。",
                error: nil,
                refinedAt: Date(timeIntervalSince1970: 1_751_000_200),
                model: "claude-haiku-4-5-20251001",
                batchId: "batch_00001"
            )
        )
        try await handle.writeText("# デイリースクラム\n\n## 概要\n\n...", to: .summaryMarkdown)

        let exporter = WikiExporter(config: config)
        try await exporter.export(sessionHandle: handle)

        let meta = await handle.meta
        let expectedFileName = WikiExportRenderer.fileName(for: meta)
        let expectedURL = targetDir.appendingPathComponent(expectedFileName)
        #expect(FileManager.default.fileExists(atPath: expectedURL.path))

        let written = try String(contentsOf: expectedURL, encoding: .utf8)
        #expect(written.contains("session_id: 2026-07-01T14-30-00_a1b2c3d4"))
        #expect(written.contains("# デイリースクラム"))
        #expect(written.contains("次のスプリントで対応します。"))
    }

    @Test("export(sessionHandle:) exports with an empty summary section when summary.md doesn't exist yet")
    func exportWithMissingSummaryMarkdown() async throws {
        let targetDir = makeTemporaryDirectory(prefix: "WikiExporterTests-target")
        defer { try? FileManager.default.removeItem(at: targetDir) }
        let sessionDir = makeTemporaryDirectory(prefix: "WikiExporterTests-session")
        defer { try? FileManager.default.removeItem(at: sessionDir) }

        let config = makeExportConfig(targetDir: targetDir)
        let handle = makeSessionHandle(directory: sessionDir)

        let exporter = WikiExporter(config: config)
        try await exporter.export(sessionHandle: handle) // must not throw despite no summary.md

        let meta = await handle.meta
        let expectedURL = targetDir.appendingPathComponent(WikiExportRenderer.fileName(for: meta))
        #expect(FileManager.default.fileExists(atPath: expectedURL.path))
    }

    @Test("export(sessionHandle:) overwrites an existing export file idempotently")
    func exportOverwritesExistingFile() async throws {
        let targetDir = makeTemporaryDirectory(prefix: "WikiExporterTests-target")
        defer { try? FileManager.default.removeItem(at: targetDir) }
        let sessionDir = makeTemporaryDirectory(prefix: "WikiExporterTests-session")
        defer { try? FileManager.default.removeItem(at: sessionDir) }

        let config = makeExportConfig(targetDir: targetDir)
        let handle = makeSessionHandle(directory: sessionDir)
        let exporter = WikiExporter(config: config)

        try await exporter.export(sessionHandle: handle)
        try await handle.writeText("# デイリースクラム\n\n## 概要\n\n更新後の概要", to: .summaryMarkdown)
        try await exporter.export(sessionHandle: handle)

        let meta = await handle.meta
        let expectedURL = targetDir.appendingPathComponent(WikiExportRenderer.fileName(for: meta))
        let entries = try FileManager.default.contentsOfDirectory(atPath: targetDir.path)
        #expect(entries.count == 1, "a re-export of the same session must overwrite, not duplicate, the file")

        let written = try String(contentsOf: expectedURL, encoding: .utf8)
        #expect(written.contains("更新後の概要"))
    }
}
