import Foundation
import Testing

@testable import Kikimi

/// Layer 1 (unit) coverage for `WikiExportRenderer` (`docs/design/08-wiki-export.md` §4/§8,
/// `docs/design/37-transcript-markdown-copy.md` TC1), which now only generates the export file
/// name/slug -- `render(_:)`/`Input`/`displayText(for:)`/`wallClockDate`/`durationLabel` moved to
/// `TranscriptMarkdownRenderer` (design §3.1's migration table): `wallClockDate`/`durationLabel`/
/// `render(_:)` end-to-end now live in `KikimiTests/Markdown/TranscriptMarkdownRendererTests.swift`
/// (expected values updated for design §4), and `displayText(for:)`'s coverage moves to
/// `TranscriptMarkdownSourceTests` (the disk adapter that now owns that branching). Every test here
/// constructs plain values directly -- never a `SessionHandle`/`AppConfig` -- since `WikiExporter`
/// (tested separately, `WikiExporterTests.swift`) owns all the I/O this type deliberately has none of.
///
/// Every `Date` fixture is built from `DateComponents` against `Calendar.current`/`TimeZone.current`
/// (via `date(...)` below), matching `WikiExportRenderer`'s own `.current`-timezone formatter, so
/// assertions never depend on which timezone actually runs the test.
@Suite("WikiExportRenderer")
struct WikiExportRendererTests {
    /// `static` (not an instance method) so it can also be used directly in another helper's default
    /// argument expressions (`makeMeta(...)`'s `createdAt`/`startedAt` defaults below), which run in a
    /// context with no `self`.
    private static func date(year: Int, month: Int, day: Int, hour: Int, minute: Int, second: Int) -> Date {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = .current
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = day
        components.hour = hour
        components.minute = minute
        components.second = second
        return calendar.date(from: components)!
    }

    /// - Parameter startedAt: Passed straight through to `SessionMeta.startedAt` with **no**
    ///   `?? fallback` substitution -- its default argument value is already the sensible non-nil
    ///   date most tests want, so a test that instead needs `meta.startedAt == nil` (to exercise the
    ///   "no startedAt yet" fallback-to-`createdAt` path,
    ///   `fileNameFallsBackToCreatedAtWhenStartedAtIsNil` below) can pass `startedAt: nil` explicitly
    ///   and have it actually land on the constructed `SessionMeta` as `nil`.
    private func makeMeta(
        id: String = "2026-07-01T14-30-00_a1b2c3d4",
        title: String = "デイリースクラム",
        createdAt: Date = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 28, second: 12),
        startedAt: Date? = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0),
        durationMs: Int = 2_722_000,
        recordings: [RecordingSegment] = []
    ) -> SessionMeta {
        SessionMeta(
            id: id,
            title: title,
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .ended,
            createdAt: createdAt,
            startedAt: startedAt,
            endedAt: Self.date(year: 2_026, month: 7, day: 1, hour: 15, minute: 15, second: 22),
            durationMs: durationMs,
            recordings: recordings,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    // MARK: - slug(from:)

    @Test("slug(from:) keeps a plain Japanese title unchanged")
    func slugKeepsJapaneseTitleUnchanged() {
        #expect(WikiExportRenderer.slug(from: "デイリースクラム") == "デイリースクラム")
    }

    @Test("slug(from:) replaces filesystem-unsafe characters and whitespace with hyphens, collapsing runs")
    func slugReplacesUnsafeCharactersAndCollapsesRuns() {
        #expect(WikiExportRenderer.slug(from: "顧客A / 打ち合わせ: 議事録?") == "顧客A-打ち合わせ-議事録")
    }

    @Test("slug(from:) collapses whitespace runs and existing double hyphens alike")
    func slugCollapsesWhitespaceAndExistingHyphens() {
        #expect(WikiExportRenderer.slug(from: "foo   bar--baz") == "foo-bar-baz")
    }

    @Test("slug(from:) trims leading/trailing hyphens produced by leading/trailing unsafe characters")
    func slugTrimsLeadingTrailingHyphens() {
        #expect(WikiExportRenderer.slug(from: "  /タイトル/  ") == "タイトル")
    }

    @Test("slug(from:) falls back to \"untitled\" for an empty title")
    func slugFallsBackToUntitledForEmptyTitle() {
        #expect(WikiExportRenderer.slug(from: "") == "untitled")
    }

    @Test("slug(from:) falls back to \"untitled\" for a title made entirely of unsafe/whitespace characters")
    func slugFallsBackToUntitledForAllUnsafeTitle() {
        #expect(WikiExportRenderer.slug(from: "   ///:::   ") == "untitled")
    }

    @Test("slug(from:) truncates to 80 characters")
    func slugTruncatesToEightyCharacters() {
        let longTitle = String(repeating: "あ", count: 200)
        let slug = WikiExportRenderer.slug(from: longTitle)
        #expect(slug.count == 80)
        #expect(slug == String(repeating: "あ", count: 80))
    }

    @Test("slug(from:) leaves an exactly-80-character title untouched (no truncation at the boundary)")
    func slugLeavesEightyCharacterTitleUntouched() {
        let title = String(repeating: "あ", count: 80)
        #expect(WikiExportRenderer.slug(from: title) == title)
    }

    @Test("slug(from:) replaces every filesystem-unsafe character in the design-doc list (§4.4), not just a subset")
    func slugReplacesEveryUnsafeCharacterInTheDesignDocList() {
        // Design doc §4.4 unsafe set: / \ : * ? " < > |. The existing
        // "replacesUnsafeCharactersAndCollapsesRuns" test only exercises "/", ":", "?"; this one covers the
        // remaining "\", "*", "\"", "<", ">", "|" so every character in the documented set has a direct test.
        #expect(WikiExportRenderer.slug(from: "a\\b*c\"d<e>f|g") == "a-b-c-d-e-f-g")
    }

    @Test("slug(from:) treats tabs and newlines the same as spaces (CharacterSet.whitespacesAndNewlines, not just \" \")")
    func slugTreatsTabsAndNewlinesAsWhitespace() {
        #expect(WikiExportRenderer.slug(from: "foo\tbar\nbaz") == "foo-bar-baz")
    }

    // MARK: - fileName(for:)

    @Test("fileName(for:) combines the startedAt date with the title slug")
    func fileNameCombinesDateAndSlug() {
        let meta = makeMeta(title: "デイリースクラム")
        #expect(WikiExportRenderer.fileName(for: meta) == "2026-07-01-デイリースクラム.md")
    }

    @Test("fileName(for:) falls back to createdAt's date when startedAt is nil")
    func fileNameFallsBackToCreatedAtWhenStartedAtIsNil() {
        let created = Self.date(year: 2_026, month: 8, day: 15, hour: 9, minute: 0, second: 0)
        let meta = makeMeta(title: "無題", createdAt: created, startedAt: nil)
        #expect(WikiExportRenderer.fileName(for: meta) == "2026-08-15-無題.md")
    }

    @Test("fileName(for:) applies slug(from:)'s unsafe-character replacement to the title, not just plain titles")
    func fileNameAppliesSlugUnsafeCharacterReplacement() {
        let meta = makeMeta(title: "顧客A / 打ち合わせ: 議事録?")
        #expect(WikiExportRenderer.fileName(for: meta) == "2026-07-01-顧客A-打ち合わせ-議事録.md")
    }

    @Test("fileName(for:) falls back to \"untitled\" end-to-end when the title is empty")
    func fileNameFallsBackToUntitledForEmptyTitle() {
        let meta = makeMeta(title: "")
        #expect(WikiExportRenderer.fileName(for: meta) == "2026-07-01-untitled.md")
    }
}
