import Foundation
import Testing

@testable import Kikimi

/// Layer 1 (unit) coverage for `TranscriptMarkdownSource` (`docs/design/37-transcript-markdown-copy.md`
/// §3.2(b)/§7), the disk-backed speaker-name resolution adapter used by `SessionListViewModel`'s
/// "Markdown をコピー" and by `WikiExporter`. Every test builds a real fixture session folder in a
/// temporary directory -- `meta.json`/`transcript.jsonl`/`refined.jsonl`/`diarization.jsonl`/
/// `speaker_assignments.json` -- through an actual `SessionHandle`'s own read/write API (never by
/// hand-writing JSON), and a real `VoiceprintStore` backed by a temporary file, exactly the way
/// `TranscriptMarkdownSource.load(sessionHandle:)` is used in production (§3.2(b): "テストは
/// `TranscriptMarkdownSource` を値ごと差し替える... `VoiceprintStore` は既存テストと同じく一時ファイルの実インスタンス
/// を使う").
@Suite("TranscriptMarkdownSource")
struct TranscriptMarkdownSourceTests {
    // MARK: - Fixtures

    private func makeTemporaryDirectory(prefix: String) -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(prefix)-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    /// A `VoiceprintStore` backed by a temporary file that does not exist yet -- `VoiceprintStore.init`
    /// treats a missing file as "start from an empty database" (`VoiceprintStore.swift`'s
    /// `loadDatabase(from:decoder:)`), so no fixture file needs to be pre-created.
    private func makeVoiceprintStore() -> (store: VoiceprintStore, fileURL: URL) {
        let fileURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("TranscriptMarkdownSourceTests-voiceprints-\(UUID().uuidString).json")
        return (VoiceprintStore(fileURL: fileURL), fileURL)
    }

    private func makeSessionHandle(directory: URL, title: String = "定例MTG") -> SessionHandle {
        let meta = SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: title,
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .ended,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_100),
            endedAt: Date(timeIntervalSince1970: 1_751_002_822),
            durationMs: 2_722_000,
            recordings: [
                RecordingSegment(
                    index: 0,
                    startedAt: Date(timeIntervalSince1970: 1_751_000_100),
                    endedAt: Date(timeIntervalSince1970: 1_751_002_822),
                    startMsOffset: 0
                ),
            ],
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
        return SessionHandle(directoryURL: directory, meta: meta)
    }

    private func makeSource(
        diarization: DiarizationConfig = .default,
        voiceprintStore: VoiceprintStore
    ) -> TranscriptMarkdownSource {
        TranscriptMarkdownSource(diarization: diarization, voiceprintStore: voiceprintStore)
    }

    private func line(_ lines: [TranscriptMarkdownRenderer.Line], id: String) -> TranscriptMarkdownRenderer.Line? {
        lines.first { $0.id == id }
    }

    private func makeRefinedSegment(
        id: String,
        startMs: Int,
        endMs: Int,
        speaker: AudioSourceKind,
        rawText: String,
        refinedText: String?,
        sourceSegIds: [String] = []
    ) -> RefinedSegment {
        RefinedSegment(
            id: id,
            startMs: startMs,
            endMs: endMs,
            speaker: speaker,
            rawText: rawText,
            refinedText: refinedText,
            error: refinedText == nil ? "refinement failed" : nil,
            refinedAt: Date(timeIntervalSince1970: 1_751_000_200),
            model: "claude-haiku-4-5-20251001",
            batchId: "batch_00001",
            sourceSegIds: sourceSegIds
        )
    }

    // MARK: - (a) refined + raw merge (TC15)

    @Test("load merges refined segments with a raw tail segment not covered by any RefinedSegment.sourceSegIds")
    func loadMergesRefinedAndRawTail() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-a")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let first = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 1_000, text: "raw one", confidence: 0.9)
        let second = try await handle.appendTranscriptSegment(
            source: .system, startMs: 1_000, endMs: 2_000, text: "raw two (tail)", confidence: 0.9
        )
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: first.id, startMs: first.startMs, endMs: first.endMs, speaker: .mic, rawText: first.text, refinedText: "整形済みテキスト")
        )
        // `second` is deliberately never refined -- an in-progress recording's tail or a
        // crash-recovery session whose last batch never got refined (TC15).

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        #expect(input.lines.count == 2)
        let refinedLine = try #require(line(input.lines, id: first.id))
        #expect(refinedLine.text == "整形済みテキスト")
        #expect(refinedLine.isRawFallback == false)

        let tailLine = try #require(line(input.lines, id: second.id))
        #expect(tailLine.text == "raw two (tail)")
        #expect(tailLine.isRawFallback == true)

        // Regression guard for the marker-doubling bug: the raw-fallback marker must appear exactly
        // once in the final rendered output, appended by `TranscriptMarkdownRenderer` from
        // `isRawFallback` alone -- never embedded in `Line.text` by this adapter.
        let rendered = TranscriptMarkdownRenderer.render(input, scope: .transcript)
        let occurrences = rendered.components(separatedBy: TranscriptMarkdownRenderer.rawFallbackMarker).count - 1
        #expect(occurrences == 1)
    }

    // MARK: - (b) segmentOverrides on a non-leading sourceSegIds entry

    @Test("load finds a segmentOverride pinned to a merged segment's non-leading sourceSegIds entry")
    func loadFindsOverrideOnNonLeadingSourceSegId() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-b")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let first = try await handle.appendTranscriptSegment(source: .system, startMs: 0, endMs: 1_000, text: "a", confidence: 0.9)
        let second = try await handle.appendTranscriptSegment(source: .system, startMs: 1_000, endMs: 2_000, text: "b", confidence: 0.9)
        // A merged `RefinedSegment`: `id == sourceSegIds.first` (`SessionModels.swift:62`), so the
        // override below is pinned to `second.id`, which is *not* the leading id.
        try await handle.appendRefinedSegment(
            makeRefinedSegment(
                id: first.id, startMs: first.startMs, endMs: second.endMs, speaker: .system,
                rawText: "a b", refinedText: "整形済み", sourceSegIds: [first.id, second.id]
            )
        )
        try await handle.updateSpeakerAssignments { assignments in
            assignments.segmentOverrides[second.id] = SegmentSpeakerOverride(displayName: "田中")
        }

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        #expect(input.lines.count == 1)
        let resolvedLine = try #require(line(input.lines, id: first.id))
        #expect(resolvedLine.speakerName == "田中")
    }

    // MARK: - (c) turns present -> activeRanges full opt-in resolves a past session's speaker names

    @Test("load resolves a past session's speaker name from diarization turns + speaker_assignments.json when turns are non-empty")
    func loadResolvesSpeakerNameFromTurnsWhenNonEmpty() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-c")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .system, startMs: 0, endMs: 1_000, text: "こんにちは", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .system, rawText: segment.text, refinedText: "こんにちは。")
        )
        // Fully covers the segment's time range so it attributes wholly to `spk_1`.
        try await handle.appendDiarizationTurn(DiarizationTurn(slot: "spk_1", startMs: 0, endMs: 1_000))
        try await handle.updateSpeakerAssignments { assignments in
            assignments.assignments["spk_1"] = SlotAssignment(displayName: "田中", assignedBy: .user)
        }

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.speakerName == "田中")
    }

    // MARK: - (d) unattributed segment -> "Speaker ?", never ".recognizing"

    @Test("load resolves an unattributed system segment to \"Speaker ?\", not the recognizing placeholder")
    func loadResolvesUnattributedSegmentToSpeakerQuestionMark() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-d")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .system, startMs: 0, endMs: 1_000, text: "謎の音声", confidence: 0.4)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .system, rawText: segment.text, refinedText: "謎の音声。")
        )
        // A turn exists (so `turns` is non-empty and `activeRanges` opts every segment in), but it
        // does not overlap this segment's [0, 1_000) time range at all -> unattributed.
        try await handle.appendDiarizationTurn(DiarizationTurn(slot: "spk_1", startMs: 5_000, endMs: 6_000))

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.speakerName == "Speaker ?")
    }

    // MARK: - (e) VoiceprintStore rename wins over the snapshot displayName (design 23 §2.2 regression)

    @Test("load prefers VoiceprintStore's current registered name over speaker_assignments.json's frozen snapshot displayName")
    func loadPrefersCurrentRegisteredNameOverSnapshot() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-e")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .system, startMs: 0, endMs: 1_000, text: "よろしくお願いします", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .system, rawText: segment.text, refinedText: "よろしくお願いします。")
        )
        try await handle.appendDiarizationTurn(DiarizationTurn(slot: "spk_1", startMs: 0, endMs: 1_000))

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let registered = try await voiceprintStore.registerSpeaker(name: "旧名", embedding: [])
        // `speaker_assignments.json`'s snapshot was frozen with the name current *at assignment
        // time* ("旧名(snapshot)") -- distinct from `registered.name` so the test can tell which one
        // won.
        try await handle.updateSpeakerAssignments { assignments in
            assignments.assignments["spk_1"] = SlotAssignment(globalSpeakerId: registered.id, displayName: "旧名(snapshot)", assignedBy: .auto)
        }
        // The Settings 話者 tab renames the speaker after the snapshot was written.
        try await voiceprintStore.renameSpeaker(id: registered.id, name: "新名")

        let source = makeSource(voiceprintStore: voiceprintStore)
        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.speakerName == "新名")
    }

    // MARK: - (f) no diarization.jsonl (turns empty) -> every row "system", never "Speaker ?"

    @Test("load resolves every system line to \"system\" when diarization.jsonl doesn't exist (turns empty)")
    func loadResolvesToSystemWhenNoDiarizationTurnsExist() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-f")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .system, startMs: 0, endMs: 1_000, text: "テスト", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .system, rawText: segment.text, refinedText: "テスト。")
        )
        // No `appendDiarizationTurn(_:)` call at all -- `diarization.jsonl` never gets created, so
        // `readDiarizationTurns()` returns `[]` (a past session recorded before this feature existed,
        // or one where the system stream never triggered diarization).

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.speakerName == "system")
    }

    // MARK: - (g) diarization.enabled == false -> every row "system", even with turns present

    @Test("load resolves every system line to \"system\" when DiarizationConfig.enabled is false, even with turns present")
    func loadResolvesToSystemWhenDiarizationDisabled() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-g")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .system, startMs: 0, endMs: 1_000, text: "テスト", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .system, rawText: segment.text, refinedText: "テスト。")
        )
        try await handle.appendDiarizationTurn(DiarizationTurn(slot: "spk_1", startMs: 0, endMs: 1_000))
        try await handle.updateSpeakerAssignments { assignments in
            assignments.assignments["spk_1"] = SlotAssignment(displayName: "田中", assignedBy: .user)
        }

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        var disabledDiarization = DiarizationConfig.default
        disabledDiarization.enabled = false
        let source = makeSource(diarization: disabledDiarization, voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.speakerName == "system")
    }

    // MARK: - (h) mic segments always use the injected DiarizationConfig.selfName

    @Test("load resolves mic segments to the injected DiarizationConfig.selfName, bypassing speaker resolution")
    func loadResolvesMicSegmentsToSelfName() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-h")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 1_000, text: "私から共有します", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .mic, rawText: segment.text, refinedText: "私から共有します。")
        )
        // Turns/assignments exist but must never apply to a `mic` line (design §4.2's "`mic` セグメント
        // は上表を通さず常に `selfName`").
        try await handle.appendDiarizationTurn(DiarizationTurn(slot: "spk_1", startMs: 0, endMs: 1_000))
        try await handle.updateSpeakerAssignments { assignments in
            assignments.assignments["spk_1"] = SlotAssignment(displayName: "田中", assignedBy: .user)
        }

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        var config = DiarizationConfig.default
        config.selfName = "テスト太郎"
        let source = makeSource(diarization: config, voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.speakerName == "テスト太郎")
    }

    // MARK: - (j) anonymous slot (no displayName) -> "Speaker N"

    @Test("load resolves a dominant slot with no displayName to \"Speaker N\" (SpeakerDisplayLabel.anonymous)")
    func loadResolvesAnonymousSlotToSpeakerNumber() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-j")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .system, startMs: 0, endMs: 1_000, text: "はい", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .system, rawText: segment.text, refinedText: "はい。")
        )
        // `spk_3` fully covers the segment's range but is never assigned a displayName in
        // `speaker_assignments.json` -- `SpeakerLabelResolver.resolvedLabel(forSlot:...)` falls back
        // to `.anonymous(slotNumber:)` (`SpeakerLabeling.swift:191`), distinct from the unattributed
        // "Speaker ?" case (test (d) above): here a slot *did* dominate, it just has no name yet.
        try await handle.appendDiarizationTurn(DiarizationTurn(slot: "spk_3", startMs: 0, endMs: 1_000))

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.speakerName == "Speaker 3")
    }

    // MARK: - (k) two slots overlap enough to trigger .mixed -> "primary + secondary"

    @Test("load resolves two substantially-overlapping slots to \"primary + secondary\" (SpeakerDisplayLabel.mixed)")
    func loadResolvesMixedSpeakersToConcatenatedNames() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-k")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        // A 10s segment: `SegmentAttribution.attribute` trims `edgeTrimRatio` (0.15) off each end,
        // leaving a [1_500, 8_500) central range. Two turns fully covering that same central range
        // give both slots equal, fully-overlapping occupancy -- well past
        // `AttributionTuning.secondSpeakerMixedThreshold` (0.3) -- so `attribute(...)` resolves to
        // `.mixed(primary: "spk_1", secondary: "spk_2")` (tie broken by ascending slot id,
        // `SegmentAttribution.swift:113`).
        let segment = try await handle.appendTranscriptSegment(source: .system, startMs: 0, endMs: 10_000, text: "重なった発話", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .system, rawText: segment.text, refinedText: "重なった発話。")
        )
        try await handle.appendDiarizationTurn(DiarizationTurn(slot: "spk_1", startMs: 0, endMs: 10_000))
        try await handle.appendDiarizationTurn(DiarizationTurn(slot: "spk_2", startMs: 0, endMs: 10_000))
        try await handle.updateSpeakerAssignments { assignments in
            assignments.assignments["spk_1"] = SlotAssignment(displayName: "田中", assignedBy: .user)
            assignments.assignments["spk_2"] = SlotAssignment(displayName: "佐藤", assignedBy: .user)
        }

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.speakerName == "田中 + 佐藤")
    }

    // MARK: - (l) unreadable summary.md (invalid UTF-8) -> empty サマリ, transcript still loads (§6)

    @Test("load falls back to an empty summaryMarkdown and still loads the transcript when summary.md is not valid UTF-8")
    func loadFallsBackToEmptySummaryWhenSummaryMarkdownIsUnreadable() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-l")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 1_000, text: "テスト", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .mic, rawText: segment.text, refinedText: "テスト。")
        )
        // Invalid UTF-8 byte sequence -- `SessionHandle.readTextIfPresent(_:)` throws
        // `SessionHandleError.invalidTextEncoding` for this (`SessionHandle.swift:213`), which
        // `TranscriptMarkdownSource.load(sessionHandle:)`'s `do`/`catch` must swallow (§6: "summary.md
        // が読めない -> サマリを空として扱い... コピーを続行"), the same fallback `WikiExporter.export(sessionHandle:)`
        // already relies on.
        let invalidUTF8 = Data([0xFF, 0xFE, 0x00, 0x01])
        try invalidUTF8.write(to: sessionDir.appendingPathComponent("summary.md"))

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        #expect(input.summaryMarkdown.isEmpty)
        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.text == "テスト。")
    }

    // MARK: - (i) displayText's 3 branches (moved from WikiExportRendererTests)

    @Test("load includes a non-empty refinedText as-is, with isRawFallback == false")
    func loadIncludesNonEmptyRefinedTextAsIs() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-i1")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 1_000, text: "生テキスト", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .mic, rawText: segment.text, refinedText: "整形済みテキスト")
        )

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.text == "整形済みテキスト")
        #expect(resolvedLine.isRawFallback == false)
    }

    @Test("load falls back to rawText (without the marker embedded) when refinedText is nil, with isRawFallback == true")
    func loadFallsBackToRawTextWhenRefinedTextIsNil() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-i2")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 1_000, text: "生テキスト", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .mic, rawText: segment.text, refinedText: nil)
        )

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        let resolvedLine = try #require(line(input.lines, id: segment.id))
        #expect(resolvedLine.text == "生テキスト", "the marker is TranscriptMarkdownRenderer's job (isRawFallback), not embedded in Line.text here")
        #expect(resolvedLine.isRawFallback == true)
    }

    @Test("load excludes a segment entirely when refinedText == \"\" (intentional deletion, kikimi.md 7 章)")
    func loadExcludesIntentionallyDeletedSegment() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "TranscriptMarkdownSourceTests-i3")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        let segment = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 1_000, text: "意味のない発話", confidence: 0.9)
        try await handle.appendRefinedSegment(
            makeRefinedSegment(id: segment.id, startMs: segment.startMs, endMs: segment.endMs, speaker: .mic, rawText: segment.text, refinedText: "")
        )

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }
        let source = makeSource(voiceprintStore: voiceprintStore)

        let input = try await source.load(sessionHandle: handle)

        #expect(line(input.lines, id: segment.id) == nil)
        #expect(input.lines.isEmpty)
    }
}
