import Foundation
import Testing

@testable import Kikimi

/// Layer 1 (unit) coverage for `TranscriptMarkdownRenderer` (`docs/design/37-transcript-markdown-copy
/// .md` §3.1/§4/§7), the pure rendering half shared by the Wiki export and the "copy transcript as
/// Markdown" feature. Every test constructs plain `Input`/`Line` values directly -- never a
/// `SessionHandle`/`AppConfig` -- since speaker-name resolution and line selection are each caller's
/// adapter's job (design §3.2), not this type's.
///
/// Every `Date` fixture is built from `DateComponents` against `Calendar.current`/`TimeZone.current`
/// (via `date(...)` below), matching the renderer's own `.current`-timezone formatters, so assertions
/// never depend on which timezone actually runs the test.
@Suite("TranscriptMarkdownRenderer")
struct TranscriptMarkdownRendererTests {
    /// `static` (not an instance method) so it can also be used directly in another helper's default
    /// argument expressions (`makeMeta(...)`'s `createdAt`/`startedAt` defaults below), which run in a
    /// context with no `self`.
    private static func date(year: Int, month: Int, day: Int, hour: Int, minute: Int, second: Int) -> Date {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = .current
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = day
        components.hour = hour
        components.minute = minute
        components.second = second
        return calendar.date(from: components)!
    }

    /// - Parameter startedAt: Passed straight through to `SessionMeta.startedAt` with **no**
    ///   `?? fallback` substitution -- its default argument value is already the sensible non-nil
    ///   date most tests want, so a test that instead needs `meta.startedAt == nil` can pass
    ///   `startedAt: nil` explicitly and have it actually land on the constructed `SessionMeta`.
    private func makeMeta(
        id: String = "2026-07-01T14-30-00_a1b2c3d4",
        title: String = "デイリースクラム",
        createdAt: Date = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 28, second: 12),
        startedAt: Date? = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0),
        durationMs: Int = 2_722_000,
        recordings: [RecordingSegment] = []
    ) -> SessionMeta {
        SessionMeta(
            id: id,
            title: title,
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .ended,
            createdAt: createdAt,
            startedAt: startedAt,
            endedAt: Self.date(year: 2_026, month: 7, day: 1, hour: 15, minute: 15, second: 22),
            durationMs: durationMs,
            recordings: recordings,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func makeLine(
        id: String,
        startMs: Int,
        speakerName: String = "田中",
        text: String = "テキスト",
        isRawFallback: Bool = false
    ) -> TranscriptMarkdownRenderer.Line {
        TranscriptMarkdownRenderer.Line(id: id, startMs: startMs, speakerName: speakerName, text: text, isRawFallback: isRawFallback)
    }

    // MARK: - wallClockDate(startMs:recordings:fallback:)

    @Test("wallClockDate resolves a single-segment session's startMs directly against its startedAt")
    func wallClockDateSingleSegment() {
        let started = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let recordings = [RecordingSegment(index: 0, startedAt: started, endedAt: nil, startMsOffset: 0)]
        let result = TranscriptMarkdownRenderer.wallClockDate(startMs: 5_000, recordings: recordings, fallback: started)
        #expect(result == started.addingTimeInterval(5))
    }

    @Test("wallClockDate resolves a startMs in the second of two recording segments (a pause/resume gap)")
    func wallClockDateAcrossTwoSegments() {
        let firstStart = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let secondStart = Self.date(year: 2_026, month: 7, day: 1, hour: 15, minute: 5, second: 30)
        let recordings = [
            RecordingSegment(index: 0, startedAt: firstStart, endedAt: firstStart.addingTimeInterval(1_330), startMsOffset: 0),
            RecordingSegment(index: 1, startedAt: secondStart, endedAt: nil, startMsOffset: 1_330_000),
        ]
        // 10 seconds into the second segment.
        let result = TranscriptMarkdownRenderer.wallClockDate(startMs: 1_340_000, recordings: recordings, fallback: firstStart)
        #expect(result == secondStart.addingTimeInterval(10))
    }

    @Test("wallClockDate at exactly a segment boundary offset resolves to that segment's startedAt")
    func wallClockDateAtExactSegmentBoundary() {
        let firstStart = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let secondStart = Self.date(year: 2_026, month: 7, day: 1, hour: 15, minute: 5, second: 30)
        let recordings = [
            RecordingSegment(index: 0, startedAt: firstStart, endedAt: firstStart.addingTimeInterval(1_330), startMsOffset: 0),
            RecordingSegment(index: 1, startedAt: secondStart, endedAt: nil, startMsOffset: 1_330_000),
        ]
        let result = TranscriptMarkdownRenderer.wallClockDate(startMs: 1_330_000, recordings: recordings, fallback: firstStart)
        #expect(result == secondStart)
    }

    @Test("wallClockDate resolves a startMs owned by the middle of three recording segments, not just the last")
    func wallClockDateAmongThreeSegmentsPicksTheOwningSegment() {
        // Regression for the doc comment's "the one with the greatest startMsOffset <= startMs":
        // every other wallClockDate test above uses at most two segments, where `last(where:)` and a
        // naive "always use recordings.last" bug would coincidentally produce the same answer. A
        // startMs that lands inside the *middle* segment (neither the first nor the last) is the only
        // way to catch that class of bug directly.
        let firstStart = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let secondStart = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 45, second: 0)
        let thirdStart = Self.date(year: 2_026, month: 7, day: 1, hour: 15, minute: 10, second: 0)
        let recordings = [
            RecordingSegment(index: 0, startedAt: firstStart, endedAt: firstStart.addingTimeInterval(600), startMsOffset: 0),
            RecordingSegment(index: 1, startedAt: secondStart, endedAt: secondStart.addingTimeInterval(600), startMsOffset: 600_000),
            RecordingSegment(index: 2, startedAt: thirdStart, endedAt: nil, startMsOffset: 1_200_000),
        ]
        // 100 seconds into the second (middle) segment -- well before the third segment's offset.
        let result = TranscriptMarkdownRenderer.wallClockDate(startMs: 700_000, recordings: recordings, fallback: firstStart)
        #expect(result == secondStart.addingTimeInterval(100))
    }

    @Test("wallClockDate falls back to fallback + startMs when recordings is empty")
    func wallClockDateFallsBackWhenRecordingsIsEmpty() {
        let fallback = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let result = TranscriptMarkdownRenderer.wallClockDate(startMs: 2_500, recordings: [], fallback: fallback)
        #expect(result == fallback.addingTimeInterval(2.5))
    }

    @Test("wallClockDate falls back to recordings.first (not fallback) when startMs precedes every segment's offset")
    func wallClockDateFallsBackToFirstRecordingWhenStartMsPrecedesAllOffsets() {
        // Defensive-only branch (`last(where:)` finds no match): `startMsOffset` is normally 0 for the
        // first segment, but the guard's `?? recordings.first` still needs to be exercised directly.
        let segmentStart = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let recordings = [RecordingSegment(index: 0, startedAt: segmentStart, endedAt: nil, startMsOffset: 5_000)]
        let unrelatedFallback = Self.date(year: 2_020, month: 1, day: 1, hour: 0, minute: 0, second: 0)
        let result = TranscriptMarkdownRenderer.wallClockDate(startMs: 1_000, recordings: recordings, fallback: unrelatedFallback)
        // elapsedInSegment = (1_000 - 5_000) / 1_000 = -4s against the *segment's* startedAt, never the fallback.
        #expect(result == segmentStart.addingTimeInterval(-4))
    }

    // MARK: - durationLabel(durationMs:)

    @Test("durationLabel rounds to the nearest whole minute")
    func durationLabelRoundsToNearestMinute() {
        #expect(TranscriptMarkdownRenderer.durationLabel(durationMs: 2_722_000) == "45m")
        #expect(TranscriptMarkdownRenderer.durationLabel(durationMs: 90_000) == "2m") // 1.5min rounds up
        #expect(TranscriptMarkdownRenderer.durationLabel(durationMs: 89_000) == "1m") // 1.483min rounds down
        #expect(TranscriptMarkdownRenderer.durationLabel(durationMs: 0) == "0m")
    }

    // MARK: - referenceDate(for:)

    @Test("referenceDate falls back to createdAt when startedAt is nil")
    func referenceDateFallsBackToCreatedAtWhenStartedAtIsNil() {
        let created = Self.date(year: 2_026, month: 8, day: 15, hour: 9, minute: 0, second: 0)
        let meta = makeMeta(createdAt: created, startedAt: nil)
        #expect(TranscriptMarkdownRenderer.referenceDate(for: meta) == created)
    }

    @Test("referenceDate prefers startedAt over createdAt when both are present")
    func referenceDatePrefersStartedAtWhenPresent() {
        let created = Self.date(year: 2_026, month: 8, day: 15, hour: 8, minute: 55, second: 0)
        let started = Self.date(year: 2_026, month: 8, day: 15, hour: 9, minute: 0, second: 0)
        let meta = makeMeta(createdAt: created, startedAt: started)
        #expect(TranscriptMarkdownRenderer.referenceDate(for: meta) == started)
    }

    // MARK: - render(_:scope: .full)

    @Test("render(_:scope: .full) produces design §4.1's documented shape end-to-end")
    func renderFullProducesDocumentedShape() {
        let started = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let recordings = [RecordingSegment(index: 0, startedAt: started, endedAt: nil, startMsOffset: 0)]
        let meta = makeMeta(title: "デイリースクラム", durationMs: 2_722_000, recordings: recordings)

        let lines = [
            makeLine(id: "seg_00001", startMs: 5_000, speakerName: "自分", text: "次のスプリントで対応します。"),
            makeLine(id: "seg_00002", startMs: 8_000, speakerName: "田中", text: "了解しました。"),
            makeLine(id: "seg_00003", startMs: 12_000, speakerName: "自分", text: "raw fallback text", isRawFallback: true),
        ]

        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "## 概要\n\n会議の概要です。", lines: lines),
            scope: .full
        )

        let expected = """
        ---
        date: 2026-07-01
        duration: 45m
        source: kikimi
        session_id: 2026-07-01T14-30-00_a1b2c3d4
        tags: [meeting, transcript]
        ---

        # デイリースクラム

        ## サマリ

        ## 概要

        会議の概要です。

        ## 書き起こし

        **14:30:05 自分** 次のスプリントで対応します。

        **14:30:08 田中** 了解しました。

        **14:30:12 自分** raw fallback text\(TranscriptMarkdownRenderer.rawFallbackMarker)

        """
        #expect(markdown == expected)
    }

    @Test("render(_:scope: .full) uses createdAt for both the frontmatter date and the transcript wall-clock when startedAt is nil")
    func renderFullUsesCreatedAtConsistentlyForFrontmatterAndTranscriptWhenStartedAtIsNil() {
        // `referenceDate(for:)`'s doc comment claims the frontmatter `date:` and the transcript's
        // wall-clock fallback "always agree even for a degenerate session with no recordings at all" --
        // but `render(_:scope:)` calls `referenceDate(for: meta)` from two independent call sites
        // (`frontmatterBlock` and the transcript body), so nothing structurally guarantees that beyond
        // both happening to call the same pure function. Every other `render` test uses a non-nil
        // `startedAt`, which never exercises this fallback path at all.
        let created = Self.date(year: 2_026, month: 8, day: 15, hour: 9, minute: 0, second: 0)
        let meta = makeMeta(title: "無題の会議", createdAt: created, startedAt: nil, recordings: [])
        let lines = [makeLine(id: "seg_00001", startMs: 5_000, speakerName: "自分", text: "本文です。")]

        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "", lines: lines),
            scope: .full
        )

        #expect(markdown.contains("date: 2026-08-15"))
        // 5 seconds after createdAt (09:00:00), the same reference point the frontmatter date used.
        #expect(markdown.contains("**09:00:05 自分** 本文です。"))
    }

    @Test("render(_:scope:) treats a whitespace-only summaryMarkdown as non-empty (no trimming before the isEmpty check)")
    func renderTreatsWhitespaceOnlySummaryMarkdownAsNonEmpty() {
        // TC14 only specifies that an empty string ("") omits the heading; the implementation's
        // `!input.summaryMarkdown.isEmpty` check is a literal string comparison with no trimming, so a
        // whitespace-only string is *not* empty and must still produce the heading. This pins that
        // literal (non-trimmed) contract against a future "helpful" trim being added.
        let meta = makeMeta(title: "空白サマリの会議")
        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "   ", lines: []),
            scope: .summary
        )
        #expect(markdown.contains("## サマリ"))
        #expect(markdown == "# 空白サマリの会議\n\n## サマリ\n\n   \n")
    }

    @Test("render(_:scope:) passes a title containing Markdown-sensitive characters through verbatim, unescaped")
    func renderPassesThroughMarkdownSensitiveTitleUnescaped() {
        // The renderer documents itself as purely ordering/formatting already-final strings (type doc
        // comment, lines 12-15) -- it has no escaping step. A title containing `#`/`*`/`[]` (a real
        // possibility for an auto-generated or user-edited meeting title) must appear byte-for-byte
        // after "# ", not be sanitized or corrupt the heading.
        let meta = makeMeta(title: "# 顧客A [緊急] *打ち合わせ*")
        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "", lines: []),
            scope: .transcript
        )
        #expect(markdown == "# # 顧客A [緊急] *打ち合わせ*\n")
    }

    @Test("render(_:scope: .full) omits both the サマリ and 書き起こし headings when both are empty")
    func renderFullOmitsBothSectionsWhenEmpty() {
        let meta = makeMeta(title: "空の会議")
        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "", lines: []),
            scope: .full
        )
        let expected = """
        ---
        date: 2026-07-01
        duration: 45m
        source: kikimi
        session_id: 2026-07-01T14-30-00_a1b2c3d4
        tags: [meeting, transcript]
        ---

        # 空の会議

        """
        #expect(markdown == expected)
        #expect(!markdown.contains("## サマリ"))
        #expect(!markdown.contains("## 書き起こし"))
    }

    @Test("render(_:scope:) omits only \"## サマリ\" when summaryMarkdown is empty but lines is not (TC14)")
    func renderOmitsOnlySummaryHeadingWhenSummaryEmptyButLinesPresent() {
        let meta = makeMeta(title: "サマリ未生成の会議")
        let lines = [makeLine(id: "seg_00001", startMs: 0, speakerName: "自分", text: "本文")]

        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "", lines: lines),
            scope: .full
        )

        #expect(!markdown.contains("## サマリ"))
        #expect(markdown.contains("## 書き起こし"))
    }

    @Test("render(_:scope:) omits only \"## 書き起こし\" when lines is empty but summaryMarkdown is not (TC14)")
    func renderOmitsOnlyTranscriptHeadingWhenLinesEmptyButSummaryPresent() {
        let meta = makeMeta(title: "書き起こし0行の会議")

        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "## 概要\n\n本文なし。", lines: []),
            scope: .full
        )

        #expect(!markdown.contains("## 書き起こし"))
        #expect(markdown.contains("## サマリ"))
    }

    // MARK: - §4.2 speaker column mapping (already-resolved strings)

    // `TranscriptMarkdownRenderer` does not itself compute the §4.2 mapping -- `Line.speakerName`
    // arrives already resolved from the adapter (design §3.1/§3.2: mapping is each adapter's
    // responsibility, not this type's). These tests fix the renderer's side of the contract: whatever
    // already-mapped string an adapter hands it for each `SpeakerDisplayLabel` case in §4.2's table,
    // it appears verbatim in the speaker column, untouched.
    @Test("renderLine passes through a .named display name verbatim (§4.2)")
    func rendersNamedSpeaker() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 5_000, speakerName: "田中", text: "本文です。")
        #expect(TranscriptMarkdownRenderer.renderLine(line, meta: meta) == "**14:30:05 田中** 本文です。")
    }

    @Test("renderLine passes through an .anonymous \"Speaker n\" label verbatim (§4.2)")
    func rendersAnonymousSpeaker() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 5_000, speakerName: "Speaker 2", text: "本文です。")
        #expect(TranscriptMarkdownRenderer.renderLine(line, meta: meta) == "**14:30:05 Speaker 2** 本文です。")
    }

    @Test("renderLine passes through a .mixed \"a + b\" label verbatim (§4.2)")
    func rendersMixedSpeaker() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 5_000, speakerName: "田中 + 佐藤", text: "本文です。")
        #expect(TranscriptMarkdownRenderer.renderLine(line, meta: meta) == "**14:30:05 田中 + 佐藤** 本文です。")
    }

    @Test("renderLine passes through the .recognizing/.unknown \"Speaker ?\" label verbatim (§4.2)")
    func rendersRecognizingOrUnknownSpeaker() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 5_000, speakerName: "Speaker ?", text: "本文です。")
        #expect(TranscriptMarkdownRenderer.renderLine(line, meta: meta) == "**14:30:05 Speaker ?** 本文です。")
    }

    @Test("renderLine passes through the .systemFallback \"system\" label verbatim (§4.2)")
    func rendersSystemFallbackSpeaker() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 5_000, speakerName: "system", text: "本文です。")
        #expect(TranscriptMarkdownRenderer.renderLine(line, meta: meta) == "**14:30:05 system** 本文です。")
    }

    @Test("renderLine passes through the no-diarization-label mic fallback (selfName) verbatim (§4.2 last row)")
    func rendersMicSelfNameFallback() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 5_000, speakerName: "自分", text: "本文です。")
        #expect(TranscriptMarkdownRenderer.renderLine(line, meta: meta) == "**14:30:05 自分** 本文です。")
    }

    // MARK: - render(_:scope: .transcript / .summary) -- TC6

    @Test("render(_:scope: .transcript) has no frontmatter and no サマリ section, even when summaryMarkdown is non-empty")
    func renderTranscriptScopeOmitsFrontmatterAndSummary() {
        let meta = makeMeta()
        let lines = [makeLine(id: "seg_00001", startMs: 5_000, speakerName: "田中", text: "了解しました。")]
        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "概要", lines: lines),
            scope: .transcript
        )
        let expected = """
        # デイリースクラム

        ## 書き起こし

        **14:30:05 田中** 了解しました。

        """
        #expect(markdown == expected)
        #expect(!markdown.contains("---"))
        #expect(!markdown.contains("## サマリ"))
    }

    @Test("render(_:scope: .summary) has no frontmatter and no 書き起こし section, even when lines is non-empty")
    func renderSummaryScopeOmitsFrontmatterAndTranscript() {
        let meta = makeMeta()
        let lines = [makeLine(id: "seg_00001", startMs: 5_000)]
        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "## 概要\n\n会議の概要です。", lines: lines),
            scope: .summary
        )
        let expected = """
        # デイリースクラム

        ## サマリ

        ## 概要

        会議の概要です。

        """
        #expect(markdown == expected)
        #expect(!markdown.contains("---"))
        #expect(!markdown.contains("## 書き起こし"))
    }

    @Test("render(_:scope: .transcript) omits the 書き起こし heading and leaves just the title when lines is empty")
    func renderTranscriptScopeOmitsHeadingWhenLinesIsEmpty() {
        let meta = makeMeta(title: "空の会議")
        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "無視されるはずのサマリ", lines: []),
            scope: .transcript
        )
        #expect(markdown == "# 空の会議\n")
        #expect(!markdown.contains("## 書き起こし"))
        #expect(!markdown.contains("## サマリ"))
    }

    @Test("render(_:scope: .summary) omits the サマリ heading and leaves just the title when summaryMarkdown is empty")
    func renderSummaryScopeOmitsHeadingWhenSummaryMarkdownIsEmpty() {
        let meta = makeMeta(title: "空の会議")
        let lines = [makeLine(id: "seg_00001", startMs: 0, text: "無視されるはずの本文")]
        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "", lines: lines),
            scope: .summary
        )
        #expect(markdown == "# 空の会議\n")
        #expect(!markdown.contains("## サマリ"))
        #expect(!markdown.contains("## 書き起こし"))
    }

    // MARK: - Ordering determinism (design §3.1 "Line.id を持つ理由")

    @Test("render(_:scope:) orders same-startMs lines by id ascending regardless of input order")
    func renderOrdersSameStartMsLinesByIdAscending() {
        let meta = makeMeta()
        let forward = [
            makeLine(id: "a", startMs: 1_000, speakerName: "自分", text: "first"),
            makeLine(id: "b", startMs: 1_000, speakerName: "田中", text: "second"),
        ]
        let reversed = Array(forward.reversed())

        let forwardMarkdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "", lines: forward), scope: .transcript
        )
        let reversedMarkdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "", lines: reversed), scope: .transcript
        )

        #expect(forwardMarkdown == reversedMarkdown)
        #expect(forwardMarkdown.contains("first"))
        let firstRange = forwardMarkdown.range(of: "first")
        let secondRange = forwardMarkdown.range(of: "second")
        #expect(firstRange != nil && secondRange != nil && firstRange!.lowerBound < secondRange!.lowerBound)
    }

    @Test("render(_:scope:) orders lines with distinct startMs ascending regardless of input order")
    func renderOrdersLinesWithDistinctStartMsAscendingRegardlessOfInputOrder() {
        let meta = makeMeta()
        let unordered = [
            makeLine(id: "c", startMs: 12_000, text: "third"),
            makeLine(id: "a", startMs: 3_000, text: "first"),
            makeLine(id: "b", startMs: 8_000, text: "second"),
        ]

        let markdown = TranscriptMarkdownRenderer.render(
            TranscriptMarkdownRenderer.Input(meta: meta, summaryMarkdown: "", lines: unordered), scope: .transcript
        )

        let firstRange = markdown.range(of: "first")
        let secondRange = markdown.range(of: "second")
        let thirdRange = markdown.range(of: "third")
        #expect(firstRange != nil && secondRange != nil && thirdRange != nil)
        #expect(firstRange!.lowerBound < secondRange!.lowerBound)
        #expect(secondRange!.lowerBound < thirdRange!.lowerBound)
    }

    // MARK: - renderLine(_:meta:) -- §4.4

    @Test("renderLine matches the transcript section's line format exactly, with no trailing newline")
    func renderLineMatchesTranscriptSectionFormat() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 8_000, speakerName: "田中", text: "特にはありません。ただログの量が増えています。")
        let result = TranscriptMarkdownRenderer.renderLine(line, meta: meta)
        #expect(result == "**14:30:08 田中** 特にはありません。ただログの量が増えています。")
        #expect(!result.hasSuffix("\n"))
    }

    @Test("renderLine appends the raw-fallback marker when isRawFallback is true")
    func renderLineAppendsRawFallbackMarker() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 12_000, speakerName: "自分", text: "raw fallback text", isRawFallback: true)
        let result = TranscriptMarkdownRenderer.renderLine(line, meta: meta)
        #expect(result == "**14:30:12 自分** raw fallback text\(TranscriptMarkdownRenderer.rawFallbackMarker)")
    }

    @Test("renderLine does not append the raw-fallback marker when isRawFallback is false")
    func renderLineOmitsRawFallbackMarkerForRefinedLines() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 8_000, speakerName: "田中", text: "整形済みテキスト", isRawFallback: false)
        let result = TranscriptMarkdownRenderer.renderLine(line, meta: meta)
        #expect(result == "**14:30:08 田中** 整形済みテキスト")
        #expect(!result.contains(TranscriptMarkdownRenderer.rawFallbackMarker))
    }

    @Test("renderLine never emits the overlap marker (⚠) -- TC4")
    func renderLineNeverEmitsOverlapMarker() {
        let meta = makeMeta()
        let line = makeLine(id: "seg_00001", startMs: 5_000, speakerName: "田中", text: "テキスト")
        let result = TranscriptMarkdownRenderer.renderLine(line, meta: meta)
        #expect(!result.contains("⚠"))
    }

    @Test("renderLine resolves its time against meta.recordings, not just the referenceDate fallback")
    func renderLineUsesMetaRecordingsForWallClockAcrossSegmentGap() {
        let firstStart = Self.date(year: 2_026, month: 7, day: 1, hour: 14, minute: 30, second: 0)
        let secondStart = Self.date(year: 2_026, month: 7, day: 1, hour: 15, minute: 5, second: 30)
        let recordings = [
            RecordingSegment(index: 0, startedAt: firstStart, endedAt: firstStart.addingTimeInterval(1_330), startMsOffset: 0),
            RecordingSegment(index: 1, startedAt: secondStart, endedAt: nil, startMsOffset: 1_330_000),
        ]
        let meta = makeMeta(startedAt: firstStart, recordings: recordings)
        // 10 seconds into the second (post-gap) segment.
        let line = makeLine(id: "seg_00001", startMs: 1_340_000, speakerName: "田中", text: "本文です。")
        let result = TranscriptMarkdownRenderer.renderLine(line, meta: meta)
        #expect(result == "**15:05:40 田中** 本文です。")
    }
}
