import SwiftUI

// MARK: - SimpleWatcherFormSheet

/// The simple-Watcher create/edit form (`docs/design/34-simple-watchers.md` §6.2): the default entry
/// point for creating a Watcher (`WatcherManagementSection`'s "新規作成"), and the edit surface for
/// any `kind: simple` row (`WatcherPanelItem.isSimple`). Closure-injected like `WatcherEditSheet`
/// (`WatcherPrepSheets.swift`), so this view stays entirely ViewModel-agnostic -- the caller decides
/// whether `onSave` wraps `MeetingWorkspaceViewModel.createSimpleWatcher(_:)` or
/// `updateSimpleWatcher(id:_:)`.
///
/// `id`/`model` never appear as form fields (§6.2): `id` is generated by the ViewModel on create and
/// is immutable/hidden on edit; `model` is carried through untouched via
/// `SimpleWatcherSpecDraft.model` (populated from `loadSpec()`'s result in `apply(_:)` below) so a
/// hand-edited `model:` on the underlying `.md` file survives a form save (§6.3 "model の引き継ぎ
/// （サイレント喪失の防止）").
struct SimpleWatcherFormSheet: View {
    /// `nil` when creating a new Watcher; the existing id when editing one (session-local or preset).
    /// Only used to decide the title/button wording and whether `loadSpec()`/"詳細形式で作成…" apply --
    /// never rendered as an editable field.
    let editingId: String?
    /// `true` only for a preset row (§6.3): every field renders disabled and only "閉じる" is offered
    /// (fork the preset first to edit it -- same rule as `WatcherEditSheet`'s preset row).
    let isReadOnly: Bool
    /// Resolves the current `SimpleWatcherSpec` to prefill the form (the caller's
    /// `MeetingWorkspaceViewModel.simpleWatcherSpec(id:)`). Only invoked when `editingId != nil`; a
    /// brand-new Watcher starts from the field defaults below and never calls this.
    let loadSpec: () async -> SimpleWatcherSpec?
    /// "作成"/"保存". The caller decides whether this wraps `createSimpleWatcher(_:)` or
    /// `updateSimpleWatcher(id:_:)` -- both throw `LocalizedError`s that this sheet displays inline
    /// (§6.3 "フォームでのエラー表示") without dismissing, so a fixable mistake (e.g. a transient write
    /// failure) doesn't lose the user's edits.
    let onSave: (SimpleWatcherSpecDraft) async throws -> Void
    /// "詳細形式で作成…" (§6.1/6.2): dismisses this sheet and hands off to the full-form creation flow
    /// (`NewLocalWatcherSheet`). `nil` hides the link -- offered only while creating, never editing
    /// (there is no "詳細形式で編集" -- eject lives on the management row per §7, not in this form).
    var onOpenFullCreate: (() -> Void)?

    @Environment(\.dismiss) private var dismiss

    @State private var name = ""
    @State private var prompt = ""
    /// Carried through from `loadSpec()` untouched (§6.3 "model の引き継ぎ"); `nil` for a new Watcher.
    @State private var existingModel: String?
    @State private var targetKind: TargetKind = .recentConversation
    @State private var recentCount = WatcherInputScope.defaultRecentCount
    @State private var timingKind: TimingKind = .onSummaryUpdate
    @State private var intervalMinutes = 5

    @State private var isLoading: Bool
    @State private var isSaving = false
    @State private var errorMessage: String?

    init(
        editingId: String?,
        isReadOnly: Bool,
        loadSpec: @escaping () async -> SimpleWatcherSpec?,
        onSave: @escaping (SimpleWatcherSpecDraft) async throws -> Void,
        onOpenFullCreate: (() -> Void)? = nil
    ) {
        self.editingId = editingId
        self.isReadOnly = isReadOnly
        self.loadSpec = loadSpec
        self.onSave = onSave
        self.onOpenFullCreate = onOpenFullCreate
        _isLoading = State(initialValue: editingId != nil)
    }

    // MARK: - Local UI enums (mirror `WatcherInputScope`/`WatcherTrigger`'s desugared cases 1:1, §6.2)

    private enum TargetKind: Hashable {
        case recentConversation
        case summaryOnly
        case fullMeeting
    }

    private enum TimingKind: Hashable {
        case onSummaryUpdate
        case interval
        case manual
        case onSessionEnd
    }

    private var isNameEmpty: Bool { name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
    private var isPromptEmpty: Bool { prompt.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }

    private var title: String {
        if isReadOnly { return "簡易 Watcher（プリセット・読み取り専用）" }
        return editingId == nil ? "新規 簡易 Watcher" : "簡易 Watcher を編集"
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(title)
                .font(.headline)

            if isLoading {
                ProgressView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                formFields
            }

            if let errorMessage {
                Text(errorMessage)
                    .font(.caption)
                    .foregroundStyle(.red)
            }

            footer
        }
        .padding()
        .frame(width: 480, height: 520)
        .task {
            guard let editingId else { return }
            if let spec = await loadSpec() {
                apply(spec)
            } else {
                // The definition disappeared out from under us (e.g. deleted between opening the row
                // and this sheet loading). Surfacing a hint here beats a form that silently starts
                // empty and looks like a normal blank "new Watcher" state under an edit title.
                errorMessage = "Watcher \"\(editingId)\" の定義を読み込めませんでした。"
            }
            isLoading = false
        }
    }

    // MARK: - Fields

    private var formFields: some View {
        Form {
            Section("基本") {
                TextField("名前", text: $name)
                    .disabled(isReadOnly)

                VStack(alignment: .leading, spacing: 4) {
                    Text("観点")
                    PlainTextEditor(
                        text: $prompt,
                        isEditable: !isReadOnly,
                        placeholder: "例: いま議論している論点を3つ以内で整理してください。"
                            + "対立している選択肢があればそれも書いてください。"
                    )
                    .frame(minHeight: 120)
                }
            }

            Section("対象") {
                Picker("", selection: $targetKind) {
                    Text("直近の会話").tag(TargetKind.recentConversation)
                    Text("サマリのみ").tag(TargetKind.summaryOnly)
                    Text("会議全体").tag(TargetKind.fullMeeting)
                }
                .labelsHidden()
                .disabled(isReadOnly)

                if targetKind == .recentConversation {
                    SettingsIntField(label: "発言数", value: $recentCount, range: 1...200)
                        .disabled(isReadOnly)
                }
            }

            Section("実行タイミング") {
                Picker("", selection: $timingKind) {
                    Text("サマリ更新ごと").tag(TimingKind.onSummaryUpdate)
                    Text("定期").tag(TimingKind.interval)
                    Text("手動のみ").tag(TimingKind.manual)
                    Text("会議終了時").tag(TimingKind.onSessionEnd)
                }
                .labelsHidden()
                .disabled(isReadOnly)

                if timingKind == .interval {
                    SettingsIntField(label: "間隔", unit: "分", value: $intervalMinutes, range: 1...60)
                        .disabled(isReadOnly)
                }
            }
        }
        .formStyle(.grouped)
    }

    private var footer: some View {
        HStack {
            if !isReadOnly, editingId == nil, let onOpenFullCreate {
                Button("詳細形式で作成…") {
                    dismiss()
                    onOpenFullCreate()
                }
                .buttonStyle(.link)
                .controlSize(.small)
            }
            if isSaving {
                ProgressView().controlSize(.small)
            }
            Spacer()
            Button(isReadOnly ? "閉じる" : "キャンセル") { dismiss() }
            if !isReadOnly {
                Button(editingId == nil ? "作成" : "保存") { save() }
                    .keyboardShortcut(.defaultAction)
                    .disabled(isNameEmpty || isPromptEmpty || isSaving || isLoading)
            }
        }
    }

    // MARK: - Spec <-> form state

    /// Prefills every field from an existing `SimpleWatcherSpec` (edit mode's `.task`). The inverse of
    /// `currentDraft` below, except `on_interval` seconds that don't divide evenly into minutes are
    /// rounded UP to the nearest minute (minimum 1 minute, §6.2) -- a hand-edited `on_interval:45`
    /// initializes to "1 分" here, and saving as-is then overwrites the file with the rounded value
    /// (accepted: the simple form's timing field is minute-granularity by design; a user who needs
    /// second-level control uses "詳細形式に変換").
    private func apply(_ spec: SimpleWatcherSpec) {
        name = spec.name
        prompt = spec.prompt
        existingModel = spec.model

        switch spec.inputScope {
        case .summaryAndRecent(let count):
            targetKind = .recentConversation
            recentCount = count
        case .summary:
            targetKind = .summaryOnly
        case .fullRefined:
            targetKind = .fullMeeting
        }

        switch spec.trigger {
        case .onSummaryUpdate:
            timingKind = .onSummaryUpdate
        case .onInterval(let seconds):
            timingKind = .interval
            intervalMinutes = max(1, Int(ceil(Double(seconds) / 60.0)))
        case .onManual:
            timingKind = .manual
        case .onSessionEnd:
            timingKind = .onSessionEnd
        }
    }

    /// The draft `onSave` is called with -- built fresh from current field state on every save attempt
    /// so a retry after a fixed error reflects any edits made while `errorMessage` was showing.
    private var currentDraft: SimpleWatcherSpecDraft {
        SimpleWatcherSpecDraft(
            name: name.trimmingCharacters(in: .whitespacesAndNewlines),
            model: existingModel,
            prompt: prompt.trimmingCharacters(in: .whitespacesAndNewlines),
            trigger: currentTrigger,
            inputScope: currentInputScope
        )
    }

    private var currentInputScope: WatcherInputScope {
        switch targetKind {
        case .recentConversation:
            return .summaryAndRecent(count: recentCount)
        case .summaryOnly:
            return .summary
        case .fullMeeting:
            return .fullRefined
        }
    }

    private var currentTrigger: WatcherTrigger {
        switch timingKind {
        case .onSummaryUpdate:
            return .onSummaryUpdate
        case .interval:
            return .onInterval(seconds: intervalMinutes * 60)
        case .manual:
            return .onManual
        case .onSessionEnd:
            return .onSessionEnd
        }
    }

    // MARK: - Save

    private func save() {
        isSaving = true
        errorMessage = nil
        let draft = currentDraft
        Task {
            do {
                try await onSave(draft)
                isSaving = false
                dismiss()
            } catch {
                // §6.3 "フォームでのエラー表示": inline red text, sheet stays open so the user can retry
                // without losing what they typed.
                errorMessage = (error as? LocalizedError)?.errorDescription ?? "保存に失敗しました。"
                isSaving = false
            }
        }
    }
}
