import Foundation

// MARK: - SummaryUpdater + §3.4 session-end final title proposal

/// Split out of `SummaryUpdater.swift` to keep that file under the project's `file_length` lint limit
/// (mirrors `+Regeneration.swift`/`+ParticipantsMerge.swift`'s own splits). Only needs
/// `SummaryUpdater`'s already-`internal` surface (`sessionHandle`/`llm`/`config`/`logger`/
/// `eventsContinuation`/`promptBodyProvider`, the last per `docs/design/42-prompt-overrides.md`
/// §4.3), not any genuinely `private` member of the primary actor declaration.
extension SummaryUpdater {
    /// `on_session_end` final title proposal (§3.4): generates one title from the final
    /// `summary.state.json` and stores it as a proposal (never auto-reflected, see
    /// `applyFinalTitleProposal(_:)` below). Not `private`: called from `execute(_:)` in
    /// `SummaryUpdater.swift`, across the file split.
    func performFinalTitleProposal() async {
        let state: SummaryState
        do {
            state = (try await sessionHandle.readJSON(.summaryState, as: SummaryState.self)) ?? .empty
        } catch {
            logger.error("Failed to read summary.state.json for final title proposal: \(String(describing: error), privacy: .public)")
            return
        }

        // §3.4: state is the primary material (not the full refined transcript), to keep the
        // prompt small.
        let prompt = Self.finalTitlePrompt(state: state)

        let titleResult: TitleOnly
        do {
            let result: LLMResult<TitleOnly> = try await llm.complete(
                LLMRequest(
                    system: promptBodyProvider(.finalTitle),
                    user: prompt,
                    schema: SummaryJSONSchema.titleSchemaJSON,
                    model: config.model,
                    stubKey: "final_title"
                )
            )
            titleResult = result.value
        } catch {
            logger.warning("Final title LLM call failed, skipping: \(String(describing: error), privacy: .public)")
            return
        }

        let metaChanged = await applyFinalTitleProposal(titleResult.title)
        if metaChanged {
            eventsContinuation.yield(SummaryUpdateEvent(summaryMarkdown: nil, metaChanged: true))
        }
    }

    /// §3.4: same gating as §3.1 (`autoNaming` + `titleAutoGenerated`), but this only ever sets
    /// `titleProposal` -- it never auto-reflects into `meta.title` directly, regardless of
    /// `titleAutoNamedOnce` (session-end always waits for manual adoption).
    private func applyFinalTitleProposal(_ proposal: String) async -> Bool {
        guard config.autoNaming, !proposal.isEmpty else { return false }
        var changed = false
        do {
            try await sessionHandle.updateMeta { meta in
                guard meta.titleAutoGenerated else { return }
                guard proposal != meta.title else { return }
                meta.titleProposal = proposal
                changed = true
            }
        } catch {
            logger.error("Failed to apply final title proposal to meta.json: \(String(describing: error), privacy: .public)")
            return false
        }
        return changed
    }

    private static func finalTitlePrompt(state: SummaryState) -> String {
        """
        【概要】
        \(state.overview)

        【決定事項】
        \(state.decisions.map { "- \($0.text)" }.joined(separator: "\n"))

        会議のタイトルを1つ提案してください。
        """
    }
}
