import Foundation
import Testing

@testable import Kikimi

/// Layer 1 coverage for `ChatContextScope.resolve(...)` and `ChatContextBuilder`
/// (`docs/design/38-session-chat.md` §7). Pure: fixtures are plain
/// `TranscriptMarkdownRenderer.Input` values, never a `SessionHandle`.
@Suite("ChatContextBuilder")
struct ChatContextBuilderTests {
    // MARK: - Fixtures

    private func makeMeta(title: String = "定例MTG") -> SessionMeta {
        SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: title,
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .ended,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_100),
            endedAt: nil,
            durationMs: 0,
            recordings: [
                RecordingSegment(
                    index: 0,
                    startedAt: Date(timeIntervalSince1970: 1_751_000_100),
                    endedAt: nil,
                    startMsOffset: 0
                )
            ],
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    private func makeLine(
        id: String,
        startMs: Int,
        speakerName: String = "自分",
        text: String,
        isRawFallback: Bool = false
    ) -> TranscriptMarkdownRenderer.Line {
        TranscriptMarkdownRenderer.Line(
            id: id,
            startMs: startMs,
            speakerName: speakerName,
            text: text,
            isRawFallback: isRawFallback
        )
    }

    private func makeInput(
        summary: String = "サマリ本文",
        lines: [TranscriptMarkdownRenderer.Line] = []
    ) -> TranscriptMarkdownRenderer.Input {
        TranscriptMarkdownRenderer.Input(meta: makeMeta(), summaryMarkdown: summary, lines: lines)
    }

    // MARK: - resolve: thresholds

    @Test("resolve stays .full exactly at the budget and demotes one character past it")
    func resolveSwitchesAtTheBoundary() {
        let atLimit = ChatContextScope.resolve(
            transcriptLength: 90, summaryLength: 10, questionLength: 0, historyLength: 0, maxContextChars: 100
        )
        #expect(atLimit == ChatContextResolution(scope: .full, transcriptBudget: 90))

        let overLimit = ChatContextScope.resolve(
            transcriptLength: 91, summaryLength: 10, questionLength: 0, historyLength: 0, maxContextChars: 100
        )
        #expect(overLimit == ChatContextResolution(scope: .summaryAndRecent, transcriptBudget: 90))
    }

    @Test("resolve counts the question and the history, so a short transcript can still demote")
    func resolveCountsQuestionAndHistory() {
        // The transcript alone is well under the budget; the pasted question is what overruns it.
        let byQuestion = ChatContextScope.resolve(
            transcriptLength: 20, summaryLength: 0, questionLength: 500, historyLength: 0, maxContextChars: 100
        )
        #expect(byQuestion.scope == .summaryAndRecent)
        #expect(byQuestion.transcriptBudget == 0, "the fixed parts alone already exceed the budget")

        let byHistory = ChatContextScope.resolve(
            transcriptLength: 20, summaryLength: 0, questionLength: 0, historyLength: 95, maxContextChars: 100
        )
        #expect(byHistory.scope == .summaryAndRecent)
        #expect(byHistory.transcriptBudget == 5)

        let bySummary = ChatContextScope.resolve(
            transcriptLength: 20, summaryLength: 95, questionLength: 0, historyLength: 0, maxContextChars: 100
        )
        #expect(bySummary.scope == .summaryAndRecent)
    }

    @Test("resolve never returns a negative budget")
    func resolveClampsBudgetAtZero() {
        let resolution = ChatContextScope.resolve(
            transcriptLength: 1_000, summaryLength: 5_000, questionLength: 0, historyLength: 0, maxContextChars: 100
        )
        #expect(resolution.transcriptBudget == 0)
    }

    // MARK: - build: document shape

    @Test("build emits the title exactly once, with both sections present")
    func buildEmitsTitleOnce() {
        let input = makeInput(lines: [makeLine(id: "seg_00001", startMs: 0, text: "こんにちは")])
        let output = ChatContextBuilder.build(
            input,
            resolution: ChatContextResolution(scope: .full, transcriptBudget: 10_000)
        )

        // The reason `Scope` was not extended to cover this case: `.summary` + `.transcript`
        // concatenated would print the title twice.
        #expect(output.markdown.components(separatedBy: "# 定例MTG").count - 1 == 1)
        #expect(output.markdown.contains("## サマリ"))
        #expect(output.markdown.contains("## 書き起こし"))
        #expect(output.scope == .full)
    }

    @Test("build omits the サマリ heading entirely when there is no summary")
    func buildOmitsEmptySummarySection() {
        let input = makeInput(summary: "", lines: [makeLine(id: "seg_00001", startMs: 0, text: "こんにちは")])
        let output = ChatContextBuilder.build(
            input,
            resolution: ChatContextResolution(scope: .full, transcriptBudget: 10_000)
        )

        #expect(!output.markdown.contains("## サマリ"))
        #expect(output.markdown.contains("# 定例MTG"))
        #expect(output.markdown.contains("こんにちは"))
    }

    @Test("build labels a demoted transcript section as 直近")
    func buildLabelsDemotedTranscript() {
        let input = makeInput(lines: [makeLine(id: "seg_00001", startMs: 0, text: "こんにちは")])
        let output = ChatContextBuilder.build(
            input,
            resolution: ChatContextResolution(scope: .summaryAndRecent, transcriptBudget: 10_000)
        )

        #expect(output.markdown.contains("## 書き起こし（直近）"))
        #expect(output.scope == .summaryAndRecent)
    }

    @Test("build formats each line exactly as TranscriptMarkdownRenderer.renderLine does")
    func buildMatchesRenderLineFormatting() {
        let line = makeLine(id: "seg_00001", startMs: 5_000, speakerName: "田中さん", text: "本文", isRawFallback: true)
        let input = makeInput(summary: "", lines: [line])

        let output = ChatContextBuilder.build(
            input,
            resolution: ChatContextResolution(scope: .full, transcriptBudget: 10_000)
        )

        let expected = TranscriptMarkdownRenderer.renderLine(line, meta: makeMeta())
        #expect(output.markdown.contains(expected))
        #expect(expected.hasSuffix(" *(raw)*"))
    }

    // MARK: - build: truncation

    @Test("build keeps the newest whole lines and never cuts one in half")
    func buildTruncatesWholeLinesFromTheTail() {
        let lines = (1...5).map { index in
            makeLine(id: String(format: "seg_%05d", index), startMs: index * 1_000, text: "発言\(index)")
        }
        let rendered = lines.map { TranscriptMarkdownRenderer.renderLine($0, meta: makeMeta()) }
        // Room for the last two lines and their separator, one character short of a third.
        let budget = rendered[3].count + rendered[4].count + 2

        let output = ChatContextBuilder.build(
            makeInput(summary: "", lines: lines),
            resolution: ChatContextResolution(scope: .summaryAndRecent, transcriptBudget: budget)
        )

        #expect(output.markdown.contains("発言4"))
        #expect(output.markdown.contains("発言5"))
        #expect(!output.markdown.contains("発言3"), "a line that does not fit whole is dropped, not truncated")
        #expect(!output.markdown.contains("発言1"))
        // Every retained line still carries its complete `**HH:MM:SS 話者**` prefix -- half a line
        // would break the tie between text and speaker.
        #expect(output.markdown.contains(rendered[4]))
    }

    @Test("build drops the transcript heading too when the budget is 0")
    func buildOmitsTranscriptSectionAtZeroBudget() {
        let input = makeInput(lines: [makeLine(id: "seg_00001", startMs: 0, text: "こんにちは")])
        let output = ChatContextBuilder.build(
            input,
            resolution: ChatContextResolution(scope: .summaryAndRecent, transcriptBudget: 0)
        )

        #expect(!output.markdown.contains("書き起こし"))
        #expect(output.markdown.contains("## サマリ"), "the summary is never trimmed -- resolve already counted it whole")
    }

    // MARK: - measure

    @Test("measure's transcriptLength equals the actual rendered transcript body of a .full build")
    func measureMatchesTheBuiltTranscriptBody() {
        let lines = (1...4).map { index in
            makeLine(id: String(format: "seg_%05d", index), startMs: index * 1_000, text: "発言\(index)")
        }
        let input = makeInput(summary: "", lines: lines)

        let measured = ChatContextBuilder.measure(input)
        let output = ChatContextBuilder.build(
            input,
            resolution: ChatContextResolution(scope: .full, transcriptBudget: measured.transcriptLength)
        )

        // Counting one way and rendering another would let the budget drift out of sync with the
        // real prompt with nothing failing loudly, which is why both go through `renderedLines`.
        let body = try? #require(output.markdown.components(separatedBy: "## 書き起こし\n\n").last)
        #expect(body?.count == measured.transcriptLength)
        #expect(measured.summaryLength == 0)
    }

    @Test("measure's summaryLength is the summary Markdown's own length")
    func measureReportsSummaryLength() {
        let measured = ChatContextBuilder.measure(makeInput(summary: "サマリ本文"))
        #expect(measured.summaryLength == "サマリ本文".count)
        #expect(measured.transcriptLength == 0)
    }
}
