import Foundation
import Testing

@testable import Kikimi

// MARK: - RecordingChatLLM

/// Records the request it was handed and answers with a canned `{"answer": ...}` payload, so these
/// tests assert on what `ChatRunner` *builds* without any LLM involvement. `actor` so the recorded
/// request is race-free.
private actor RecordingChatLLM: LLMCompleting {
    private(set) var receivedRequests: [LLMRequest] = []
    var answer = "回答本文"
    var usage = LLMUsage.zero
    var respondedModel: String?

    init(answer: String = "回答本文", usage: LLMUsage = .zero, respondedModel: String? = nil) {
        self.answer = answer
        self.usage = usage
        self.respondedModel = respondedModel
    }

    func complete<T: Decodable & Sendable>(_ request: LLMRequest) async throws -> LLMResult<T> {
        receivedRequests.append(request)
        let encoded = try JSONEncoder().encode(["answer": answer])
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return LLMResult(value: try decoder.decode(T.self, from: encoded), usage: usage, respondedModel: respondedModel)
    }

    func completeRaw(_ request: LLMRequest) async throws -> LLMResult<Data> {
        receivedRequests.append(request)
        return LLMResult(value: try JSONEncoder().encode(["answer": answer]), usage: usage, respondedModel: respondedModel)
    }
}

// MARK: - ChatRunnerTests

/// Layer 1 coverage for `ChatRunner` (`docs/design/38-session-chat.md` §7). Fixtures are real
/// temp-directory sessions written through `SessionHandle`'s own API, the same way
/// `TranscriptMarkdownSourceTests` builds them -- the runner reads the session through that adapter,
/// so hand-written JSON would test a different path than production takes.
@Suite("ChatRunner")
struct ChatRunnerTests {
    // MARK: - Fixtures

    /// `runOneQuestion`'s default `promptBodyProvider` return value. A fixed sentinel string rather
    /// than `ChatPromptBuilder`/`PromptSpec` text -- these tests only need to prove `ChatRunner`
    /// forwards whatever `promptBodyProvider` returns into `LLMRequest.system` on every call
    /// (`docs/design/42-prompt-overrides.md` §4.3: "chat: 送信ごとに system が変わっても実害なし"),
    /// not what that text says.
    private static let testSystemPrompt = "テスト用システムプロンプト"

    private func makeTemporaryDirectory(prefix: String) -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(prefix)-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func makeVoiceprintStore() -> (store: VoiceprintStore, fileURL: URL) {
        let fileURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("ChatRunnerTests-voiceprints-\(UUID().uuidString).json")
        return (VoiceprintStore(fileURL: fileURL), fileURL)
    }

    private func makeSessionHandle(directory: URL) -> SessionHandle {
        let meta = SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: "定例MTG",
            titleAutoGenerated: true,
            titleAutoNamedOnce: true,
            titleProposal: nil,
            state: .ended,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_100),
            endedAt: Date(timeIntervalSince1970: 1_751_002_822),
            durationMs: 2_722_000,
            recordings: [
                RecordingSegment(
                    index: 0,
                    startedAt: Date(timeIntervalSince1970: 1_751_000_100),
                    endedAt: Date(timeIntervalSince1970: 1_751_002_822),
                    startMsOffset: 0
                )
            ],
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
        return SessionHandle(directoryURL: directory, meta: meta)
    }

    private func makeTurn(_ id: String, _ role: ChatRole, _ text: String, error: String? = nil) -> ChatTurn {
        ChatTurn(
            id: id,
            role: role,
            text: text,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            error: error
        )
    }

    /// Builds a session with `segmentCount` transcript lines, runs one question through a
    /// `ChatRunner`, and hands back both the answer and the request the LLM saw.
    private func runOneQuestion(
        prefix: String,
        segmentCount: Int,
        segmentText: String = "これはテスト発言です。",
        summary: String? = nil,
        history: [ChatTurn] = [],
        question: String = "決まったことは？",
        config: ChatConfig = .default,
        llm: RecordingChatLLM = RecordingChatLLM(),
        promptBodyProvider: @escaping @Sendable (PromptID) -> String = { _ in ChatRunnerTests.testSystemPrompt }
    ) async throws -> (answer: ChatAnswer, request: LLMRequest) {
        let sessionDir = makeTemporaryDirectory(prefix: prefix)
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)

        for index in 0..<segmentCount {
            _ = try await handle.appendTranscriptSegment(
                source: .mic,
                startMs: index * 1_000,
                endMs: index * 1_000 + 900,
                text: "\(segmentText)#\(index)",
                confidence: 0.9
            )
        }
        if let summary {
            try await handle.writeText(summary, to: .summaryMarkdown)
        }

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }

        let runner = ChatRunner(
            llm: llm,
            source: TranscriptMarkdownSource(diarization: .default, voiceprintStore: voiceprintStore),
            config: config,
            promptBodyProvider: promptBodyProvider
        )
        let answer = try await runner.ask(question: question, history: history, sessionHandle: handle)
        let request = try #require(await llm.receivedRequests.last)
        return (answer, request)
    }

    // MARK: - (a) history trimming

    @Test("history is cut to historyTurns / 2 round trips")
    func historyIsTrimmedToConfiguredPairs() async throws {
        let history = (1...5).flatMap { index in
            [makeTurn("u\(index)", .user, "質問\(index)"), makeTurn("a\(index)", .assistant, "回答\(index)")]
        }

        let result = try await runOneQuestion(
            prefix: "ChatRunnerTests-a",
            segmentCount: 2,
            history: history,
            config: ChatConfig(model: "test-model", maxContextChars: 120_000, historyTurns: 4, timeoutSeconds: 30)
        )

        let messages = try #require(result.request.messages)
        // 2 for the context pair + 4 history turns.
        #expect(messages.count == 6)
        #expect(messages.map(\.text).contains("質問4"))
        #expect(messages.map(\.text).contains("回答5"))
        #expect(!messages.map(\.text).contains("質問3"), "older pairs are dropped from the prompt")
    }

    // MARK: - (b) failed turns never reach the prompt

    @Test("a failed turn and its question are excluded from the prompt")
    func failedTurnsAreExcludedFromThePrompt() async throws {
        let history = [
            makeTurn("u1", .user, "失敗した質問"),
            makeTurn("a1", .assistant, "", error: "timed out"),
            makeTurn("u2", .user, "成功した質問"),
            makeTurn("a2", .assistant, "成功した回答")
        ]

        let result = try await runOneQuestion(prefix: "ChatRunnerTests-b", segmentCount: 2, history: history)

        let texts = try #require(result.request.messages).map(\.text)
        #expect(texts.contains("成功した質問"))
        #expect(!texts.contains("失敗した質問"))
        #expect(texts.count.isMultiple(of: 2), "roles must still alternate after the exclusion")
    }

    // MARK: - (c) demotion

    @Test("a transcript past the budget demotes to summaryAndRecent and only carries its tail")
    func longTranscriptDemotes() async throws {
        let result = try await runOneQuestion(
            prefix: "ChatRunnerTests-c",
            segmentCount: 40,
            summary: "サマリ本文",
            // Small enough that 40 lines cannot fit, large enough that a couple can.
            config: ChatConfig(model: "test-model", maxContextChars: 400, historyTurns: 6, timeoutSeconds: 30)
        )

        #expect(result.answer.contextScope == .summaryAndRecent)
        let context = try #require(result.request.messages?.first?.text)
        #expect(context.contains("## 書き起こし（直近）"))
        #expect(context.contains("サマリ本文"), "the summary survives demotion -- only the transcript is trimmed")
        #expect(context.contains("#39"), "the newest lines are the ones kept")
        #expect(!context.contains("#0"))
    }

    @Test("a transcript inside the budget stays .full")
    func shortTranscriptStaysFull() async throws {
        let result = try await runOneQuestion(prefix: "ChatRunnerTests-c2", segmentCount: 3, summary: "サマリ本文")

        #expect(result.answer.contextScope == .full)
        let context = try #require(result.request.messages?.first?.text)
        #expect(context.contains("## 書き起こし"))
        #expect(!context.contains("（直近）"))
        #expect(context.contains("#0"))
    }

    // MARK: - (d) usage passthrough

    @Test("usage and the responded model reach ChatAnswer")
    func usageReachesTheAnswer() async throws {
        let usage = LLMUsage(
            inputTokens: 1_200,
            outputTokens: 300,
            cacheReadInputTokens: 40,
            cacheCreationInputTokens: 10,
            totalCostUSD: 0.0031
        )
        let llm = RecordingChatLLM(answer: "## 決定事項", usage: usage, respondedModel: "claude-haiku-4-5-actual")

        let result = try await runOneQuestion(prefix: "ChatRunnerTests-d", segmentCount: 2, llm: llm)

        #expect(result.answer.markdown == "## 決定事項")
        #expect(result.answer.usage == usage)
        #expect(result.answer.model == "claude-haiku-4-5-actual")
    }

    @Test("the requested model is reported when the backend names none")
    func fallsBackToRequestedModel() async throws {
        let result = try await runOneQuestion(
            prefix: "ChatRunnerTests-d2",
            segmentCount: 1,
            config: ChatConfig(model: "configured-model", maxContextChars: 120_000, historyTurns: 6, timeoutSeconds: 30)
        )

        #expect(result.answer.model == "configured-model")
    }

    // MARK: - (e) request wiring

    @Test("the request carries stubKey \"chat\", the configured timeout, model, and schema")
    func requestCarriesConfiguredFields() async throws {
        let result = try await runOneQuestion(
            prefix: "ChatRunnerTests-e",
            segmentCount: 1,
            question: "決まったことは？",
            config: ChatConfig(model: "configured-model", maxContextChars: 120_000, historyTurns: 6, timeoutSeconds: 42)
        )

        // Without `stubKey`, `UsageRecordingLLM` files this call's cost under `unknown` and stub mode
        // throws `missingStructuredOutput`.
        #expect(result.request.stubKey == "chat")
        #expect(result.request.timeout == .seconds(42))
        #expect(result.request.model == "configured-model")
        #expect(result.request.schema == ChatPromptBuilder.answerSchema)
        #expect(result.request.user == "決まったことは？", "the latest question rides alone in `user`")
        #expect(result.request.system == ChatRunnerTests.testSystemPrompt)
    }

    // MARK: - (f) prompt override injection (docs/design/42-prompt-overrides.md §4.3)

    @Test("system is read from promptBodyProvider(.chat), not from ChatPromptBuilder")
    func systemComesFromPromptBodyProvider() async throws {
        let result = try await runOneQuestion(
            prefix: "ChatRunnerTests-f",
            segmentCount: 1,
            promptBodyProvider: { id in id == .chat ? "override 本文" : "unexpected id: \(id)" }
        )

        #expect(result.request.system == "override 本文")
    }

    @Test("promptBodyProvider is read fresh on every ask(), not snapshotted at init")
    func promptBodyProviderIsReadPerSend() async throws {
        let sessionDir = makeTemporaryDirectory(prefix: "ChatRunnerTests-f2")
        defer { try? FileManager.default.removeItem(at: sessionDir) }
        let handle = makeSessionHandle(directory: sessionDir)
        _ = try await handle.appendTranscriptSegment(source: .mic, startMs: 0, endMs: 900, text: "発言#0", confidence: 0.9)

        let (voiceprintStore, voiceprintFileURL) = makeVoiceprintStore()
        defer { try? FileManager.default.removeItem(at: voiceprintFileURL) }

        var currentPrompt = "1回目"
        let llm = RecordingChatLLM()
        let runner = ChatRunner(
            llm: llm,
            source: TranscriptMarkdownSource(diarization: .default, voiceprintStore: voiceprintStore),
            config: .default,
            promptBodyProvider: { _ in currentPrompt }
        )

        _ = try await runner.ask(question: "質問1", history: [], sessionHandle: handle)
        currentPrompt = "2回目"
        _ = try await runner.ask(question: "質問2", history: [], sessionHandle: handle)

        let requests = await llm.receivedRequests
        #expect(requests.count == 2)
        #expect(requests[0].system == "1回目")
        #expect(requests[1].system == "2回目", "a later ask() must see the updated prompt body, not a cached one")
    }

    @Test("an empty transcript still produces a well-formed request")
    func emptyTranscriptStillBuildsARequest() async throws {
        let result = try await runOneQuestion(prefix: "ChatRunnerTests-e2", segmentCount: 0, question: "何が決まった？")

        let context = try #require(result.request.messages?.first?.text)
        #expect(context.contains("# 定例MTG"))
        #expect(!context.contains("## 書き起こし"), "an empty section is omitted heading and all")
        #expect(result.answer.contextScope == .full)
    }
}
