import Foundation
import Testing

@testable import Kikimi

// MARK: - FakeWatcherLLM

/// Deterministic, network-free stand-in for `LLMCompleting` (mirrors `SummaryUpdaterTests.FakeLLM`'s
/// shape), scripted per `stubKey`. `WatcherRunner` only ever calls `completeRaw(_:)`
/// (`docs/design/05-watcher-runner.md` §5.1); `complete<T>` is still implemented (protocol
/// conformance) by decoding the same scripted response.
private actor FakeWatcherLLM: LLMCompleting {
    private(set) var callCounts: [String: Int] = [:]
    private(set) var receivedRequests: [LLMRequest] = []
    /// High-water mark of concurrently in-flight `completeRaw`/`complete` calls, across every
    /// `stubKey` -- a direct, non-flaky way to prove two Watchers actually overlapped in time
    /// (mirrors `RefinementQueueTests.FakeLLM.maxConcurrentCalls`), instead of asserting on wall-clock
    /// elapsed time under `swift test`'s full-suite parallel load.
    private(set) var maxConcurrentCalls = 0
    private var activeCalls = 0
    var responses: [String: String] = [:]
    var errors: [String: LLMClientError] = [:]
    var delays: [String: Duration] = [:]

    func setResponse(_ json: String, for key: String) {
        responses[key] = json
        errors[key] = nil
    }

    func setError(_ error: LLMClientError, for key: String) {
        errors[key] = error
    }

    func setDelay(_ delay: Duration, for key: String) {
        delays[key] = delay
    }

    func callCount(for key: String) -> Int {
        callCounts[key] ?? 0
    }

    func complete<T: Decodable & Sendable>(_ request: LLMRequest) async throws -> LLMResult<T> {
        let data = try await resolveData(for: request)
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return LLMResult(value: try decoder.decode(T.self, from: data), usage: .zero)
    }

    func completeRaw(_ request: LLMRequest) async throws -> LLMResult<Data> {
        LLMResult(value: try await resolveData(for: request), usage: .zero)
    }

    private func resolveData(for request: LLMRequest) async throws -> Data {
        let key = request.stubKey ?? ""
        callCounts[key, default: 0] += 1
        receivedRequests.append(request)
        activeCalls += 1
        maxConcurrentCalls = max(maxConcurrentCalls, activeCalls)
        defer { activeCalls -= 1 }

        if let delay = delays[key] {
            try? await Task.sleep(for: delay)
        }
        if let error = errors[key] {
            throw error
        }
        guard let json = responses[key], let data = json.data(using: .utf8) else {
            throw LLMClientError.missingStructuredOutput(raw: "no fake response for stubKey=\(key)")
        }
        return data
    }
}

// MARK: - EventCollector

/// Generic, race-free event sink for `for await event in runner.events` loops (mirrors the pattern
/// `RefinementQueueTests`/`SummaryUpdaterTests` use for their own event streams).
private actor EventCollector {
    private(set) var events: [WatcherEvent] = []

    func append(_ event: WatcherEvent) {
        events.append(event)
    }
}

// MARK: - Test suite

@Suite("WatcherRunner")
struct WatcherRunnerTests {
    private func makeTempSessionDirectory() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("WatcherRunnerTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func makeHandle(directory: URL) -> SessionHandle {
        SessionHandle(directoryURL: directory, meta: SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: "",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_010),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        ))
    }

    /// A minimal, always-valid Watcher definition: `schema: { source_seg_id: string }`, so tests can
    /// assert the persisted `watchers/<id>.state.json` keeps that key un-camelCased.
    private func definitionText(id: String, trigger: String = "on_manual", stateMode: String = "cumulative") -> String {
        """
        ---
        id: \(id)
        name: Test Watcher \(id)
        trigger: \(trigger)
        state_mode: \(stateMode)
        input_scope: summary
        schema:
          source_seg_id: string
        view: |
          {{source_seg_id}}
        ---

        # System

        system prompt

        # User

        {{state}}
        """
    }

    private func makeLibrary() -> WatcherLibrary {
        WatcherLibrary(presetsDirectory: FileManager.default.temporaryDirectory.appendingPathComponent("WatcherRunnerTests-empty-presets-\(UUID().uuidString)"))
    }

    /// Polls `predicate` on a short interval until it returns `true` or a timeout elapses (mirrors
    /// `RefinementQueueTests.waitUntil`/`SummaryUpdaterTests.waitUntil`).
    private func waitUntil(timeout: Duration = .seconds(10), predicate: @escaping () async -> Bool) async throws {
        let deadline = ContinuousClock.now + timeout
        while ContinuousClock.now < deadline {
            if await predicate() { return }
            try await Task.sleep(for: .milliseconds(10))
        }
        #expect(await predicate(), "condition did not become true within \(timeout)")
    }

    // MARK: - Trigger matching

    @Test("run(trigger:) only executes enabled Watchers whose declared trigger matches")
    func runOnlyExecutesMatchingTrigger() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionText(id: "watcher-a", trigger: "on_summary_update"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeText(definitionText(id: "watcher-b", trigger: "on_manual"), to: .watcherDefinition(id: "watcher-b"))
        try await handle.writeEnabledWatchers(["watcher-a", "watcher-b"])

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        await llm.setResponse("{\"source_seg_id\":\"seg_00002\"}", for: "watcher_watcher-b")

        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.run(trigger: .onSummaryUpdate)

        #expect(await llm.callCount(for: "watcher_watcher-a") == 1)
        #expect(await llm.callCount(for: "watcher_watcher-b") == 0)
    }

    @Test("runManually(id:) runs regardless of the Watcher's declared trigger")
    func runManuallyIgnoresDeclaredTrigger() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionText(id: "watcher-a", trigger: "on_session_end"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")

        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")

        #expect(await llm.callCount(for: "watcher_watcher-a") == 1)
    }

    // MARK: - state.json key preservation (§7.1)

    @Test("watchers/<id>.state.json preserves the LLM's dynamic snake_case keys unconverted")
    func stateJSONPreservesKeysUnconverted() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionText(id: "watcher-a"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00099\"}", for: "watcher_watcher-a")

        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")

        let stateText = try await handle.readText(.watcherState(id: "watcher-a"))
        #expect(stateText?.contains("\"source_seg_id\"") == true)
        #expect(stateText?.contains("sourceSegId") == false)
    }

    // MARK: - run.json (§7.2)

    @Test("a successful run persists watchers/<id>.run.json with that run's timestamp and input_scope")
    func successfulRunPersistsRunRecord() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(
            definitionTextWithInputScope(id: "watcher-a", inputScope: "summary_and_recent:12"),
            to: .watcherDefinition(id: "watcher-a")
        )
        try await handle.writeEnabledWatchers(["watcher-a"])

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")

        // Whole seconds: `run.json` is written with `dateEncodingStrategy = .iso8601`, which drops
        // sub-second precision, so a fractional timestamp would not round-trip exactly.
        let finishedAt = Date(timeIntervalSince1970: 1_700_000_000)
        let runner = WatcherRunner(
            sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001",
            now: { finishedAt }
        )
        await runner.runManually(id: "watcher-a")

        let record = try await handle.readJSON(.watcherRunRecord(id: "watcher-a"), as: WatcherRunRecord.self)
        #expect(record?.finishedAt == finishedAt)
        #expect(record?.inputScope == .summaryAndRecent(count: 12))
    }

    @Test("a failed run leaves the previous run.json untouched (it describes the state still on disk)")
    func failedRunKeepsPreviousRunRecord() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionText(id: "watcher-a"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let finishedAt = Date(timeIntervalSince1970: 1_700_000_000)
        let runner = WatcherRunner(
            sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001",
            now: { finishedAt }
        )
        await runner.runManually(id: "watcher-a")

        let collector = EventCollector()
        let collectTask = Task {
            for await event in runner.events {
                await collector.append(event)
            }
        }
        await llm.setError(.timedOut(.seconds(1)), for: "watcher_watcher-a")
        await runner.runManually(id: "watcher-a")
        try await waitUntil { await collector.events.contains { if case .failed = $0.kind { return true }; return false } }
        collectTask.cancel()

        let record = try await handle.readJSON(.watcherRunRecord(id: "watcher-a"), as: WatcherRunRecord.self)
        #expect(record?.finishedAt == finishedAt)
    }

    // MARK: - LLM failure keeps previous state (§9.1/§12)

    @Test("a failed LLM call leaves the previously-persisted state untouched and yields .failed")
    func llmFailureKeepsPreviousState() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionText(id: "watcher-a"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")
        let stateAfterSuccess = try await handle.readText(.watcherState(id: "watcher-a"))

        let collector = EventCollector()
        let collectTask = Task {
            for await event in runner.events {
                await collector.append(event)
            }
        }
        await llm.setError(.timedOut(.seconds(1)), for: "watcher_watcher-a")
        await runner.runManually(id: "watcher-a")

        try await waitUntil { await collector.events.contains { if case .failed = $0.kind { return true }; return false } }
        collectTask.cancel()

        let stateAfterFailure = try await handle.readText(.watcherState(id: "watcher-a"))
        #expect(stateAfterFailure == stateAfterSuccess)
    }

    // MARK: - Schema-edit reset (§7.1/§12)

    @Test("a persisted state that fails the current schema is reset to initial_state and yields .stateReset")
    func schemaMismatchResetsToInitialState() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        let definition = """
        ---
        id: watcher-a
        name: Test Watcher
        trigger: on_manual
        state_mode: cumulative
        input_scope: summary
        schema:
          source_seg_id: string
        initial_state: |
          {"source_seg_id": "seg_initial"}
        view: |
          {{source_seg_id}}
        ---

        # System
        system prompt

        # User
        {{state}}
        """
        try await handle.writeText(definition, to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])
        // A state.json shaped for a schema this Watcher no longer declares (missing source_seg_id).
        try await handle.writeText("{\"old_field\":\"x\"}", to: .watcherState(id: "watcher-a"))

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")

        let collector = EventCollector()
        let collectTask = Task {
            for await event in runner.events {
                await collector.append(event)
            }
        }
        await runner.runManually(id: "watcher-a")
        try await waitUntil { await collector.events.contains { if case .stateReset = $0.kind { return true }; return false } }
        collectTask.cancel()
    }

    // MARK: - Duplicate in-flight dispatch skipped (§9.2)

    @Test("a second trigger for the same Watcher while one is still in flight is skipped")
    func duplicateInFlightRunIsSkipped() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionText(id: "watcher-a"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        await llm.setDelay(.milliseconds(300), for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")

        async let first: Void = runner.runManually(id: "watcher-a")
        // Give the first call a moment to actually start (claim the in-flight flag) before firing
        // the second.
        try await Task.sleep(for: .milliseconds(50))
        async let second: Void = runner.runManually(id: "watcher-a")
        _ = await (first, second)

        // Only one of the two calls actually reached the LLM; the other was skipped while in-flight.
        #expect(await llm.callCount(for: "watcher_watcher-a") == 1)
    }

    // MARK: - Parallel independence (§9.2)

    @Test("two different Watchers triggered together run independently in parallel")
    func differentWatchersRunInParallel() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionText(id: "watcher-a", trigger: "on_summary_update"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeText(definitionText(id: "watcher-b", trigger: "on_summary_update"), to: .watcherDefinition(id: "watcher-b"))
        try await handle.writeEnabledWatchers(["watcher-a", "watcher-b"])

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        await llm.setResponse("{\"source_seg_id\":\"seg_00002\"}", for: "watcher_watcher-b")
        await llm.setDelay(.milliseconds(200), for: "watcher_watcher-a")
        await llm.setDelay(.milliseconds(200), for: "watcher_watcher-b")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")

        await runner.run(trigger: .onSummaryUpdate)

        // Direct proof of overlap (both calls were in flight at the same time), rather than a
        // wall-clock elapsed-time assertion -- the latter is flaky under `swift test`'s full-suite
        // parallel load (this suite observed >600ms elapsed for two 300ms delays under load, even
        // though the calls did genuinely overlap).
        #expect(await llm.maxConcurrentCalls == 2)
        #expect(await llm.callCount(for: "watcher_watcher-a") == 1)
        #expect(await llm.callCount(for: "watcher_watcher-b") == 1)
    }

    // MARK: - Missing/unresolvable definitions (§12)

    @Test("run(trigger:) silently skips an enabled id with no resolvable definition")
    func runSkipsUnresolvableDefinitionSilently() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeEnabledWatchers(["missing-watcher"])
        let llm = FakeWatcherLLM()
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")

        let collector = EventCollector()
        let collectTask = Task {
            for await event in runner.events {
                await collector.append(event)
            }
        }
        await runner.run(trigger: .onManual)
        try await Task.sleep(for: .milliseconds(100))
        collectTask.cancel()

        #expect(await collector.events.isEmpty)
    }

    // MARK: - `summary_and_recent:<n>` segment window (docs/design/34-simple-watchers.md §5)

    /// A definition whose `input_scope` carries an explicit `:<n>` count (§5's
    /// `WatcherInputScope.summaryAndRecent(count:)`), so `resolveRecentSegments` truncates
    /// `{{recent_segments}}` to the last `n` transcript segments rather than the unmarked default of
    /// 30.
    private func definitionTextWithRecentCount(id: String, count: Int) -> String {
        """
        ---
        id: \(id)
        name: Test Watcher \(id)
        trigger: on_manual
        state_mode: cumulative
        input_scope: summary_and_recent:\(count)
        schema:
          source_seg_id: string
        view: |
          {{source_seg_id}}
        ---

        # System

        system prompt

        # User

        {{recent_segments}}
        """
    }

    @Test("input_scope: summary_and_recent:<n> truncates {{recent_segments}} to the last n transcript segments")
    func summaryAndRecentCountTruncatesToSuffix() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionTextWithRecentCount(id: "watcher-a", count: 2), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        for index in 1...4 {
            _ = try await handle.appendTranscriptSegment(
                source: .mic,
                startMs: index * 1000,
                endMs: index * 1000 + 500,
                text: "segment \(index)",
                confidence: 1.0
            )
        }

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")

        let receivedUserPrompt = await llm.receivedRequests.last?.user ?? ""
        // Only the last 2 of the 4 appended segments (seg_00003/seg_00004) should be included.
        #expect(receivedUserPrompt.contains("seg_00003"))
        #expect(receivedUserPrompt.contains("seg_00004"))
        #expect(!receivedUserPrompt.contains("seg_00001"))
        #expect(!receivedUserPrompt.contains("seg_00002"))
    }

    /// A definition whose `# User` section is only `{{recent_segments}}`, with a caller-supplied raw
    /// `input_scope` value -- lets the remaining tests below exercise `summary`/`full_refined`/the
    /// unmarked `summary_and_recent` default without duplicating `definitionTextWithRecentCount`'s
    /// `:<n>`-suffixed form.
    private func definitionTextWithInputScope(id: String, inputScope: String) -> String {
        """
        ---
        id: \(id)
        name: Test Watcher \(id)
        trigger: on_manual
        state_mode: cumulative
        input_scope: \(inputScope)
        schema:
          source_seg_id: string
        view: |
          {{source_seg_id}}
        ---

        # System

        system prompt

        # User

        {{recent_segments}}
        """
    }

    /// Mirrors `SummaryUpdaterTests.makeRefinedSegment(...)`: builds a `RefinedSegment` for direct
    /// `appendRefinedSegment` calls without pulling in every other field this suite doesn't care about.
    private func makeRefinedSegment(
        id: String,
        startMs: Int = 0,
        endMs: Int = 1_000,
        refinedText: String?,
        sourceSegIds: [String] = []
    ) -> RefinedSegment {
        RefinedSegment(
            id: id,
            startMs: startMs,
            endMs: endMs,
            speaker: .mic,
            rawText: "raw text",
            refinedText: refinedText,
            error: nil,
            refinedAt: Date(timeIntervalSince1970: 1_751_000_020),
            model: "claude-haiku-4-5-20251001",
            batchId: "batch_00001",
            sourceSegIds: sourceSegIds
        )
    }

    @Test("input_scope: summary resolves {{recent_segments}} to empty even when transcript segments exist")
    func summaryScopeYieldsNoRecentSegments() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionTextWithInputScope(id: "watcher-a", inputScope: "summary"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        for index in 1...3 {
            _ = try await handle.appendTranscriptSegment(
                source: .mic,
                startMs: index * 1000,
                endMs: index * 1000 + 500,
                text: "segment \(index)",
                confidence: 1.0
            )
        }

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")

        let receivedUserPrompt = await llm.receivedRequests.last?.user ?? ""
        #expect(receivedUserPrompt.isEmpty)
        #expect(!receivedUserPrompt.contains("seg_"))
    }

    @Test("input_scope: full_refined includes every appended segment without truncation")
    func fullRefinedScopeIncludesEverySegment() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionTextWithInputScope(id: "watcher-a", inputScope: "full_refined"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        // More than the `summary_and_recent` default window (30), to prove `full_refined` does not
        // truncate at all.
        for index in 1...35 {
            _ = try await handle.appendTranscriptSegment(
                source: .mic,
                startMs: index * 1000,
                endMs: index * 1000 + 500,
                text: "segment \(index)",
                confidence: 1.0
            )
        }

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")

        let receivedUserPrompt = await llm.receivedRequests.last?.user ?? ""
        #expect(receivedUserPrompt.contains("seg_00001"))
        #expect(receivedUserPrompt.contains("seg_00035"))
    }

    @Test("input_scope: summary_and_recent without a count suffix truncates to the default window of 30 segments")
    func summaryAndRecentUnmarkedDefaultsToThirtySegmentWindow() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionTextWithInputScope(id: "watcher-a", inputScope: "summary_and_recent"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        for index in 1...35 {
            _ = try await handle.appendTranscriptSegment(
                source: .mic,
                startMs: index * 1000,
                endMs: index * 1000 + 500,
                text: "segment \(index)",
                confidence: 1.0
            )
        }

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")

        let receivedUserPrompt = await llm.receivedRequests.last?.user ?? ""
        // Segments 1-5 fall outside the last-30 window; segments 6-35 (30 of them) are inside it.
        #expect(!receivedUserPrompt.contains("seg_00001"))
        #expect(!receivedUserPrompt.contains("seg_00005"))
        #expect(receivedUserPrompt.contains("seg_00006"))
        #expect(receivedUserPrompt.contains("seg_00035"))
    }

    @Test("recent_segments prefers a segment's refined text over its raw transcript text")
    func recentSegmentsPrefersRefinedTextOverRaw() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionTextWithInputScope(id: "watcher-a", inputScope: "full_refined"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        let segment = try await handle.appendTranscriptSegment(source: .mic, startMs: 1_000, endMs: 1_500, text: "raw content", confidence: 1.0)
        try await handle.appendRefinedSegment(makeRefinedSegment(id: segment.id, startMs: 1_000, refinedText: "refined content"))

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")

        let receivedUserPrompt = await llm.receivedRequests.last?.user ?? ""
        #expect(receivedUserPrompt.contains("refined content"))
        #expect(!receivedUserPrompt.contains("raw content"))
    }

    @Test("recent_segments excludes a segment entirely when its refined text is the empty string")
    func recentSegmentsExcludesEmptyRefinedText() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionTextWithInputScope(id: "watcher-a", inputScope: "full_refined"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        let dropped = try await handle.appendTranscriptSegment(source: .mic, startMs: 1_000, endMs: 1_500, text: "excluded raw text", confidence: 1.0)
        try await handle.appendRefinedSegment(makeRefinedSegment(id: dropped.id, startMs: 1_000, refinedText: ""))
        let kept = try await handle.appendTranscriptSegment(source: .mic, startMs: 2_000, endMs: 2_500, text: "included raw text", confidence: 1.0)

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")

        let receivedUserPrompt = await llm.receivedRequests.last?.user ?? ""
        #expect(!receivedUserPrompt.contains(dropped.id))
        #expect(!receivedUserPrompt.contains("excluded raw text"))
        #expect(receivedUserPrompt.contains(kept.id))
        #expect(receivedUserPrompt.contains("included raw text"))
    }

    @Test("recent_segments resolves a merged unit's non-leading source_seg_id to the same refined text, not a raw fallback (design 03 §15.2.5)")
    func recentSegmentsExpandsMergedSourceSegIds() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(definitionTextWithInputScope(id: "watcher-a", inputScope: "full_refined"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        let first = try await handle.appendTranscriptSegment(source: .mic, startMs: 1_000, endMs: 1_500, text: "raw 0", confidence: 1.0)
        let second = try await handle.appendTranscriptSegment(source: .mic, startMs: 1_500, endMs: 2_000, text: "raw 1", confidence: 1.0)
        // One merged derived unit covering both raw segments -- `second.id` never appears as a
        // top-level `id` in refined.jsonl, only inside `source_seg_ids`.
        try await handle.appendRefinedSegment(makeRefinedSegment(
            id: first.id,
            startMs: first.startMs,
            endMs: second.endMs,
            refinedText: "整形済み結合テキスト",
            sourceSegIds: [first.id, second.id]
        ))

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"source_seg_id\":\"seg_00001\"}", for: "watcher_watcher-a")
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")
        await runner.runManually(id: "watcher-a")

        let receivedUserPrompt = await llm.receivedRequests.last?.user ?? ""
        #expect(receivedUserPrompt.contains("整形済み結合テキスト"))
        #expect(!receivedUserPrompt.contains("raw 1"), "second (covered, non-leading) must not fall back to its own raw text")
    }

    // MARK: - simpleWatcherTemplate session-start fixity (`docs/design/42-prompt-overrides.md` §4.3/§5.2)

    /// A minimal, always-valid `kind: simple` definition -- the runner desugars this through
    /// `SimpleWatcherSpec.desugar(promptTemplate:)`, embedding `prompt` into whatever template this
    /// runner was constructed with.
    private func simpleDefinitionText(id: String, prompt: String) -> String {
        """
        ---
        kind: simple
        id: \(id)
        name: Simple Test Watcher
        trigger: on_manual
        input_scope: summary
        ---

        \(prompt)
        """
    }

    @Test("a kind: simple Watcher's .md edit mid-recording is reflected on the next manual run, while the systemPrompt's surrounding template stays this runner's own init-time snapshot")
    func simpleWatcherTemplateStaysFixedAcrossReparsedMdEdits() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        try await handle.writeText(simpleDefinitionText(id: "watcher-a", prompt: "最初の観点"), to: .watcherDefinition(id: "watcher-a"))
        try await handle.writeEnabledWatchers(["watcher-a"])

        let llm = FakeWatcherLLM()
        await llm.setResponse("{\"markdown\":\"result\"}", for: "watcher_watcher-a")

        let customTemplate = "CUSTOM PREAMBLE\n{{viewpoint}}\nCUSTOM FOOTER"
        let runner = WatcherRunner(
            sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001",
            simpleWatcherTemplate: customTemplate
        )
        await runner.runManually(id: "watcher-a")
        let firstSystemPrompt = await llm.receivedRequests.last?.system ?? ""
        #expect(firstSystemPrompt == "CUSTOM PREAMBLE\n最初の観点\nCUSTOM FOOTER")

        // kikimi.md 9 章: "Recording 中の .md 編集は次回発火から即反映" -- simulate a live edit.
        try await handle.writeText(simpleDefinitionText(id: "watcher-a", prompt: "更新後の観点"), to: .watcherDefinition(id: "watcher-a"))
        await runner.runManually(id: "watcher-a")
        let secondSystemPrompt = await llm.receivedRequests.last?.system ?? ""

        // The viewpoint reflects the edit immediately (next-trigger reparse)...
        #expect(secondSystemPrompt == "CUSTOM PREAMBLE\n更新後の観点\nCUSTOM FOOTER")
        // ...but the template wrapping it is still this runner's own construction-time snapshot,
        // fixed for the session's duration (§5.2's "System は実行間で完全固定").
        #expect(secondSystemPrompt.hasPrefix("CUSTOM PREAMBLE\n"))
        #expect(secondSystemPrompt.hasSuffix("\nCUSTOM FOOTER"))
    }

    @Test("runManually(id:) yields .failed for an unresolvable definition")
    func runManuallyFailsForUnresolvableDefinition() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = makeHandle(directory: directory)
        let llm = FakeWatcherLLM()
        let runner = WatcherRunner(sessionHandle: handle, llm: llm, library: makeLibrary(), defaultModel: "claude-haiku-4-5-20251001")

        let collector = EventCollector()
        let collectTask = Task {
            for await event in runner.events {
                await collector.append(event)
            }
        }
        await runner.runManually(id: "missing-watcher")
        try await waitUntil { await collector.events.contains { if case .failed = $0.kind { return true }; return false } }
        collectTask.cancel()
    }
}
