import Foundation
import Testing

@testable import Kikimi

/// Layer 1 coverage for `WatcherLibrary` (`docs/design/05-watcher-runner.md` §3): session-local vs.
/// preset resolution order, preset listing, fork, and promote.
@Suite("WatcherLibrary")
struct WatcherLibraryTests {
    private func makeTempDirectory(prefix: String) -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(prefix)-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func makeSessionHandle(directory: URL) -> SessionHandle {
        SessionHandle(directoryURL: directory, meta: SessionMeta(
            id: "2026-07-01T14-30-00_a1b2c3d4",
            title: "",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_010),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        ))
    }

    private func writePresetFile(_ text: String, id: String, in presetsDirectory: URL) throws {
        try FileManager.default.createDirectory(at: presetsDirectory, withIntermediateDirectories: true)
        try text.write(to: presetsDirectory.appendingPathComponent("\(id).md"), atomically: true, encoding: .utf8)
    }

    // MARK: - resolveDefinitionText priority (§3)

    @Test("resolveDefinitionText prefers a session-local definition over a same-id preset")
    func resolvesSessionLocalOverPreset() async throws {
        let sessionDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-session")
        let presetsDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-presets")
        defer {
            try? FileManager.default.removeItem(at: sessionDirectory)
            try? FileManager.default.removeItem(at: presetsDirectory)
        }
        let handle = makeSessionHandle(directory: sessionDirectory)
        try await handle.writeText("session-local text", to: .watcherDefinition(id: "pre-check"))
        try writePresetFile("preset text", id: "pre-check", in: presetsDirectory)

        let library = WatcherLibrary(presetsDirectory: presetsDirectory)
        let resolved = try await library.resolveDefinitionText(id: "pre-check", sessionHandle: handle)

        #expect(resolved?.text == "session-local text")
        #expect(resolved?.origin == .sessionLocal)
    }

    @Test("resolveDefinitionText falls back to a preset when no session-local definition exists")
    func resolvesPresetWhenNoSessionLocal() async throws {
        let sessionDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-session")
        let presetsDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-presets")
        defer {
            try? FileManager.default.removeItem(at: sessionDirectory)
            try? FileManager.default.removeItem(at: presetsDirectory)
        }
        try writePresetFile("preset text", id: "pre-check", in: presetsDirectory)
        let library = WatcherLibrary(presetsDirectory: presetsDirectory)
        let handle = makeSessionHandle(directory: sessionDirectory)

        let resolved = try await library.resolveDefinitionText(id: "pre-check", sessionHandle: handle)

        #expect(resolved?.text == "preset text")
        #expect(resolved?.origin == .preset)
    }

    @Test("resolveDefinitionText returns nil when neither a session-local nor a preset definition exists")
    func resolvesNilWhenMissingEntirely() async throws {
        let sessionDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-session")
        let presetsDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-presets")
        defer {
            try? FileManager.default.removeItem(at: sessionDirectory)
            try? FileManager.default.removeItem(at: presetsDirectory)
        }
        let library = WatcherLibrary(presetsDirectory: presetsDirectory)
        let handle = makeSessionHandle(directory: sessionDirectory)

        let resolved = try await library.resolveDefinitionText(id: "missing-id", sessionHandle: handle)

        #expect(resolved == nil)
    }

    // MARK: - listPresetIds

    @Test("listPresetIds returns sorted ids, filtering non-.md files and invalid names")
    func listPresetIdsFiltersAndSorts() throws {
        let presetsDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-presets")
        defer { try? FileManager.default.removeItem(at: presetsDirectory) }
        try writePresetFile("a", id: "zebra", in: presetsDirectory)
        try writePresetFile("b", id: "alpha", in: presetsDirectory)
        try "not a watcher".write(to: presetsDirectory.appendingPathComponent("notes.txt"), atomically: true, encoding: .utf8)
        try "invalid".write(to: presetsDirectory.appendingPathComponent("has space.md"), atomically: true, encoding: .utf8)

        let library = WatcherLibrary(presetsDirectory: presetsDirectory)

        #expect(library.listPresetIds() == ["alpha", "zebra"])
    }

    @Test("listPresetIds returns an empty list when the presets directory does not exist")
    func listPresetIdsEmptyWhenDirectoryMissing() {
        let library = WatcherLibrary(presetsDirectory: FileManager.default.temporaryDirectory.appendingPathComponent("nonexistent-\(UUID().uuidString)"))
        #expect(library.listPresetIds().isEmpty)
    }

    // MARK: - presetText

    @Test("presetText returns nil for an id with no matching file")
    func presetTextNilForMissingId() {
        let presetsDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-presets")
        defer { try? FileManager.default.removeItem(at: presetsDirectory) }
        let library = WatcherLibrary(presetsDirectory: presetsDirectory)
        #expect(library.presetText(id: "missing") == nil)
    }

    // MARK: - fork (§3, kikimi.md 9 章 "Preset を fork")

    @Test("fork copies a preset's text into the session-local watchers/<id>.md")
    func forkCopiesPresetIntoSessionLocal() async throws {
        let sessionDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-session")
        let presetsDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-presets")
        defer {
            try? FileManager.default.removeItem(at: sessionDirectory)
            try? FileManager.default.removeItem(at: presetsDirectory)
        }
        try writePresetFile("preset content", id: "pre-check", in: presetsDirectory)
        let library = WatcherLibrary(presetsDirectory: presetsDirectory)
        let handle = makeSessionHandle(directory: sessionDirectory)

        try await library.fork(id: "pre-check", into: handle)

        let sessionLocalText = try await handle.readText(.watcherDefinition(id: "pre-check"))
        #expect(sessionLocalText == "preset content")
    }

    @Test("fork throws presetNotFound when the preset does not exist")
    func forkThrowsWhenPresetMissing() async throws {
        let sessionDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-session")
        let presetsDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-presets")
        defer {
            try? FileManager.default.removeItem(at: sessionDirectory)
            try? FileManager.default.removeItem(at: presetsDirectory)
        }
        let library = WatcherLibrary(presetsDirectory: presetsDirectory)
        let handle = makeSessionHandle(directory: sessionDirectory)

        await #expect(throws: WatcherLibraryError.presetNotFound("missing")) {
            try await library.fork(id: "missing", into: handle)
        }
    }

    // MARK: - promote (§3, kikimi.md 9 章 "Session-local Watcher の Preset への昇格")

    @Test("promote writes a session-local definition out to the preset library, overwriting any existing preset")
    func promoteWritesSessionLocalToPresetOverwritingExisting() async throws {
        let sessionDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-session")
        let presetsDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-presets")
        defer {
            try? FileManager.default.removeItem(at: sessionDirectory)
            try? FileManager.default.removeItem(at: presetsDirectory)
        }
        try writePresetFile("old preset content", id: "pre-check", in: presetsDirectory)
        let library = WatcherLibrary(presetsDirectory: presetsDirectory)
        let handle = makeSessionHandle(directory: sessionDirectory)
        try await handle.writeText("new session-local content", to: .watcherDefinition(id: "pre-check"))

        try await library.promote(id: "pre-check", from: handle)

        #expect(library.presetText(id: "pre-check") == "new session-local content")
    }

    @Test("promote throws sessionLocalNotFound when no session-local definition exists")
    func promoteThrowsWhenSessionLocalMissing() async throws {
        let sessionDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-session")
        let presetsDirectory = makeTempDirectory(prefix: "WatcherLibraryTests-presets")
        defer {
            try? FileManager.default.removeItem(at: sessionDirectory)
            try? FileManager.default.removeItem(at: presetsDirectory)
        }
        let library = WatcherLibrary(presetsDirectory: presetsDirectory)
        let handle = makeSessionHandle(directory: sessionDirectory)

        await #expect(throws: WatcherLibraryError.sessionLocalNotFound("missing")) {
            try await library.promote(id: "missing", from: handle)
        }
    }
}
