import Foundation

// MARK: - MeetingWorkspaceViewModel.AudioCaptureFactory / TranscriptPipelineFactory defaults
//
// Split into its own file (alongside `MeetingWorkspaceViewModel.swift`'s other extensions, e.g.
// `+Prep.swift`/`+AudioInput.swift`) to keep `MeetingWorkspaceViewModel.swift` under the project's
// `file_length` lint limit. `defaultAudioCaptureFactory` lives in
// `MeetingWorkspaceViewModel+AudioInput.swift` instead of here: it constructs `AudioCapture` from
// an `AudioInputSelection`, so it stayed alongside the rest of that feature's logic.

extension MeetingWorkspaceViewModel {
    /// The stand-in `meta` `init` seeds before `hydrateFromSessionHandle()` replaces it with the
    /// real one. `SessionHandle.meta` is an actor `var` and cannot be read synchronously from a
    /// non-`async` `init` (see `init`'s own doc comment), so this fills the gap for the moment
    /// between construction and the first hydration. Moved here from the main file for
    /// `file_length`; `internal` rather than `private` because Swift's `private` does not span
    /// files.
    static func placeholderMeta(sessionId: String) -> SessionMeta {
        SessionMeta(
            id: sessionId,
            title: "",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .draft,
            createdAt: Date(),
            startedAt: nil,
            endedAt: nil,
            durationMs: 0,
            recordings: [],
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: ""
        )
    }

    /// Production default for `chatRunnerFactory`: a real `ChatRunner` over `LLMClient.shared` and
    /// `AppConfig.shared.data.chat` (`docs/design/38-session-chat.md` §3.3). `KIKIMI_STUB_LLM` is
    /// handled inside `LLMClient`, not here, same as the factories below.
    ///
    /// The `TranscriptMarkdownSource` is built exactly as `defaultWikiExporter()` builds its own, so
    /// a chat answer quotes the same speaker names the export and the copy feature produce.
    ///
    /// `docs/design/16-llm-usage-stats.md` section 3: wrapped in `UsageRecordingLLM`, so chat cost
    /// lands in `llm_usage.jsonl` (as `purpose: "chat"`, via `LLMRequest.stubKey`) without
    /// `ChatRunner` knowing the decorator is there.
    @MainActor
    static func defaultChatRunnerFactory(_ sessionHandle: SessionHandle) -> ChatRunner {
        let chatConfig = AppConfig.shared.data.chat
        return ChatRunner(
            llm: UsageRecordingLLM(base: LLMClient.shared, sessionHandle: sessionHandle),
            source: TranscriptMarkdownSource(
                diarization: AppConfig.shared.data.diarization,
                voiceprintStore: .shared
            ),
            config: chatConfig,
            resolvedModel: ModelResolver.resolve(
                candidates: [chatConfig.model],
                config: AppConfig.shared.data.llm,
                availableProviders: LLMClient.shared.availableProviders
            )
        )
    }

    /// Production default for `transcriptPipelineFactory`: a real `TranscriptPipeline` with an
    /// `SttEngineConfig` whose `language`/`chunkMs`/`segmentIdleTimeout`/`maxSegmentCharacters`/
    /// `twoPassDecode` all come from `AppConfig.shared.data.stt` (`docs/design/11-streaming-stt.md`
    /// section 3.9; `twoPassDecode` per `docs/design/33-meeting-two-pass-decode.md` §4/MT10), rather
    /// than `SttEngineConfig`'s own struct-literal defaults. `twoPassDecode` is a recording-start
    /// snapshot like the other fields here -- a mid-recording Settings toggle only takes effect on
    /// the next recording (MT10).
    ///
    /// - Parameter startMsOffset: The recording segment's `RecordingSegment.startMsOffset`
    ///   (kikimi.md 5/6 章), forwarded unchanged to `TranscriptPipeline.init`.
    static func defaultTranscriptPipelineFactory(_ sessionHandle: SessionHandle, _ startMsOffset: Int) -> RecordingTranscriptPipelining {
        let sttConfig = AppConfig.shared.data.stt
        var engineConfig = SttEngineConfig()
        engineConfig.language = sttConfig.language
        engineConfig.chunkMs = sttConfig.chunkMs
        engineConfig.segmentIdleTimeout = sttConfig.segmentIdleTimeout
        engineConfig.maxSegmentCharacters = sttConfig.maxSegmentCharacters
        engineConfig.twoPassDecode = sttConfig.twoPassDecode
        return TranscriptPipeline(sessionHandle: sessionHandle, startMsOffset: startMsOffset, config: engineConfig)
    }

    /// Production default for `summaryUpdaterFactory`: a real `SummaryUpdater` using `LLMClient
    /// .shared` and `AppConfig.shared.data.summary` (`docs/design/04-summary-updater.md` section 7/§8,
    /// same "config.yaml 対応で先行させる" rationale `defaultRefinementQueueFactory` below documents for
    /// `AppConfig.shared.data.refinement`). `KIKIMI_STUB_LLM` is handled internally by `LLMClient`, not
    /// here (`Kikimi/LLM/LLMClient.swift`).
    ///
    /// `docs/design/16-llm-usage-stats.md` section 3: `LLMClient.shared` is wrapped in
    /// `UsageRecordingLLM` so every summary/title call this session makes gets its token usage
    /// recorded to `llm_usage.jsonl`, without `SummaryUpdater` itself knowing that decorator exists.
    @MainActor
    static func defaultSummaryUpdaterFactory(_ sessionHandle: SessionHandle) -> SummaryUpdater {
        let summaryConfig = AppConfig.shared.data.summary
        let llmConfig = AppConfig.shared.data.llm
        let availableProviders = LLMClient.shared.availableProviders
        return SummaryUpdater(
            sessionHandle: sessionHandle,
            llm: UsageRecordingLLM(base: LLMClient.shared, sessionHandle: sessionHandle),
            config: summaryConfig,
            resolvedModel: ModelResolver.resolve(
                candidates: [summaryConfig.model],
                config: llmConfig,
                availableProviders: availableProviders
            ),
            // §7's row for summary finalPass: `resolve(candidates: [config.finalModel, config.model])`
            // -- a two-element candidate list, never `finalModel ?? model` collapsed first (§3.2).
            resolvedFinalModel: ModelResolver.resolve(
                candidates: [summaryConfig.finalModel, summaryConfig.model],
                config: llmConfig,
                availableProviders: availableProviders
            )
        )
    }

    /// Production default for `refinementQueueFactory`: a real `RefinementQueue` using `LLMClient
    /// .shared` and `AppConfig.shared.data.refinement` (`docs/design/03-refinement-batch.md` §8,
    /// same "config.yaml 対応で先行させる" rationale `defaultDiarizationCoordinatorFactory` documents for
    /// `AppConfig.shared.data.diarization`). `KIKIMI_STUB_LLM` is handled internally by `LLMClient`,
    /// not here, same as `defaultSummaryUpdaterFactory` above.
    ///
    /// `docs/design/16-llm-usage-stats.md` section 3: `LLMClient.shared` is wrapped in
    /// `UsageRecordingLLM`, same rationale as `defaultSummaryUpdaterFactory` above.
    ///
    /// `docs/design/28-glossary.md` §3: `AppConfig.shared.data.glossary` and `.glossaryCategories` are
    /// snapshotted here, on the main actor, into plain values captured by the `glossaryProvider` /
    /// `glossaryCategoriesProvider` closures -- mirroring how `config: AppConfig.shared.data.refinement`
    /// itself is a one-time snapshot, not a live `AppConfig` reference (see
    /// `RefinementQueue.glossaryProvider`'s doc comment for why this must not read `AppConfig.shared`
    /// from inside the actor instead).
    ///
    /// `docs/design/42-prompt-overrides.md` §4.3/§5.2: `PromptStore.shared.refreshIfStale()` is called
    /// first (the session-start safety net against a missed/coalesced filesystem watch event -- §5.1),
    /// then `refinement`'s policy body and `glossary-header`'s body are each read once, here, on the
    /// main actor, and captured by `ruleBodyProvider`/`glossaryHeaderProvider`. This -- not anything
    /// inside `RefinementQueue` itself -- is "session-start スナップショット"'s actual mechanism: both
    /// providers are `let`s for this queue's entire lifetime, so a `prompts/refinement.md` /
    /// `prompts/glossary-header.md` edit mid-session is only ever picked up by the *next* session's
    /// queue (§5.2's table, "次のセッション開始時"), exactly like `glossary`/`glossaryCategories` above.
    @MainActor
    static func defaultRefinementQueueFactory(_ sessionHandle: SessionHandle) -> RefinementQueue {
        let glossary = AppConfig.shared.data.glossary
        let glossaryCategories = AppConfig.shared.data.glossaryCategories
        PromptStore.shared.refreshIfStale()
        let ruleBody = PromptStore.shared.policyBody(for: .builtin(.refinement))
        let glossaryHeader = PromptStore.shared.policyBody(for: .builtin(.glossaryHeader))
        let refinementConfig = AppConfig.shared.data.refinement
        return RefinementQueue(
            sessionHandle: sessionHandle,
            llm: UsageRecordingLLM(base: LLMClient.shared, sessionHandle: sessionHandle),
            config: refinementConfig,
            resolvedModel: ModelResolver.resolve(
                candidates: [refinementConfig.model],
                config: AppConfig.shared.data.llm,
                availableProviders: LLMClient.shared.availableProviders
            ),
            glossaryProvider: { glossary },
            glossaryCategoriesProvider: { glossaryCategories },
            ruleBodyProvider: { ruleBody },
            glossaryHeaderProvider: { glossaryHeader }
        )
    }

    /// Production default for `watcherLibrary`: a `WatcherLibrary` rooted at `AppConfig.shared.data
    /// .watchers.presetsDir` (`docs/design/05-watcher-runner.md` §3.2), tilde-expanded via
    /// `FileManager.expandingTildePath(_:)`. Creates the directory if missing (§3.2: "presets_dir が
    /// 無ければ factory 時点で作成する") so a brand-new install's first Watcher preset save never fails
    /// with "no such directory".
    ///
    /// `nonisolated`: unlike `defaultDiarizationCoordinatorFactory`/`defaultWatcherRunnerFactory`
    /// (function *references* passed as still-unevaluated default parameter values), this one is
    /// *called* immediately as `MeetingWorkspaceViewModel.init`'s own default argument expression --
    /// which is evaluated at each call site, not inside `init`'s own `@MainActor` body. `AppConfig`/
    /// `FileManager` touch no main-actor-isolated state, so this is safe to run from any context.
    nonisolated static func defaultWatcherLibrary() -> WatcherLibrary {
        let presetsDirectory = FileManager.expandingTildePath(AppConfig.shared.data.watchers.presetsDir)
        try? FileManager.default.createDirectory(at: presetsDirectory, withIntermediateDirectories: true)
        return WatcherLibrary(presetsDirectory: presetsDirectory)
    }

    /// Production default for `watcherRunnerFactory`: a real `WatcherRunner` using `LLMClient.shared`
    /// and `AppConfig.shared.data.watchers.defaultModel` (`docs/design/05-watcher-runner.md` §3.2/§9).
    /// `KIKIMI_STUB_LLM` is handled internally by `LLMClient`, not here, same as
    /// `defaultSummaryUpdaterFactory`/`defaultRefinementQueueFactory` above.
    ///
    /// `docs/design/16-llm-usage-stats.md` section 3: `LLMClient.shared` is wrapped in
    /// `UsageRecordingLLM`, same rationale as the other two factories above -- `WatcherRunner`'s own
    /// `completeRaw` calls get the identical `llm_usage.jsonl` bookkeeping without knowing this
    /// decorator exists (`UsageRecordingLLM.completeRaw(_:)`'s own doc comment).
    ///
    /// `docs/design/42-prompt-overrides.md` §4.3/§5.1: `PromptStore.shared.refreshIfStale()` runs
    /// synchronously right before the `simple-watcher` prompt override is read, so a watch event this
    /// process somehow missed (kqueue's own limits, §8 #12) still can't leave a stale session-start
    /// snapshot -- then that one `policyBody(for:)` read is captured into `WatcherRunner`'s own
    /// `simpleWatcherTemplate`, fixed for this runner's entire lifetime (§5.2's "次のセッション開始時"
    /// reload timing; a mid-recording `prompts/simple-watcher.md` edit only takes effect for the *next*
    /// session's runner).
    @MainActor
    static func defaultWatcherRunnerFactory(_ sessionHandle: SessionHandle) -> WatcherRunner {
        PromptStore.shared.refreshIfStale()
        let simpleWatcherTemplate = PromptStore.shared.policyBody(for: .builtin(.simpleWatcher))
        return WatcherRunner(
            sessionHandle: sessionHandle,
            llm: UsageRecordingLLM(base: LLMClient.shared, sessionHandle: sessionHandle),
            library: defaultWatcherLibrary(),
            // §7's row for watcher: candidates `[definition.model, watchersDefaultModel]`, resolved
            // at execution time against *live* `AppConfig` (not snapshotted here) -- Watchers reload
            // their preset on every trigger, so the model assignment should track that (see
            // `WatcherRunner.resolveModel`'s doc comment).
            resolveModel: { definitionModel in
                ModelResolver.resolve(
                    candidates: [definitionModel, AppConfig.shared.data.watchers.defaultModel],
                    config: AppConfig.shared.data.llm,
                    availableProviders: LLMClient.shared.availableProviders
                )
            },
            simpleWatcherTemplate: simpleWatcherTemplate
        )
    }

    /// Production default for `wikiExporter`: a real `WikiExporter` capturing `AppConfig.shared.data
    /// .export`'s current value (`docs/design/08-wiki-export.md`) and a `TranscriptMarkdownSource`
    /// capturing `AppConfig.shared.data.diarization` (`docs/design/37-transcript-markdown-copy.md`
    /// §5) so the export shares the same speaker-name resolution as the "copy transcript" feature.
    /// `nonisolated`/called immediately as `MeetingWorkspaceViewModel.init`'s own default argument
    /// expression, same shape as `defaultWatcherLibrary()` above -- reading `AppConfig.shared` touches
    /// no main-actor-isolated state either.
    nonisolated static func defaultWikiExporter() -> WikiExporting {
        WikiExporter(
            config: AppConfig.shared.data.export,
            source: TranscriptMarkdownSource(diarization: AppConfig.shared.data.diarization, voiceprintStore: .shared)
        )
    }
}
