import AVFoundation
import Foundation
import Testing

@testable import Kikimi

/// Unit tests for `OverrideEnrollmentExtractor` (`Kikimi/Diarization/OverrideEnrollmentExtractor.swift`),
/// design section 20 §5.4 stage 2's WAV-slice -> embedding actor. Every existing exercise of this type
/// elsewhere (`MeetingWorkspaceViewModelTests.swift`'s override-aggregate enrollment suite) injects a
/// `FakeOverrideEnrollmentExtractor` that bypasses this actor's own body entirely (missing-file skip,
/// empty-slices/empty-samples `nil`, cross-slice sample concatenation) -- this file is the only place
/// that logic itself is exercised, using a real `AVAudioFileSampleReader` against `WavFileWriter`-
/// produced WAV fixtures (mirroring `SessionAudioSampleReaderTests.swift`'s own precedent) plus a fake
/// `VoiceprintEmbeddingExtracting` so no real CoreML model is touched.
@Suite("OverrideEnrollmentExtractor")
struct OverrideEnrollmentExtractorTests {
    private let sampleRate: Double = 16_000
    private let channels: AVAudioChannelCount = 1
    /// `WavFileWriter` round-trips Float32 through 16-bit PCM (`SessionAudioSampleReaderTests.swift`'s
    /// own precedent); generous enough to absorb that quantization step without masking a genuine
    /// slicing/ordering bug.
    private let quantizationTolerance: Float = 0.001

    private func makeTempSessionDirectory() -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("OverrideEnrollmentExtractorTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(
            at: url.appendingPathComponent("audio", isDirectory: true), withIntermediateDirectories: true
        )
        return url
    }

    private func baseMeta(id: String = "2026-07-01T14-30-00_a1b2c3d4") -> SessionMeta {
        SessionMeta(
            id: id,
            title: "Test Session",
            titleAutoGenerated: true,
            titleAutoNamedOnce: false,
            titleProposal: nil,
            state: .recording,
            createdAt: Date(timeIntervalSince1970: 1_751_000_000),
            startedAt: Date(timeIntervalSince1970: 1_751_000_010),
            endedAt: nil,
            durationMs: 0,
            basedOnSession: nil,
            segmentCount: 0,
            refinedCount: 0,
            appVersion: "0.1.0"
        )
    }

    /// A distinctive ramp (not silence, not a single repeated value) so a slicing/ordering bug shows
    /// up as a value mismatch, not just a count mismatch (`SessionAudioSampleReaderTests.swift`'s own
    /// precedent). `offset` lets two fixtures be told apart even where their ranges would otherwise
    /// overlap in value.
    private func rampValues(count: Int, offset: Float = 0) -> [Float] {
        (0..<count).map { min(max(Float($0) / Float(count) - 0.5 + offset, -1), 1) }
    }

    /// Writes `values` as a mono Float32 WAV at `directory/audio/system_<recordingIndex>.wav`, waiting
    /// synchronously (`WavFileWriter.close()`) until every byte has actually landed on disk.
    private func writeSystemWav(values: [Float], directory: URL, recordingIndex: Int) throws {
        let fileURL = directory.appendingPathComponent("audio", isDirectory: true)
            .appendingPathComponent(AudioCapture.systemFileName(recordingIndex: recordingIndex))
        let writer = try WavFileWriter(fileURL: fileURL, sampleRate: sampleRate, channels: channels, headerFlushInterval: 60)
        let format = AVAudioFormat(standardFormatWithSampleRate: sampleRate, channels: channels)!
        let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: AVAudioFrameCount(values.count))!
        buffer.frameLength = AVAudioFrameCount(values.count)
        let channelData = buffer.floatChannelData![0]
        for (index, value) in values.enumerated() {
            channelData[index] = value
        }
        writer.append(buffer) { _ in }
        writer.close()
    }

    /// Deterministic `VoiceprintEmbeddingExtracting` fake: records every call's samples so tests can
    /// assert on exactly what `OverrideEnrollmentExtractor` concatenated and handed over, without a
    /// real WeSpeaker CoreML model (mirrors `RealtimeDiarizationCoordinatorTests.swift`'s own
    /// `FakeVoiceprintExtractor`).
    private actor FakeEmbeddingExtractor: VoiceprintEmbeddingExtracting {
        private(set) var callCount = 0
        private(set) var receivedSamples: [Float]?
        private let result: [Float]
        private let error: Error?

        init(result: [Float] = [1, 0], error: Error? = nil) {
            self.result = result
            self.error = error
        }

        func extractEmbedding(from samples: [Float]) async throws -> [Float] {
            callCount += 1
            receivedSamples = samples
            if let error {
                throw error
            }
            return result
        }
    }

    private struct FakeExtractionError: Error, Equatable {}

    @Test("empty slices return nil without invoking the embedding extractor at all")
    func emptySlicesReturnNilWithoutExtracting() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let embeddingExtractor = FakeEmbeddingExtractor()
        let extractor = OverrideEnrollmentExtractor(
            sessionHandle: handle, audioReader: AVAudioFileSampleReader(), voiceprintExtractor: embeddingExtractor
        )

        let result = try await extractor.extractEmbedding(slices: [])

        #expect(result == nil)
        #expect(await embeddingExtractor.callCount == 0)
    }

    @Test("a slice whose system_NNN.wav is missing on disk is skipped; with no other slice, the result is nil and the extractor is never invoked")
    func missingFileIsSkippedAndYieldsNilWhenNoOtherSliceExists() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let embeddingExtractor = FakeEmbeddingExtractor()
        let extractor = OverrideEnrollmentExtractor(
            sessionHandle: handle, audioReader: AVAudioFileSampleReader(), voiceprintExtractor: embeddingExtractor
        )

        // system_000.wav is deliberately never written.
        let slices = [EnrollmentSampleSlice(recordingIndex: 0, sampleRange: 0..<1_000)]

        let result = try await extractor.extractEmbedding(slices: slices)

        #expect(result == nil)
        #expect(await embeddingExtractor.callCount == 0)
    }

    @Test("slices are read and concatenated across multiple recording segments, in order, before being handed to the embedding extractor")
    func concatenatesSlicesAcrossRecordingSegmentsInOrder() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let firstValues = rampValues(count: 1_000)
        let secondValues = rampValues(count: 500, offset: 0.1)
        try writeSystemWav(values: firstValues, directory: directory, recordingIndex: 0)
        try writeSystemWav(values: secondValues, directory: directory, recordingIndex: 1)

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let embeddingExtractor = FakeEmbeddingExtractor(result: [9, 9, 9])
        let extractor = OverrideEnrollmentExtractor(
            sessionHandle: handle, audioReader: AVAudioFileSampleReader(), voiceprintExtractor: embeddingExtractor
        )

        let slices = [
            EnrollmentSampleSlice(recordingIndex: 0, sampleRange: 100..<300),
            EnrollmentSampleSlice(recordingIndex: 1, sampleRange: 0..<200)
        ]

        let result = try await extractor.extractEmbedding(slices: slices)

        #expect(result == [9, 9, 9])
        #expect(await embeddingExtractor.callCount == 1)
        let received = try #require(await embeddingExtractor.receivedSamples)
        #expect(received.count == 400)
        let expected = Array(firstValues[100..<300]) + Array(secondValues[0..<200])
        for (actual, expectedValue) in zip(received, expected) {
            #expect(abs(actual - expectedValue) < quantizationTolerance)
        }
    }

    @Test("a missing file among several slices is skipped, but the embedding extractor still runs on the samples that were present")
    func missingFileAmongSeveralSlicesIsSkippedButOthersStillExtract() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let presentValues = rampValues(count: 200)
        try writeSystemWav(values: presentValues, directory: directory, recordingIndex: 0)
        // system_001.wav is deliberately never written.

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let embeddingExtractor = FakeEmbeddingExtractor(result: [4, 4])
        let extractor = OverrideEnrollmentExtractor(
            sessionHandle: handle, audioReader: AVAudioFileSampleReader(), voiceprintExtractor: embeddingExtractor
        )

        let slices = [
            EnrollmentSampleSlice(recordingIndex: 1, sampleRange: 0..<100),
            EnrollmentSampleSlice(recordingIndex: 0, sampleRange: 0..<200)
        ]

        let result = try await extractor.extractEmbedding(slices: slices)

        #expect(result == [4, 4])
        let received = try #require(await embeddingExtractor.receivedSamples)
        #expect(received.count == 200, "the missing system_001.wav slice must be skipped, not zero-filled or thrown")
        for (actual, expectedValue) in zip(received, presentValues) {
            #expect(abs(actual - expectedValue) < quantizationTolerance)
        }
    }

    @Test("every candidate slice's system_NNN.wav missing on disk yields nil, not a thrown error (design section 8's best-effort contract)")
    func everySliceMissingYieldsNilNotAnError() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let embeddingExtractor = FakeEmbeddingExtractor()
        let extractor = OverrideEnrollmentExtractor(
            sessionHandle: handle, audioReader: AVAudioFileSampleReader(), voiceprintExtractor: embeddingExtractor
        )

        let slices = [
            EnrollmentSampleSlice(recordingIndex: 0, sampleRange: 0..<100),
            EnrollmentSampleSlice(recordingIndex: 1, sampleRange: 0..<100)
        ]

        let result = try await extractor.extractEmbedding(slices: slices)

        #expect(result == nil)
        #expect(await embeddingExtractor.callCount == 0)
    }

    @Test("an embedding-extraction failure propagates as a thrown error, and is never swallowed into a nil result")
    func extractionFailurePropagates() async throws {
        let directory = makeTempSessionDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        try writeSystemWav(values: rampValues(count: 100), directory: directory, recordingIndex: 0)

        let handle = SessionHandle(directoryURL: directory, meta: baseMeta())
        let embeddingExtractor = FakeEmbeddingExtractor(error: FakeExtractionError())
        let extractor = OverrideEnrollmentExtractor(
            sessionHandle: handle, audioReader: AVAudioFileSampleReader(), voiceprintExtractor: embeddingExtractor
        )

        await #expect(throws: FakeExtractionError.self) {
            try await extractor.extractEmbedding(slices: [EnrollmentSampleSlice(recordingIndex: 0, sampleRange: 0..<100)])
        }
    }
}
